### ISSUE TITLE
[Request] Folders Feature on Store Locally Files

### ISSUE THREAD

**Issue by BLeaCHeR** [foosel/OctoPrint#1042]
Hi Guys:

Thanks for your efford, i like octoprint (Actually i use it on my Raspi) and i want to suggest the posibility of make folders for files that are stored on the octoprint, with that, the stl files can be more organizated.

i hope you like my sugestion. (and sorry for my english)

Daniel B.

**Comment by foosel** [comment]
Duplicate of #31
