### ISSUE TITLE
[Request] Add events to file manager

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#1092]
The file manager currently doesn't trigger any events to notify other parts of the system about added/moved/removed etc files. The only way for e.g. plugins to get notified about added/uploaded files is listening to the [Upload](http://docs.octoprint.org/en/master/events/index.html#file-handling) event, which only is triggered for actual file uploads, not for files added through other means, e.g. the watched folder.

We should have the file manager generate its own set of events for plugins such as the [AutoSelect Plugin](https://github.com/OctoPrint/OctoPrint-Autoselect) to hook into.

A first attempt at a list:
- FileAdded
- FileRemoved
- FolderAdded
- FolderRemoved

All those events would have a payload structured somewhat like this:
- `location`: The identifier of the storage location of the affected file/folder
- `path`: The path within the storage location to the affected file/folder
- `name`: The name of the affected file/folder

For the SD card stuff we either need to have those events triggered in the comm layer for now, or don't trigger them at all, until that stuff is migrated to a proper `StorageInterface` implementation.

@Salandora do we also need events for copy/move or should it be sufficient to replicate those as `*Added` for a copy and `*Removed` + `*Added` for a move?

**Comment by Salandora** [comment]
Well I guess it would be sufficient to fire an added for copy and added + remived for move.
