### ISSUE TITLE
[Request] M300 payload

### ISSUE THREAD

**Issue by MoonshineSG** [foosel/OctoPrint#1126]
Can the event "Alert" get the parameters as payload (let's say as "sound") ? 

I'm trying to make the RPi play sounds, MP3, MIDI...  instead of the printer itself. Like this I could send a `M300 whateveriwant` and a script (or a octopi plugin?) would play the respective sound. Marlin would ignore other parameters other than 'P' and 'S' 

To test my scripts I added 

```
				if gcode and gcode in gcodeToEvent:
					# if this is a gcode bound to an event, trigger that now
					if gcode == "M300":
						payload = dict(
							sound=cmd[4:].strip()
						)
						eventManager().fire(gcodeToEvent[gcode], payload)
					else:
						eventManager().fire(gcodeToEvent[gcode])

```
in comm.py in `_sendCommand` but I am sure there is a better solution... 

Optionally, if let's say the parameters are not P or S octopi could even skip sending it to the printer...

**Comment by MoonshineSG** [comment]
Never mind this one.. I am writing it as a plugin. But I have a question... Is there a way for a plugin that implements "octoprint.comm.protocol.gcode.sending"  hook to write a short message to the web based terminal ?

**Comment by markwal** [comment]
@MoonshineSG You might be interested in this plugin: https://github.com/AmedeeBulle/StatusLine

**Comment by MoonshineSG** [comment]
@markwal No, I want to write on the Terminal window.

**Comment by foosel** [comment]
It's currently undocumented, but the comm object (which the hook should provide you with) does have a method `_log` with which you can write to the terminal. That's what you want to use here.

**Comment by MoonshineSG** [comment]
Doesn't seams like comm is available ...Maybe indirect ?

**Comment by markwal** [comment]
First parameter to gcode.sending is comm. http://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-gcode-phase

**Comment by foosel** [comment]
[See the docs](http://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-gcode-phase) - very first parameter to the hook.

**Comment by MoonshineSG** [comment]
yup.. it's there! :D and it work perfectly! Thank you!

**Comment by foosel** [comment]
Can we close this then?

**Comment by MoonshineSG** [comment]
Yes, since this in no longer a valid request.
