### ISSUE TITLE
[Request] DSI Display Compatibility

### ISSUE THREAD

**Issue by MrPeppow** [foosel/OctoPrint#1128]
I'm using the relatively new Raspberry DSI Touchscreen with a RPI2 for my Delta. 
Autostarting Chromium in fullscreen mode, 127.0.0.1 as startpage and autologin works like a charm.

Sadly the pagelayout is too big for the screens resolution and zooming out makes it very hard to use. 
A small change for the layout would be enough: Let the "sidebar" allow to move below the part where the temperature graph, etc. is.

**Comment by Grogyan** [comment]
Download the TouchUI plugin
I have and like it

**Comment by foosel** [comment]
That's exactly what plugins are for and why I've added additional plugin types to offer completely separated UIs in the devel branch.
