### ISSUE TITLE
[Request] Show CPU usage

### ISSUE THREAD

**Issue by Lord2Vader** [foosel/OctoPrint#1143]
Hi,

due to some problems with browser on the pi (on TFT-Touchscreen or so) the CPU usage should be shown. If possible per core :)

**Comment by foosel** [comment]
OctoPrint is platform agnostic, therefore that's something that should be done in a plugin.

**Comment by myersCody** [comment]
My undergrad team and I would like to resolve this issue through a plugin, if no one is currently assigned to the task.
Thanks,
Cody Myers & Angela Reinhard

**Comment by foosel** [comment]
Don't know of anyone, so marking as grabbed by you, thanks!

**Comment by foosel** [comment]
Actually a duplicate of #814
