### ISSUE TITLE
[request] layer info in State box

### ISSUE THREAD

**Issue by mrvn** [foosel/OctoPrint#1144]
The state box shows the print time and a progress bar based on (I assume) file offset. It would be nice to also include information about the numbers of layers and current layer / Z height there.

**Comment by foosel** [comment]
Please see this plugin: http://plugins.octoprint.org/plugins/displayz/

Total layers is not possible without having the file analyzed already and also won't work when printing from SD - see the GCODE viewer for that information (which does the analysis in your browser).

**Comment by chatrat12** [comment]
Checkout my plugin LayerDisplay :)

https://github.com/chatrat12/layerdisplay
