### ISSUE TITLE
[Request] I Can't connect my 3D printer.

### ISSUE THREAD

**Issue by KangChungWoo** [foosel/OctoPrint#1184]
Hellow!
I'm undergraduate in South Korea. 
Please help me.

I have 3D printer "3DISON MULTI".
I want to control my printer in Octopi.local. But i can't.

So, I read "I can't get OctoPrint to connect to my printer" of FAQ.
I trying to all baudrate, but i can't connect to my printer.
What is a problem?

And I don't understand second.(That is "2. You can patch the PySerial that is used by OctoPrint. For the latter please take a look at this post to the Mailinglist.")
If i have to patch PySerial, How can i install it to Raspberry Pi? 

This is Terminal Code, when i trying to connect baudrate 115200.

Connecting to: /dev/ttyACM0
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x1e29570, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=30.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M110
Recv: ���
Changing monitoring state from 'Connecting' to 'Closed'
Connection closed, closing down monitor

**Comment by markwal** [comment]
This is a support request, not a feature request as marked.  Please post your question to the octoprint Google group. And when you do, please post more information about your printer. What firmware does it use? What host software does it come with and does the stock host connect? Perhaps you have a Makerbot clone and you need the GPX plugin?
