### ISSUE TITLE
Mobile-friendly UI

### ISSUE THREAD

**Issue by imitation** [foosel/OctoPrint#12]
While the current UI functionally works perfectly on smartphones, it requires frequent zooming and panning (or holding the phone in landscape) to do stuff. An interface with a single column layout and larger buttons would be more suitable for a portrait smartphone.
Lowest priority for me.

**Comment by flyswatter** [comment]
I see there's a REST API for the print server now, and I was thinking it'd be a nice to have a minimal touch-screen interface for one of those 800x480 touch screens for Raspi going around ([Like this one I just ordered](https://www.adafruit.com/products/1678)).  I doubt I'll do my slicing on the raspberry pi anyway, so all it's really doing is receiving files and printing them.  All I really want is basic printer control, file selection, print starting, and an emergency stop.

Then I thought maybe this would look good with a Star Trek themed interface.  Here's my first mockup of a UI.
![octotft-concept-1](https://cloud.githubusercontent.com/assets/542863/5887033/631e8d74-a370-11e4-9328-3475c39097bf.gif)

I already know I'll want to fit more UI in there.  Maybe the busy style patch in the top mid could switch between views, or maybe selecting a file hides the file selector view to make space for extrusion and speed control.

**Comment by seanreynoldscs** [comment]
Hey guys. 
I'd like a safe area with just the data, graphs, image feeds, timelapse, etc all read only set apart from the high level end print, turn off lights, pause print, change filament, etc all normal commands set apart from advanced features like turn off fans, turn off motors, move build plate down or up, etc all commands which would break a print if things were going just fine.

That way I can open the app and not worry about my daughter coming over climbing up and accidently hitting the turn off motors button. 

I can help I guess too. I can do the iOS app if there is an sdk example like others have mentioned. 

Thoughts?

**Comment by quillford** [comment]
@seanreynoldscs https://github.com/quillford/OctoControl-iOS

**Comment by quillford** [comment]
I've also just started work on a web app as an OctoPrint front end. https://github.com/quillford/OctoControl

**Comment by markwal** [comment]
If you've come here looking for a mobile web UI, you might want to try the TouchUI plugin from @BillyBlaze http://plugins.octoprint.org/plugins/touchui/

**Comment by flyswatter** [comment]
Awesome, nice work!

- Dan

**Comment by ssshake** [comment]
Ya thats pretty great. I'm excited to check it out.

**Comment by ssshake** [comment]
Also I would love an LCARS UI for this!!!. I have a spare 7" touch screen that I could connect to the pi and totally would if it was LCARS. Let me know if you proceed with this.

**Comment by flyswatter** [comment]
Oh I will. First I'll have to get my own touch screen..

- Dan

**Comment by foosel** [comment]
With the TouchUI plugin there's definitely a solution for that now, so I'm closing this.

Big kudos to @BillyBlaze!

**Comment by MoonshineSG** [comment]
If anyone needs a different iOS optimisedU...   https://github.com/MoonshineSG/OctoPrint-Mobile
