### ISSUE TITLE
[request] User print tracking and who's printing in status.

### ISSUE THREAD

**Issue by daned33** [foosel/OctoPrint#1201]
Hi, 

Our hacklab uses octoprint for our 3d printers! And we'd like to have individual print usage (how long they've printed for and how much material, and what files they've uploaded)

and also on the status tab who's printing at the moment!

Would it be possible to implement a feature like this?

Thanks,

Dan

**Comment by gddeen** [comment]
Dan, The ClientOpened and ClientClosed server events could be "hooked" and presented in a list on the screen showing the last N users and time. Someone would have to write a plugin to do it.

**Comment by daned33** [comment]
Hmm, thanks gddeen.

Ill take a look at plugin development in that case if I get a chance.

**Comment by foosel** [comment]
I think this is actually a duplicate or an extension of #652
