### ISSUE TITLE
Octoprint renames auto0.g to auto0.gco on upload to SD

### ISSUE THREAD

**Issue by Lenbok** [foosel/OctoPrint#1314]
#### What were you doing?

Marlin supports running gcode files automatically on startup. This is a handy way to run printer initialization commands or store settings that cannot be saved to EEPROM.

If you use octoprint to upload auto0.g to the SD card, it is renamed to auto0.gco

#### What did you expect to happen?

The file should be uploaded with the name provided.

#### What happened instead?

The file was renamed to auto0.gco

#### Branch & Commit or Version of OctoPrint

1.2.10

#### Printer model & used firmware incl. version

Mendel90, Marlin (an oldish version)

#### Browser and Version of Browser, Operating System running Browser

I have read the FAQ.

**Comment by foosel** [comment]
Fixed in `maintenance` and `devel` branches, will be part of the next release.
