### ISSUE TITLE
Can't delete mp4 timelapses and wrong filename displayed in notification of completion

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#1320]
With the addition of the ability to view and download mp4's through a wrapper script it seems you can't delete them. Additionally the wrong file extension is used when displaying the rendering complete notification.

https://github.com/guysoft/OctoPi/issues/184 wrapper script

----

#### What were you doing?

Testing time lapse mp4 rendering

#### What did you expect to happen?

Render out to mp4 and be able to delete / download mp4

#### What happened instead?

mp4 rendered fine, downloads work, deleting doesn't remove any files. Additionally even though mp4 is rendered the mpeg extension is still used in the notification of rendering completion. I suggest perhaps simply removing the extension all together in the notification popup since detecting the type of file is probably impossible when using the wrapper script.

#### Branch & Commit or Version of OctoPrint

Version: 1.2.11.dev12+g119f727 (maintenance branch)

#### Printer model & used firmware incl. version

Mendel90 Sturdy running Marlin from ye olde times

#### Browser and Version of Browser, Operating System running Browser

Chrome Version 49.0.2623.112 m on windows 10 pro

#### Link to octoprint.log

https://gist.github.com/ntoff/09fb33daaf309c100116c20aaf96b32f

#### Link to contents of terminal tab or serial.log

nothing there aside from the usual temperature request / responses

#### Link to contents of Javascript console in the browser

Nothing obvious http://i.imgur.com/uoB65wf.png and it's pretty empty

#### Screenshot(s) showing the problem:

screenshot of incorrect file extension
http://i.imgur.com/A3X2Jy2.png

I have read the FAQ.

**Comment by foosel** [comment]
Solved on both `devel` and `maintenance` branch, will be part of the next release.
