### ISSUE TITLE
Disk space thresholds in settings needs unit

### ISSUE THREAD

**Issue by nicolinux** [foosel/OctoPrint#1338]
#### What were you doing?

Tried to understand which unit size the "Disk Space Thresholds" in the settings->folders area expects.

#### What did you expect to happen?

See the unit.

#### What happened instead?

Didn't see the unit :)

#### Branch & Commit or Version of OctoPrint

1.2.11 (master)

#### Screenshot(s) showing the problem:

[Imgur](http://i.imgur.com/SHXDk8H.png)

I have read the FAQ. 👍

**Comment by ntoff** [comment]
Can't you just type in something like 50MB and it'll set it to 50 megabytes, or 1GB and it'll set it to 1 gigabyte.

**Comment by foosel** [comment]
You can, should be documented though. Now it is ;)

**Comment by foosel** [comment]
... correction. Now it is for the gcode size thresholds, not the disk space thresholds m) reopened

**Comment by foosel** [comment]
Now it's also documented for the disk space threshold.
