### ISSUE TITLE
Timleapse rendering message does not dissapear on render fail

### ISSUE THREAD

**Issue by derpicknicker1** [foosel/OctoPrint#1343]
#### What were you doing?
I tried to use a relative snapshot URL. This let the timleapse modul throw many exception. Ok. Will not work. Not that bad for me. BUT after stopping the Print, i got the message that the video will be rendered (at the top right of browser). This message will not dissappear or change for hours (sure i can close).

#### What did you expect to happen?
I expected that the "rendering info" will tell me at some point that the rendering failed.
I also expected that octoprint let me know if the snapshot url will not work instead of silently throw exceptions.

#### What happened instead?
The "I'm rendering" anouncement stays open forever with no feedback. 

#### Branch & Commit or Version of OctoPrint

1.2.11 (master)

#### Printer model & used firmware incl. version
Printer moddel : custom
FW: Marlin 1.0.2

#### Browser and Version of Browser, Operating System running Browser
Chrome on WIN10 (both up to date)

#### Link to octoprint.log

https://gist.github.com/derpicknicker1/ed2886a970506482e793bd6e4faf300c

#### Link to contents of terminal tab or serial.log

not relevant

#### Link to contents of Javascript console in the browser

got no message from javascript

#### Screenshot(s) showing the problem:
:computer: 

I have read the FAQ.

**Comment by foosel** [comment]
Fixed in `maintenance` and `devel` branches, will be part of the next release.
