### ISSUE TITLE
[Request] Larger spinning busy wheel...

### ISSUE THREAD

**Issue by itsnotlevel** [foosel/OctoPrint#1376]
We have multiple users in our work place and would love to see something, maybe a larger busy spinning wheel...(in the center of the screen?) since you cant do anything until the last process has finished then, why not? Wheel size....maybe 300 times the size of the tiny one....

Paul

**Comment by foosel** [comment]
Sorry but: what wheel are you even talking about?

**Comment by itsnotlevel** [comment]
Oh sorry, its a plugin.... 
https://github.com/OctoPrint/OctoPrint-RequestSpinner

Paul

On 06/17/2016 10:35 AM, Gina Häußge wrote:
>
> Sorry but: what wheel are you even talking about?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/foosel/OctoPrint/issues/1376#issuecomment-226802661>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ALUxUf2x9DfO2l86ZKSX4DzBVGUiyFTcks5qMr7UgaJpZM4I4cpf>.
>

-- 

Paul

**Comment by foosel** [comment]
In that case, wrong bug tracker.

And you can in fact do things while that thing is spinning, it's merely showing background activity/server communication. Having it take up the whole screen would make the application pretty much unusable most of the time.

**Comment by itsnotlevel** [comment]
Good point.... Thank you

Paul
