### ISSUE TITLE
[Request]Add folder for gcode/stl files

### ISSUE THREAD

**Issue by Wanegain** [foosel/OctoPrint#1381]
I regularly prints the same parts, I wondered if it would be possible to sort the files in folders (eg a "3D printer" folder for the files to the printer itself, folder "Arduino Case" with files for different boxes depending on the Arduino, etc ..)? This would be much easier to find the right files in Octoprint.

Thank you !

**Comment by foosel** [comment]
Indeed, which is why it is already implemented in the `devel` branch and will be part of the 1.3.0 release :)

**Comment by Wanegain** [comment]
Great news ! Thank you for the huge work :+1:
