### ISSUE TITLE
M3D restarting the print

### ISSUE THREAD

**Issue by bobbypop999** [foosel/OctoPrint#1418]
I was just printing something and wanted to check how long it had left.

I expected the print to carry on normally 

Instead the printer stopped and restarted the print

I am using the current version.

I am using the M3D Micro.

I am using safari on an iPad.

I have read the FAQ.

**Comment by foosel** [comment]
Please fill out the **full** ticket template. Currently there are no logs, no version number, no terminal output, no JavaScript console. That stuff is requested for a reason :)

**Comment by donovan6000** [comment]
Make sure your using the latest version of [M33 Fio](https://github.com/donovan6000/M33-Fio), which at the time of writing this is V1.0. There's a bug in M3D Fio V0.35 and newer that can cause this to happen whenever a client connects to OctoPrint. Having both M3D Fio and M33 Fio installed at the same time can cause unexpected behavior, so it's recommended that you first uninstall M3D Fio then install M33 Fio.

**Comment by bobbypop999** [comment]
I can't get the other information though.

**Comment by bobbypop999** [comment]
Thank you it is now fixed.
