### ISSUE TITLE
Cost Estimator Plugin does not show available version in Software update

### ISSUE THREAD

**Issue by bmbeverst** [foosel/OctoPrint#1429]
#### What were you doing?
I Installed the Cost Estimator Plugin. http://plugins.octoprint.org/plugins/cost/
I did it manually and with the plugin manager. The results are the same.

#### What did you expect to happen?
I expected the software update plugin to show the available version as being the same as the installed version.

#### What happened instead?
It should no version as being available. It is blank next to available.

#### Branch & Commit or Version of OctoPrint
1.2.15 stable

#### Browser and Version of Browser, Operating System running Browser
Chromium OS 
Version 50.0.2661.105 (64-bit)
Platform 50.1.99 (Developer Build - neverware) developer-build chromeover64

#### Screenshot(s) showing the problem:
![noaval](https://cloud.githubusercontent.com/assets/603632/17279733/506541a2-574a-11e6-9407-026dc94a5ea6.png)

I have read the FAQ.

**Comment by foosel** [comment]
That's an issue with the cost estimator plugin's implementation of the software update information hook, not with OctoPrint. You need to report it there instead.

**Comment by bmbeverst** [comment]
OK, will do! Can you point me to any docs for how to set that up?

**Comment by foosel** [comment]
Using the issue tracker here: https://github.com/jasiek/OctoPrint-Cost/issues

The plugin says to track Github releases but didn't actually create any Github releases, only tags.
