### ISSUE TITLE
STL Viewer causes TypeError in octoprint.plugins.softwareupdate

### ISSUE THREAD

**Issue by bmbeverst** [foosel/OctoPrint#1430]
#### What were you doing?
Installed the STL viewer plugin and checked for an update.

#### What did you expect to happen?
Expected to see the installed and available stl viewer versions.

#### What happened instead?
Instead the version is unknown and installed and available are blank.

#### Branch & Commit or Version of OctoPrint
1.2.15 stable

#### Browser and Version of Browser, Operating System running Browser
Chromium OS 
Version 50.0.2661.105 (64-bit)
Platform 50.1.99 (Developer Build - neverware) developer-build chromeover64

#### Link to octoprint.log

https://gist.github.com/bmbeverst/bda4986a92d58f1b5012097186616e92

#### Screenshot(s) showing the problem:
![unknowversion](https://cloud.githubusercontent.com/assets/603632/17279784/ec985608-574b-11e6-9138-5cfb5a80ac3e.png)

I have read the FAQ.

**Comment by foosel** [comment]
That's an issue with the plugin's implementation of the software update information hook, not with OctoPrint. You need to report it there.

**Comment by jneilliii** [comment]
Gina, is there a change documented somewhere on the software update information hooks?  I don't think this was an issue until recent versions with my plugin.  I've looked at the changelog and didn't see anything specific.

**Comment by foosel** [comment]
@jneilliii there was no change at all in how update checks are parsed for ages. Taking a quick look at your source your plugin doesn't seem to define any however, so I'm not sure why it's even showing up in the software update dialog in the above screenshot (it doesn't show up for me when giving it a quick test). Maybe another plugin that (accidentally) hijacked your identifier for the update configuration?
