### ISSUE TITLE
Disappearing Video

### ISSUE THREAD

**Issue by tjwitman** [foosel/OctoPrint#1454]
I am running Version: 1.2.15 (master branch) of Octopi on an RP3 with a 7" Raspi display and a 5 MP Raspi camera.  I've been using your program for quite a while but just recently upgraded to the newest version.  Since then, if I'm watching the video on the Control tab, it disappears and leaves a blank screen after a random amount of time.  I can switch tabs and watch the GCode Viewer for 30 seconds and go back to Control where the video is once again visible for a time.
Have you put a time delay in the video feed for some reason?  

The only difference I have made is I put the RP3 and the screen in a different enclosure and have it running with a battery and an Adafruit voltage regulator/battery maintainer.  I have it running on a 2.5 amp power supply, again from Raspi.

----

#### What were you doing?

Running a print on my Folger Tech 2020 i3, which I've been running without problems for a year now.  I am running a program uploaded to Octoprint and directly feed to it without an SD card.  I am running Marlin 1.0.RC3 ever since it was released.

#### Branch & Commit or Version of OctoPrint

[Can be found in the lower left corner of the web interface.]

#### Printer model & used firmware incl. version

[If applicable, always include if unsure.]

#### Browser and Version of Browser, Operating System running Browser

[If applicable, always include if unsure.]

#### Link to octoprint.log

[On gist.github.com or pastebin.com. Always include and never truncate.]

#### Link to contents of terminal tab or serial.log

[On gist.github.com or pastebin.com. If applicable, always include if unsure or
reporting communication issues. Never truncate.]

#### Link to contents of Javascript console in the browser

[On gist.github.com or pastebin.com or alternatively a screenshot. If applicable -
always include if unsure or reporting UI issues.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

I have read the FAQ.

**Comment by foosel** [comment]
> Have you put a time delay in the video feed for some reason?

No. And in fact, it is technically completely impossible to influence your webcam stream at all. This is also explained in the FAQ: https://github.com/foosel/OctoPrint/wiki/FAQ#my-webcam-is-not-working

> The only difference I have made is I put the RP3 and the screen in a different enclosure

Considering that the webcam stream vanishing sounds like a network issue, my money would be on this being the cause of your issues. The RP3 only has a tiny chip antenna and depending on the enclosure type and positioning of the Pi that could degrade Wifi connectivity enough to cause issues with the stream. 

In any case, this is not an OctoPrint problem. The fact that it shows you your stream at all (and reloads it correctly when you switch to the Control tab) indicates that everything is alright regarding the actual part that OctoPrint does here. Check your connectivity. If that doesn't help, seek support on the [mailing list](https://groups.google.com/group/octoprint) or the [G+ community](https://plus.google.com/communities/102771308349328485741). This is the wrong place - it's a bug tracker.
