### ISSUE TITLE
Feature Request: Docking Script Button.

### ISSUE THREAD

**Issue by BigBox3D** [foosel/OctoPrint#1497]
In the control tab have a button similar in looks to the home buttons but one which launches a custom script, editable in the settings GCODE Scripts page.

The purpose is to execute GCODE which can be used to park the head in a particular location and or perform a nozzle wiping cycle before parking.

**Comment by Salandora** [comment]
Uhm you know that you can define parametriezed gcodes and add buttons to the control tab yourself? 
You'll find how on the really nice documentation page somwhere here: http://docs.octoprint.org

**Comment by BigBox3D** [comment]
I did not. I shall look into it. Thanks :)

**Comment by foosel** [comment]
Definitely possible via custom controls, closing for now. If you are missing something from what's possible via custom controls for your specific use case, feel free to request a reopen (and explain ;)).
