### ISSUE TITLE
[Request] Show time since last update check in update settings

### ISSUE THREAD

**Issue by hovissimo** [foosel/OctoPrint#1521]
It would be handy if we could show the age of the update check cache in the settings screen.  I can click 'Force check for update' in current master (354042) but I have no feedback that anything actually occurred.  Seeing the update cache timer reset would reassure me that something is happening.

**Comment by foosel** [comment]
Implemented on `maintenance`, soon `devel`, to be released with 1.3.3.

**Comment by foosel** [comment]
1.3.3 was just released.
