### ISSUE TITLE
[Request] Include username of user who started print in "State" pane

### ISSUE THREAD

**Issue by twilde** [foosel/OctoPrint#1545]
When access control is turned on, it would be really helpful to have the username of the user who started a print (or loaded the file for printing, or maybe both?) in the "State" pane, either all the time or as an option. Thanks for the awesome software!

**Comment by somebugis** [comment]
Hello @twilde 
I'll try do to it this week

**Comment by somebugis** [comment]
What do you mean by have the username ? Just the user who inquire his name before the print or rather a login page ?

**Comment by twilde** [comment]
I was referring to the username the person logged in with, when access control is turned on.

**Comment by somebugis** [comment]
![login](https://cloud.githubusercontent.com/assets/23096933/20007577/3691dd32-a29d-11e6-98b2-d20f861d8eb5.png)


This one ?

**Comment by twilde** [comment]
Yup, that's the one!

**Comment by cmtec** [comment]
+1 
When running a multi user environment this would help a lot.

**Comment by foosel** [comment]
This is available on `maintenance` and `devel` and will be released as part of 1.3.9
