### ISSUE TITLE
[Request] Confirmation before stopping a print

### ISSUE THREAD

**Issue by goutamenara** [foosel/OctoPrint#1557]
Please add  a confirmation dialog before stopping an ongoing print. Because when printing using screen, the display turns off after sometime and if we happen to touch the stop button while trying to see the status of print it just stops the print. So it will be good if it asks for a confirmation before stopping the print.

**Comment by derpicknicker1** [comment]
See #1550

**Comment by foosel** [comment]
Implemented in `devel`, `1.3.0rc2` and will be in stable `1.3.0` of course.
