### ISSUE TITLE
[Request] Display latest successful print duration as metadata

### ISSUE THREAD

**Issue by Finkes** [foosel/OctoPrint#1576]
I would like to see the duration of my last successful print of a certain object, so I know, how long it will take me to print it again. The estimation label could be used for that, as you will know more or less exactly how long it will take after you have printed it once.

The reason for this request is, that the estimation is often not that precise.

![image](https://cloud.githubusercontent.com/assets/6247179/20029940/c659f324-a35a-11e6-9782-5b6e07e24cf0.png)

**Comment by JohnOCFII** [comment]
@Finkes - The Print History plugin will give you the information you desire.  
http://plugins.octoprint.org/plugins/printhistory/

**Comment by Finkes** [comment]
alright I will give it a try. thanks!
