### ISSUE TITLE
[Request] More Timelapse Ending Options - Real Time Post Roll

### ISSUE THREAD

**Issue by cinderblock** [foosel/OctoPrint#1624]
I enjoy the ending extension timelapse feature that was added because of #384.

However, the nice feature of the delta-z based captures where the last frame is repeated for a few seconds is sorely missing from the time based timelapse. It is annoying to wait for many minutes just to get a couple more seconds of data, often after the part has been removed since my hand was in the way.

Even better, in my humble opinion, it would be nice to be able to record the postroll in real time. I've had a few occasions where I messed up the end GCode and that made my nozzle move quickly into my part. This was completely missed by the timelapse video. You could even make it capture at half or variable time.

#### Branch & Commit or Version of OctoPrint

`Version: 1.2.18 (master branch)`

I have read the FAQ.

**Comment by foosel** [comment]
Quoting the [change log for 1.3.0rc2](https://github.com/foosel/OctoPrint/releases/tag/1.3.0rc2) (with 1.3.0rc3 being available on the "Devel RCs" [release channel](https://github.com/foosel/OctoPrint/wiki/Using-Release-Channels)):

>   * [#1422](https://github.com/foosel/OctoPrint/issues/1422) - Added option for post roll for timed timelapse to duplicate last frame instead of capturing new frames. That makes for a faster render at the cost of a still frame at the end of the rendered video. See also [#1553](https://github.com/foosel/OctoPrint/pull/1553).

So the last-frame-repetition option for delta-t/timed timelapses is already implemented and will be available in 1.3.0 which I'll hopefully be able to release within the next week.

Recording real time is not possible, at least not without what would probably boil down to a full rewrite of the timelapse component. It only knows how to capture snapshots from a URL (25 snapshots per second won't work) and the rendering of the timelapse does not allow for variable frame rate (which you'd need for a real-time visualization after the print).
