### ISSUE TITLE
[Request] Show last time for performed prints

### ISSUE THREAD

**Issue by bdynamic** [foosel/OctoPrint#1626]
For a file which was printed the gcode file gets green and in the extended view there are the following information included:

Name: snowflake_gift_4x.gcode
Uploaded: a day ago
Size: 2.6MB
Filament: 1.50m / 3.61cm³
Estimated print time: 50 minutes
Last printed: a few seconds ago

My feature proposal is, that instead of the "Estimated print time" which can be rather inaccurate (does octopi have a learning module about the print time?) the "Time of last print" should be shown.
This would be helpful for reprinting objects.

#### What were you doing?
Printing a normal print and succeeding in printing

#### What did you expect to happen?
After the print finished the extended view at the file selector doesn't show the last real print time

#### What happened instead?
The time it took for the file to be printed the last time should be shown instead of not so accurate "Estimated print time:"

**Comment by ntoff** [comment]
Pretty sure this is already a thing https://github.com/foosel/OctoPrint/pull/1522 Is that what you're suggesting?

**Comment by foosel** [comment]
This is from a running OctoPrint 1.3.0 install:

![image](https://cloud.githubusercontent.com/assets/83657/21047118/6bb40f18-be08-11e6-8f1b-66f29ee81b06.png)

So yep, already taken care of.
