### ISSUE TITLE
[Request] Button wording on cancel print confirmation

### ISSUE THREAD

**Issue by pr3sidentspence** [foosel/OctoPrint#1656]
The wording on this confirmation box is ambiguous. The options are "cancel" and "proceed." Am I cancelling cancelling, proceeding with printing, proceeding with canceling, or cancelling printing? Perhaps, "Are you sure you want to cancel?" "Yes" & "No"

**Comment by foosel** [comment]
![image](https://cloud.githubusercontent.com/assets/83657/21261423/8ec16720-c38b-11e6-9502-ef12554fdd9a.png)

Implemented in commit 2669e79, will be in 1.3.1 (RC in early January)
