### ISSUE TITLE
Hint for keyboard controls visible when keyboard controls are disabled.

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#1660]
----

#### What were you doing?

Disabling keyboard controls that pop up over the webcam image (this part functions)

#### What did you expect to happen?

That the hint below the image would also disappear.

#### What happened instead?

"Hint: If you move your mouse over the picture, you enter keyboard control mode." appears even though keyboard controls are disabled.

#### Branch & Commit or Version of OctoPrint

Version: 1.3.0 (master branch) 

#### Plugins Active

none, I disabled them all to make sure it wasn't one of them.

#### Printer model & used firmware incl. version

unrelated

#### Browser and Version of Browser, Operating System running Browser

google chrome + firefox both on windows 10 pro

#### Link to octoprint.log

n/a

#### Link to contents of terminal tab or serial.log

n/a

#### Link to contents of Javascript console in the browser

n/a

#### Screenshot(s) showing the problem:

![image](https://cloud.githubusercontent.com/assets/9030085/21255057/5337364c-c3b5-11e6-92c6-1b4219591dce.png)

![image](https://cloud.githubusercontent.com/assets/9030085/21255071/5ff08f3c-c3b5-11e6-9468-308fa0e1a95d.png)

I have read the FAQ.

The fix: 

Add a check to https://github.com/foosel/OctoPrint/blob/master/src/octoprint/templates/tabs/control.jinja2#L22 to also check whether keyboard controls are in fact enabled.

`<div data-bind="visible: keycontrolPossible && $root.settings.feature_keyboardControl()">`

Tested in chrome / firefox on windows 10 and chrome on windows 7.

**Comment by foosel** [comment]
Part of 1.3.1 which has just been released.
