### ISSUE TITLE
[Request] Support filtering folder names in Files UI

### ISSUE THREAD

**Issue by twilde** [foosel/OctoPrint#1667]
(Maybe this is actually a bug?)

It looks like folder names aren't included when filtering in the Files UI - for example, I have a folder named "twilde" and typing "tw" results in no results, while typing a substring of an actual file in the root folder still works as it always did. It would be awesome if folder names could be searched for just like files. Thanks!

**Comment by Salandora** [comment]
Fixed this in devel

**Comment by foosel** [comment]
I also backported the fix by @Salandora to `maintenance`. It will be released with 1.3.1

**Comment by foosel** [comment]
Part of 1.3.1 which has just been released.
