### ISSUE TITLE
Unable to create folders in OctoPrint Web Console

### ISSUE THREAD

**Issue by lastrogue** [foosel/OctoPrint#1671]
#### What were you doing?

I was attempting to create a new folder under the 'Files' section of the OctoPrint web application. I have tried multiple names for the folder including 'toys', 'Toys', 'toys2', 'Animals', 'animals'.

I have also tried deleting folders that I have had successfully created in the past and re-creating folders without success.

#### What did you expect to happen?

I expected the folders to be created as they have successfully been in the past.

#### What happened instead?

There was no confirmation of the folder being created and the folder does not appear in the list.

#### Branch & Commit or Version of OctoPrint

Version: 1.3.0

#### Printer model & used firmware incl. version

Monoprice Maker Select v2.1

#### Browser and Version of Browser, Operating System running Browser

Browser: Chrome Version 55.0.2883.87 m (64-bit)

Operating System: Windows 10 Enterprise 64-bit Anniversary Edition

#### Link to octoprint.log

octoprint.log Pastebin link:
http://pastebin.com/4CW77Rtd

#### Link to contents of terminal tab or serial.log

Terminal Log pastebin link:
http://pastebin.com/rsZj8yu5

#### Link to contents of Javascript console in the browser

screenshot of javascript console:
https://i.imgur.com/hIZBb0J.png

#### Screenshot(s) showing the problem:

Screenshot showing my steps to reproduce:

Step 1 - Click to create folder: https://i.imgur.com/TJzdSJW.png
Step 2 - Enter folder name and click create: https://i.imgur.com/ymp9u9x.png
Step 3 - No folder is created: https://i.imgur.com/O9TVI2F.png

[If applicable. Always include if unsure or reporting UI issues.]

I have read the FAQ.

**Comment by Salandora** [comment]
Hello,

try this:
Click the Wrench and unselect the Hide empty Folders option.
This should fix your problems, please report back.

**Comment by ntoff** [comment]
>Click the Wrench and unselect the Hide empty Folders option.

I was about to comment and say creating the folders works fine here using those steps (using the maintenance branch) then saw this. Why is that even an option? I mean I get it, you don't want empty folders cluttering up the UI but as soon as you create a folder it's going to be empty and thus invisible. Hiding successful prints I get, upload a bunch of stuff to print and as it gets finished it automatically gets hidden but why hide folders? Maybe there needs to be a notice of like "15 files (9 hidden), 3 folders (2 hidden)" somewhere in that file list just to let people know that stuff IS there, it's just hidden.

**Comment by Salandora** [comment]
@ntoff I think you're right about the notice this would be helpful, and yes the hide empty folders filter is basically to not clutter the small files list section with empty folders.
And maybe the hide empty folders option should not be enabled by default, because this leads to exactly this. People think it'll not working.
Hmm @foosel what do you think about this?

**Comment by lastrogue** [comment]
@Salandora That did the trick, and sure enough I was able to see all the different folders I had created! Thank you for pointing that out. And I agree with @ntoff that a notification would be helpful pointing out x files hidden and y folders hidden, or something to that effect.

**Comment by foosel** [comment]
> And maybe the hide empty folders option should not be enabled by default, because this leads to exactly this.

Uhm. It isn't, for this reason actually. From a fresh upgrade to 1.3.0:

![image](https://cloud.githubusercontent.com/assets/83657/21770219/a0ede7b6-d682-11e6-80c5-8ac438d9b24f.png)

But I like the idea of a "n files (m hidden), x folders (y hidden)" display. I'm a bit at a loss though were to stuff that...

**Comment by mrardon** [comment]
I was bitten by this as well, I had changed it to hide the folders but forgot about the setting. 

Not knowing all the space restrictions/usage but above the Free/Total maybe? Could be as simple as "N hidden" if you don't want to be verbose.

**Comment by jaustindavid** [comment]
+1 bitten by this.  I have two octoprint servers, and one of them (older, 1.3.0 at creation) got this option.  I have no idea how.  I definitely was able to create a fair series of folders, then "lost" the ability (due to this feature).

**Comment by foosel** [comment]
Too many people bitten by this combined with this sudden "uh, what value does this actually add feeling" equals removed filter.

Also I think my above comment claiming it was disabled by default was wrong (and probably falsified by some left over bits in my browser profile). Anyhow - it's gone now on `maintenance` and soon `devel` and that will be part of the 1.3.2 release.

**Comment by foosel** [comment]
1.3.2 was just released. Funnily enough I managed to remove that option, but left the context menu entry for it 🤦‍♀️ . So while that shouldn't bite people any more, we now have a context menu entry that does nothing. Stupid, will be fixed in 1.3.3.

**Comment by foosel** [comment]
And already solved on `maintenance`, soon `devel`, to be released with 1.3.3. Again - stupid ;)

**Comment by foosel** [comment]
1.3.3 was just released.

**Comment by OutsourcedGuru** [comment]
What's interesting about this from a UI standpoint is that if—upon toggling the ShowEmptyFolders feature ON when creating a new folder—the user may suddenly see many (surprising) new (previously-empty) folders as a result of this programming.

With respect to usability, upon creating a new folder it may be worth instea just sending a notice/alert to the screen to remind them that the option is currently toggled OFF and where they may find it.

**Comment by foosel** [comment]
The option was removed in 1.3.3 ;)

**Comment by OutsourcedGuru** [comment]
Honestly, [I personally adjusted](https://github.com/OutsourcedGuru/roboc2-pi-samba-upgrade) my /etc/samba/smb.conf file and then I'm able to push files to my Octoprint via Finder (OSX) via...

**Cmd-K** then **smb://pi@charming-pascal.local/sharename**

This seems to work quite well. It requires you to press the Refresh button within the OctoPrint -> Files area to see the update.
