### ISSUE TITLE
Octoprint fails to slice and print on center of bed

### ISSUE THREAD

**Issue by InMuSights** [foosel/OctoPrint#1677]
Have a Monoprice Flashforge Creator with default firmware.  Using Chrome. OP is Version 1.3.0 (master branch).

I have attempted to print from OP but the offset ?? is putting the center to the back right corner of the bed.

If I use Makerbot software to print the item is centered but attempts to use Cura and upload gcode is always offset unless I radically shift the image in Cura Desktop.

Next I thought that if I exported a profile to OP that it might print but the same thing happens.  In CuraEngine 15.04 there is a check to use Origin 0,0 and selecting that appears to center but the bed travels to the bottom of the build area - thus wasting material.

No ideas on next step...

**Comment by foosel** [comment]
@markwal Could this be a GPX (configuration) issue?

@InMuSights OctoPrint only streams to the printer whatever is in your GCODE files. If that doesn't cause your prints to be centered, it's an issue with either your slicer (Cura) or - as far as I understand, @markwal would know better - your GPX plugin configuration. OctoPrint is only the messenger in the middle and I can't fix anything on my end to make your prints be centered.

**Comment by markwal** [comment]
Yes, this is likely to be a configuration issue.  Makerbot defined the origin to be the center.  Here, my guess is that the slicer (Cura) hasn't been told.  Most slicers support this because delta printers generally also find the origin at the center to be convenient.
