### ISSUE TITLE
[Request]  Support for Marlin AUTO_REPORT_TEMPERATURES

### ISSUE THREAD

**Issue by MoonshineSG** [foosel/OctoPrint#1679]
Marlin has an advanced setting, that allows the firmware to auto report temperatures, at selected intervals, without the need of constant pull using M105. The availability of auto report can be found out via M115 when `EXTENDED_CAPABILITIES_REPORT` is turned on.

See more http://reprap.org/wiki/G-code#M155:_Automatically_send_temperatures

**Comment by shacal** [comment]
+1

**Comment by ntoff** [comment]
so apparently repetier firmware also supports that, +1 from me too.

**Comment by fiveangle** [comment]
is this on the todo list ?

**Comment by foosel** [comment]
@fiveangle no, it just got moved off the TODO list because the above commit implements it ;)

Already available on the `maintenance` branch, soon on `devel`, will be released with 1.3.5.

**Comment by foosel** [comment]
As a sidenote though, current Marlin mainline still has both `EXTENDED_CAPABILITIES_REPORT` and `AUTO_REPORT_TEMPERATURES` disabled in all included example configurations, so unless you've intentionally enabled it, no dice. See also [my comments here](https://github.com/MarlinFirmware/Marlin/issues/5139#issuecomment-274097917).

I fear this also means that the next printer generation shipping with direct and unmaintained forks out of their vendor's factories will not be able to take advantage of either capability reporting or temperature autoreporting.

**Comment by ntoff** [comment]
as a repetier firmware user, I welcome our new inferior marlin underlings.

**Comment by foosel** [comment]
1.3.5 was released yesterday.
