### ISSUE TITLE
[Request] Wait for temperature to stabilize

### ISSUE THREAD

**Issue by kontakt** [foosel/OctoPrint#1680]
I have a file that changes temperatures at different points in the print, and the hotend can drop a lot before the PID picks up correctly, leading to a bad layer on occasion. It would be helpful to have the printer pause at a small z-height above the print until the temperature is stable.

**Comment by VBen** [comment]
just use M109 in your gcode to set the temperature
[M109:Set Extruder Temperature and Wait](http://reprap.org/wiki/G-code#M109:_Set_Extruder_Temperature_and_Wait)
this M-Code will wait until the temperature is in a specific target window

**Comment by kontakt** [comment]
That's a good point. I'll make that change.
