### ISSUE TITLE
[Request] Please display the name of the folder when one is opened in Files.

### ISSUE THREAD

**Issue by CyberHugger** [foosel/OctoPrint#1712]
#### What were you doing?

Opened a folder in the Files section of OctoPrint.

#### What did you expect to happen?

The name of the folder would be displayed so I know I'm in that folder.

#### What happened instead?

No folder name was displayed.

#### Branch & Commit or Version of OctoPrint

Version: 1.3.0.post1+g1014712 (master branch

#### Printer model & used firmware incl. version

Fabrikator Mini V1.5

#### Browser and Version of Browser, Operating System running Browser

Chrome Version 55.0.2883.95 (64-bit)

#### Link to octoprint.log

https://github.com/CyberHugger/helloWorld/blob/master/octoprint.log

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s) showing the problem:

![screen shot 2017-01-14 at 7 47 33 pm](https://cloud.githubusercontent.com/assets/25128317/21960098/6188cef6-da92-11e6-9f23-b0da7a23e7ab.png)

**Comment by foosel** [comment]
Implemented on `maintenance`, soon to be merged to `devel` and to be released with 1.3.2

![image](https://cloud.githubusercontent.com/assets/83657/23306837/7c2ad6b8-faa5-11e6-830e-d10513f8af5b.png)
