### ISSUE TITLE
camera on fullscreen in web [Request]

### ISSUE THREAD

**Issue by userosos** [foosel/OctoPrint#1714]
I want see connected an camera in octoprint in web page in fullscreen.

**Comment by BillyBlaze** [comment]
You can install this plugin: https://github.com/BillyBlaze/OctoPrint-FullScreen

**Comment by BillyBlaze** [comment]
Normally they should be listed on http://plugins.octoprint.org/

I still haven't got the time to register that plugin, so you can install it manually for now.
However I am now registering it to the plugin repository, so expect it there also soon 👍

**Comment by BillyBlaze** [comment]
I am closing this issue since the request has been met. If you have any feature requests, please create them in the fullscreen github issue tracker.
