### ISSUE TITLE
[Brainstorming] Some suggestions for language in source files

### ISSUE THREAD

**Issue by seigel** [foosel/OctoPrint#1735]
#### What were you doing?

Reading the instructions in a couple of files.  Nothing serious, just some tweaks.

#### Branch & Commit or Version of OctoPrint
master

#### Printer model & used firmware incl. version
N/A
#### Browser and Version of Browser, Operating System running Browser
N/A
#### Link to octoprint.log
N/A
#### Link to contents of terminal tab or serial.log
N/A

#### Link to contents of Javascript console in the browser
N/A

#### Screenshot(s) showing the problem:
N/A
I have read the FAQ.
YES

[changes.txt](https://github.com/foosel/OctoPrint/files/734525/changes.txt)

**Comment by foosel** [comment]
Sorry, that somehow got buried. I like those changes! Why didn't you create a PR instead of a Brainstorming ticket? And do you maybe still want to do that? :)

**Comment by foosel** [comment]
Applied them in the above commit. Available on `maintenance`, soon `devel`, will be part of 1.3.2.

**Comment by seigel** [comment]
Thanks sorry, I missed your response.

**Comment by foosel** [comment]
1.3.2 was just released.
