### ISSUE TITLE
[Request] Suppress update notifications when logged in as non-admin user

### ISSUE THREAD

**Issue by pelrun** [foosel/OctoPrint#1739]
Anyone logged into a non-admin account still sees all the update notifications even though they're completely unable to actually perform the update. So it's unnecessary to actually show them those notifications. They also can't tell octoprint to ignore the update, so they're forced to see the notification every time they log in until the admin user comes along and deals with it.

I'm using octoprint to manage multiple printers in my hackerspace, so everyone else except for myself gets the non-admin guest account, because we don't really need full access control but want to restrict configuration to the person maintaining them. But everyone gets spammed with update notifications, even though I'm the only one who can actually deal with them.

**Comment by foosel** [comment]
I added an option to the Software Update Plugin Settings to allow disabling notifications for users that are not admins (checked by default, to keep current behaviour for people who rely on it):

![image](https://cloud.githubusercontent.com/assets/83657/24455275/3b89c0ca-148f-11e7-930d-efd9ebb86ca1.png)

I also added the "Ignore" button to the notification and a hint to seek an admin for updating:

![image](https://cloud.githubusercontent.com/assets/83657/24455198/f9b7fe78-148e-11e7-9388-2f922749fc07.png)

The notification will also now auto-hide on log-out, and the browser will remember the ignore state on a per-user base (that way a user ignoring the notification, then logging out and handing over control to an admin will still have the notification show up for the admin).

Pushed to `maintenance`, soon `devel`, will be released with 1.3.3.
