### ISSUE TITLE
[REQUEST] Sort plugins by newest/most recently updated?

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#1747]
For your consideration: would it be possible to have the "Get more" plugins list page sorted by most recently updated/newest plugins on top? I think this would be the quickest way for me to see if there have been any new contributions to the repository?

Thanks!

**Comment by Pinaute** [comment]
It's already possible.
In the corner, at the top right there is a key.
![installplugins](https://cloud.githubusercontent.com/assets/22305245/22557159/e937869a-e969-11e6-8d30-ea1f9da08c8d.png)

**Comment by Pinaute** [comment]
> plugins list page sorted by most recently updated/newest plugins on top
By default, when you instal octoprint?

**Comment by bolsoncerrado** [comment]
My bad lol
