### ISSUE TITLE
[Request] PWM control fan

### ISSUE THREAD

**Issue by userosos** [foosel/OctoPrint#1753]
I can't control speed of fan in work.
I want change speed of fan in progress.

**Comment by FreshSteve** [comment]
I agree, having a slider to set the desired fan speed (0-100%) then select fan ON or similar would be great.  My fans rarely need to be at 100% power and are quite loud.

**Comment by foosel** [comment]
[Custom controls](http://docs.octoprint.org/en/master/features/custom_controls.html) are your friends :)

**Comment by ntoff** [comment]
Give this a try https://github.com/ntoff/OctoPrint-FanSpeedSlider
