### ISSUE TITLE
Timelapse: No picture "On Z Change"

### ISSUE THREAD

**Issue by ThomasSc** [foosel/OctoPrint#177]
There is only one picture "On Z Change" in Timelapse.

**Comment by ThomasSc** [comment]
The issue is there again.
Timelapse Mode  "On Z Change".
But it is different, because there is no picture in tmp.
If I set "Timelapse post roll", this will be rendered.

The Timelapse Mode  "Timed" works very well.


OctoPrint 1.2.0-dev-854-gfa57f16 (devel branch)

**Comment by foosel** [comment]
Please provide a file to reproduce this with

**Comment by ThomasSc** [comment]
Here is a file.
https://gist.github.com/ThomasSc/8242c46219dc0e5c4f9b#file-kalibri_simpl-gcode

**Comment by ThomasSc** [comment]
It works again with
OctoPrint 1.2.0-dev-862-g3ac2d5d (devel branch)

Thank you very much.

**Comment by foosel** [comment]
Ah, that one was tracked in #909 and I forgot about this one due to being down sick last week, sorry.
