### ISSUE TITLE
[Request] Login Screen - Internet Facing

### ISSUE THREAD

**Issue by FLDataTeK** [foosel/OctoPrint#1772]
How about an option to have a login screen option for internet facing installs? 

I noticed today that even with out logging in to the OctoPrint I can download the files that are sitting on my OctoPrint. Some of these files are custom designs for our company and do not need to be accessible by anyone not logged in. Also the camera is accessible from non logged in users as well. 

Having a login screen with authentication would reduce the attack surface of the OctoPrint on the internet as well as stopping random people from chewing up your bandwidth watching your printer print (can be up to a 5mbps stream). 

I know OctoPrint was designed to be internally used but its wonderful to use it from the internet also but we just need more ways to control who and what can be seen from unauthenticated users.

**Comment by foosel** [comment]
> we just need more ways to control who and what can be seen from unauthenticated users.

That's what #1110 is all about and @Salandora is already working on that :+1:. I'm therefore closing this as a duplicate if you don't mind :)

> [webcam is accessible]

That's [not solvable by OctoPrint though](https://github.com/foosel/OctoPrint/wiki/FAQ#why-is-there-no-access-control-for-the-webcam-in-octoprint). It will require support by external tooling and is hence outside the scope of this project (and for OctoPi it's in the pipeline, see the discussion in guysoft/OctoPi#292).

> [OctoPrint accessible from the internet]

Please take extra measurements to protect your instance. Put rate limiting into a reverse proxy that is NOT a Pi running OctoPrint or someone can DDoS the machine running your printer. Put additional access control in front. Ideally use a VPN. Opening a port of the pi to the internet is just asking for trouble. Use the telegram plugin for control on the go.
