### ISSUE TITLE
Files don't get analysed after they got moved/copied

### ISSUE THREAD

**Issue by Salandora** [foosel/OctoPrint#1775]
**Problem**

If not already analysed files won't get analysed after they got moved/copied.
This could also be a problem for files in folders.

Steps to produce this bug:
1. Upload a file
2. Before it got analysed move it somewhere else
3. Files does not get analysed now.

**Comment by foosel** [comment]
And solved on `maintenance`, to be merged to devel ASAP and to be released with 1.3.2
