### ISSUE TITLE
[Request] Confirm delete of Timelapse video

### ISSUE THREAD

**Issue by scorpydude** [foosel/OctoPrint#1798]
For the love of all that is right and just, can we please have a confirmation of delete of a timelapse? I've lost many a great timelapse when trying to view to a dodgy mouse and few too many beers and quick clicks! (Or a recycle bin or something)

**Comment by foosel** [comment]
Just realized this is a duplicate of #748. Also see discussion in #1807 though, we are nearing a solution.
