### ISSUE TITLE
Tab panel in Settings scrolls to top when clicking tabs on low resolution displays.

### ISSUE THREAD

**Issue by kantlivelong** [foosel/OctoPrint#1812]
#### What were you doing?

1. Set resolution to 1280x800
2. Open Settings
3. Scroll down and click Announcements

#### What did you expect to happen?
Announcements is displayed and the left menu stays in place.

#### What happened instead?
Announcments is displayed and the left menu scrolls to top.

#### Branch & Commit or Version of OctoPrint

1.3.1 (master)

#### Printer model & used firmware incl. version

N/A

#### Browser and Version of Browser, Operating System running Browser

N/A

#### Link to octoprint.log

http://paste.debian.net/918773/

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s) showing the problem:

https://s1.webmshare.com/QYXaJ.webm

I have read the FAQ.

**Comment by foosel** [comment]
Urks. Stuff like that can be yucky. I'll take a look.

**Comment by foosel** [comment]
Perfect, just merged your PR (also backported it to `maintenance`), will be released with 1.3.2
