### ISSUE TITLE
[Task] Remove items marked as deprecated and to be removed with 1.4.0

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#1852]
### Events

* [x] ``gcode`` type for ``Upload`` event
* [x] ``file`` property in payload for ``MetadataAnalysisStarted``, ``MetadataAnalysisFinished``, ``FileSelected``
* [x] ``filename`` property in payload for ``FileSelected``

**Comment by eyal0** [comment]
The event MetadataAnalysisFinished is marked for deprecation.  Currently, it is used to update the file list.  What will update the file list after this is deprecated?

Thanks!

**Comment by foosel** [comment]
That's an indentation error in the documentation. The event will stay, the removal notice applies to the deprecated payload field.

**Comment by foosel** [comment]
Cleaned up.
