### ISSUE TITLE
[Documentation] current installation guide on raspbian seems broken ?

### ISSUE THREAD

**Issue by gege2b** [foosel/OctoPrint#1856]
Hi all,

I face a problem when installing OP on a brand new rPI3 today
Not an actual OctoPrint bug, it's on doc side, I know it's a Wiki and I can edit it myself, but as I'm not pretty sure of what's happens, I think that opening a ticket is the best solution :) 

#### What were you doing?

I followed strictly the steps indicated on the [wiki](https://github.com/foosel/OctoPrint/wiki/Setup-on-a-Raspberry-Pi-running-Raspbian), but it seems that the command  :  

```git clone --depth 1 https://github.com/foosel/OctoPrint.git```

avoids me to switch to another branch (say devel),  I get the error : 

```
$ git checkout devel
error: pathspec 'devel' did not match any file(s) known to git.
```

using the git clone command without  --depth solves the problem.
Because I don't really know why the --depth parameter is used, I don't want to just edit the wiki and make a mistake :) 

And as this isn't "code" related, all other informations are irrelevant

I have read the FAQ.

**Comment by foosel** [comment]
The upside of having a wiki in place: everyone can fix errors. The downside of having a wiki in place: everyone can introduce errors. The latter was the case here. ``--depth 1`` does not make any sense here and break things. It has been removed again. Thanks for the heads-up!
