### ISSUE TITLE
Extra (and possibly unneeded most of the time) content loaded when initially loading Octoprint's UI in a browser

### ISSUE THREAD

**Issue by pyjamasam** [foosel/OctoPrint#1858]
#### What were you doing?
Loading the octoprint homepage

#### What did you expect to happen and what happened instead?
I expected the resources needed to load octoprint and make it functional to be loaded.

What I see is that additional resources are loaded.  Specifically resources that are part of the announcements (mostly images from the plugins channel).
And one of those images is 2.4MB.

This happens every fresh load of the octoprint interface.

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.2 (master branch)

#### Operating System running OctoPrint

Raspberry PI 2B

Linux octoprint 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION="7 (wheezy)"

#### Printer model & used firmware incl. version

Micromake D1, Azteeg X5 Mini 1, latest edge of smoothieware

#### Browser and Version of Browser, Operating System running Browser

macOS Chrome 57.0.2987.133 (64-bit)

#### Link to octoprint.log

I don't think I need to include this as its a UI bug

#### Link to contents of terminal tab or serial.log

Same as above.  Not needed for a UI bug

#### Link to contents of Javascript console in the browser

https://gist.github.com/pyjamasam/54dc29360adabfc4cd0f466317f2ebed

#### Screenshot(s) or video(s) showing the problem:

http://www.chrisandtennille.com/pictures/Screen%20Shot%202017-04-08%20at%2019.53.18.png

I have read the FAQ.

My guess is when channel data is loaded and the html is put into the corresponding dom objects the browser is loading the images (as it should since the dom has been updated).

But the announcements are hidden unless I go look at them.  I don't think it should be loading all the related media every time.

**Comment by foosel** [comment]
Good point 👍 With the above commit images from the announcements are now lazy loading. Already on `maintenance`, soon on `devel` and to be released with 1.3.3.
