### ISSUE TITLE
[Request] TimeLapse API Provide Current Status "Timelapse on/off/type" for apps

### ISSUE THREAD

**Issue by xFoxBox** [foosel/OctoPrint#1861]
#### What were you doing?

Using printoid app on android

#### What did you expect to happen and what happened instead?

Wanted to see if my timelapse was working, and what type of timelapse was being taken. But since there is no current way for "REST API's" to show if timelapses are happening or not, the app wasn't able to tell me if the printer was actually snapping pics/vid--

#### Branch & Commit or Version of OctoPrint
Octoprint ver 1.3.2 Master Branch

#### Operating System running OctoPrint

Device running Octoprint: Raspberry Pi 3, flashed directly with octoprint software

#### Printer model & used firmware incl. version

Marlin Firmware, i3 clone, Beta release "RCBugFix" from a few weeks ago

#### Browser and Version of Browser, Operating System running Browser

Arch Linux 4.10.5-1-ARCH
Firefox 52.0.1 64bit

Android 6.0.1
Printoid (android app)

#### Link to octoprint.log

https://pastebin.com/XheA3FaD

#### Link to contents of terminal tab or serial.log

[On gist.github.com or pastebin.com. If applicable, always include if unsure or
reporting any kind of communication issues between OctoPrint and your printer.
Never truncate.

serial.log is usually not written due to performance reasons and must be
enabled explicitly. Provide at the very least the FULL contents of your
terminal tab at the time of the bug occurrence, even if you do not have
a serial.log.]
No bug occurence, just a "status of timelapse" API feature request please to support our app developers! (and users)

#### Link to contents of Javascript console in the browser

[On gist.github.com or pastebin.com or alternatively a screenshot. If applicable -
always include if unsure or reporting UI issues.]
No issues, just feature request

#### Screenshot(s) or video(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]
No problems, just feature request!

I have read the FAQ. ✓

Please! Thank you!

**Comment by foosel** [comment]
Anything that is possible from the OctoPrint UI is also possible via the available API - this is what OctoPrint stock UI uses. 

This includes information about [the current timelapse configuration](http://docs.octoprint.org/en/master/api/timelapse.html) and - via [push messages](http://docs.octoprint.org/en/master/api/push.html) on the [SockJS powered websocket](http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html) and listening to the [events triggered by the timelapse component](http://docs.octoprint.org/en/master/events/index.html#timelapses) - also if snapshots are being captured or not. There are also client implementations for this websocket based push API in [python](https://github.com/foosel/OctoPrint/blob/maintenance/src/octoprint_client/__init__.py#L280-L354) and [javascript](https://github.com/foosel/OctoPrint/blob/maintenance/src/octoprint/static/js/app/client/socket.js) that can be a reference and help in getting things set up. 

I'm happy to assist the author of Printoid with getting this info into the app, but there's nothing that needs to be done in OctoPrint's code here. Everything needed is already there, apart from one bit also fully documented, and that bit is the SockJS protocol for which external documentation and reference implementations are provided.
