### ISSUE TITLE
File drop area too small

### ISSUE THREAD

**Issue by imitation** [foosel/OctoPrint#187]
With the new darkened drag-and-drop-upload screen (as of b048cc390b5f000771f189d0a2ab577a69ce409a ) and SD disabled, only the very center spot is an active upload area, the rest of the site does nothing when the file is dropped onto it. This means a lot of shuffling windows around each time, since that center spot is usually where the Slic3r and file browser windows sit.
Suggested solution: Make the whole screen an active drop area or disable the small drop area altogether when SD is disabled. For SD, split the whole screen in half and make the complete left side an active area for local uploads and the right side active for SD uploads.

**Comment by jonaslorander** [comment]
+1 from me! It is very annoying...!

**Comment by foosel** [comment]
I always find it interesting how annoying something can be without anyone bothering to try their hand at a pull request ;)

**Comment by nophead** [comment]
The box is close to 1/3 of the width of my 1280 screen and I can drop anywhere in that box. How high res does your screen have to be before it is too small to hit?

**Comment by szafran81** [comment]
If you want to know then take a screenshot and in some graphics editor make
the canvas (do not scale the screenshot since the drop box doesn't scale)
2560×1440 (WQHD) or 2560×1600 (WQXGA) or to be more current 4096×2304 (4K).


2015-03-03 16:20 GMT+01:00 Chris <notifications@github.com>:

**Comment by foosel** [comment]
=> `devel`

**Comment by jonaslorander** [comment]
The Case for me on my 1080p-resolution is that when i open Explorer it positions right in the middle of my screen over the  drop area. Förringa me to first love the Explorer Windows before draging the file.

**Comment by foosel** [comment]
![image](https://cloud.githubusercontent.com/assets/83657/6468416/2e0d8b16-c1d5-11e4-8f14-299135e0c9ef.png)

Can we now please stop beating a dead horse? Thanks ;)

**Comment by jonaslorander** [comment]
I just noticed it. Looks awesome!
