### ISSUE TITLE
[Request] simple calculations in config.yaml

### ISSUE THREAD

**Issue by rob-miller** [foosel/OctoPrint#1883]
I would like to set up a custom control to be able to specify extruder flow rate in mm/sec, but the G1 g code F value is in mm/min.  It would be nice to be able to do something like:

    - name: e0 feed 
      type: parametric_command
      # G1 F is mm/min but we want mm/sec
      commands:
        - G91
        - G1 E%(dist)s F%(rate*60)s
        - G90
      input:
        - default: 10
          name: (1-30mm)
          parameter: dist
        - default: 100
          name: (1-80mm/s)
          parameter: rate

Sorry if there is a way to do this already but could not seem to work it out?
Thanks

**Comment by foosel** [comment]
I think getting this to work in a *backwards compatible* manner would be a nightmare. Currently parametric commands use simple python format strings. For anything beyond that I'd strongly suggest looking into [a custom parameterized GCODE scripts](http://docs.octoprint.org/en/master/features/custom_controls.html#sec-features-custom-controls-examples-gcode-script) or [the `getAdditionalControls` view model callback](http://docs.octoprint.org/en/master/plugins/viewmodels.html#callbacks) and implementing [`javascript` custom controls](http://docs.octoprint.org/en/master/features/custom_controls.html#controls) via a plugin instead, full fledged calculation support would simply add way too much complexity in the code for a way too limited gain.
