### ISSUE TITLE
Delete files with ()

### ISSUE THREAD

**Issue by catohagen** [foosel/OctoPrint#19]
In the filelist, PrinterWebUi cant delete files with (), atleast if the upload directory in config.ini is a mounted share from a remote source (/mnt/router_usb)

It loads files with () fine

feel free to mess around with my PrinterWebUi at http://mosnet.mine.nu:5000/ (if its online, but should be)

**Comment by foosel** [comment]
Should no longer be an issue since the file management was completely revamped with 1.2.x
