### ISSUE TITLE
1.3.3rc1: "Save as default" on timelapse config not disabled alongside everything else when non operational

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#1918]
Originally reported by @ntoff in #1914 ([see this comment](https://github.com/foosel/OctoPrint/issues/1914#issuecomment-301292361)).

#### Expected

"Save as default" is disabled when all other settings are disabled as well due to the printer being offline.

#### Actual

It is not disabled and can be toggled. Doesn't do anything though.

![image](https://cloud.githubusercontent.com/assets/83657/26055261/627757d2-3970-11e7-92ca-ea497a173354.png)

#### Solution

Fix knockout data bindings.

#### Sidenote

It would probably make sense to allow timelapse configuration when the printer is not operational...

**Comment by jkyoutsey** [comment]
I can configure timelapse, but I cannot check the "Save as Default" button.  I'm on 1.3.10

**Comment by foosel** [comment]
@jkyoutsey can you please open a *full* new ticket for that? This one is nearly two years old and there have since been so many changes to OctoPrint that it's probably unrelated.

**Comment by Gunnl** [comment]
@jkyoutsey , have you opened a new ticket? I am having same issue ...

**Comment by jordanwjolly** [comment]
@jkyoutsey  I having the same issue
