### ISSUE TITLE
Manual placement of .profile file in Cura slicingProfiles folder results in blank Profile List in Cura Engine Settings.  [Resolved in 1.3.3/1.3.4?]

### ISSUE THREAD

**Issue by joshwills** [foosel/OctoPrint#1949]
#### What were you doing?

**APPARENTLY RESOLVED, POSTING FOR INFORMATION**

Manually changing Cura profiles in /home/pi/.octoprint/slicingProfiles/cura .  Issue occurs when any new file is placed in this directory - either copied from an existing profile (via cp), or transferred from a different OctoPrint install on a different system.

1. Connect to OctoPrint hosting system via SSH, FTP or similar
2. cd to ~/.octoprint/slicingProfiles/cura
3. Create a new .profile file by either copying it ("cp default.profile default-faster.profile" or similar), or transferring a new .profile in.

#### What did you expect to happen?

New profile to appear in the CuraEngine Settings dialog Profile list.

#### What happened instead?

CuraEngine Settings dialog Profile list is completely empty.

Clicking on the Slice button on a .stl file in the Files sidebar panel (then closing the Slicing dialog) will cause the CuraEngine Settings dialog Profile list to be populated next time it's navigated to, but only until the next time the Client is refreshed; Client Refresh and/or Server Restart both return CuraEngine Profile list to blank state.

Importing a new profile seems to fully resolve this, including showing the manually created profile(s) in the Profile list.

A separate issue I need to test - it might not be possible to Import Profile when in Safe Mode, as I was only getting 401 errors.

#### Did the same happen when running OctoPrint in safe mode?

Yes, same behavior in safe mode.

#### Branch & Commit or Version of OctoPrint

Current testing was on 1.3.2 master branch, though also seen on a bit older, and 1.3.2 rc/devel branch.

To be thorough I then tested in 1.3.4 rc/devel on Raspbian Jessie, where the issue now seems to be resolved.

#### Operating System running OctoPrint

OctoPi 0.13.0 with 1.3.2 master branch OctoPrint; 1.3.2 rc/devel on Raspbian Jessie.  Both are on Raspberry Pi 3 units.

#### Printer model & used firmware incl. version

Issue seen when not even connected, so not applicable (probably...).

#### Browser and Version of Browser, Operating System running Browser

Chrome 57.0.2987.133 on Windows 7 for this round of testing, though also seen on Safari/Mac OS X, Firefox and Windows 7, and Chrome in Linux Mint.

#### Link to octoprint.log

Nothing relevant in octoprint.log, even when running in --debug.  Can still provide if requested.

#### Link to contents of terminal tab or serial.log

Issue can be caused without being connected to a printer.

#### Link to contents of Javascript console in the browser

No errors in Chrome Javascript console, even when running in --debug.

#### Screenshot(s)/video(s) showing the problem:

![2017-06-02 08_04_14- octoprint](https://cloud.githubusercontent.com/assets/13168739/26725023/619ed47c-476a-11e7-9ba5-ab8ac5f1c132.png)

I have read the FAQ.

**Comment by foosel** [comment]
After a thorough discussion on IRC @joshwills and me have determined that the observed bug was indeed fixed in 0161d915d642ad60fa8dfb26a74f60d3fdf3eb0f, specifically through [this addition](https://github.com/foosel/OctoPrint/commit/0161d915d642ad60fa8dfb26a74f60d3fdf3eb0f#diff-9898203ccdd756fc436941ffb99dfcb6R275).

So this actually *was* fixed in 1.3.3/1.3.4 😄
