### ISSUE TITLE
[Request] Please add option to rename files

### ISSUE THREAD

**Issue by AndKe** [foosel/OctoPrint#1965]
My OctoPrint contain many .gcode files, different files have different name (usually based on Slic3r output).
It would be very useful to be able to rename them in OctoPrint:
partA_.gcode
to
partA_filament_x.gcode

or 
PartB.gcode
PartB.ver1.gcode

that would easy allow multiple versions, or important notes, like which filament they are generated for.

**Comment by foosel** [comment]
Already possible with the [file manager plugin](http://plugins.octoprint.org/plugins/filemanager/).
