### ISSUE TITLE
[Request] Auto send snapshots to emial or something

### ISSUE THREAD

**Issue by znelson710** [foosel/OctoPrint#1966]
I use the live stream to check in on prints but if I am busy through the day I'll forget to check in. I have had prints fail hat I could have stopped had I not gone 4 hours without checking. 

It would be super handy if there was a setting that I could specify how often to send a picture to my email. That way if I do forget to manually check on the print I'll at least have a photo sent to me automatically.

**Comment by foosel** [comment]
There are a number of [plugins](http://plugins.octoprint.org/) available for this exact kind of stuff, including an email plugin. I suggest to take a look at those.
