### ISSUE TITLE
[Request] 3D, rotatable slicer like view in GCODE viewer

### ISSUE THREAD

**Issue by pentar25** [foosel/OctoPrint#1972]
Self explanatory. Would be very useful. The ability to rotate the live Gcode view as it prints, and view from different angles.

Thanks

**Comment by ntoff** [comment]
https://github.com/foosel/OctoPrint/issues/267 goes into why it's not implemented

**Comment by foosel** [comment]
And this is actually a duplicate of that ticket, so closing this. Thanks @ntoff for looking up the ticket!
