### ISSUE TITLE
Deletion of read only timelapse fails silently

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#1975]
#### What were you doing?

Trying to break things as usual. I appear to be good at that.

_Ideally provide exact steps to follow in order to reproduce your problem:_

1. Navigate to timelapse directory and set one or more timelapse videos to read only (via SSH, etc)
2. Try to delete one of the timelapses by pressing the garbage can icon.

No error message is displayed notifying users the deletion failed (apart from a java console error which wouldn't normally be visible)

Now try it again with the mass delete feature:

1. (as above)
2. Tick the box next to the timelapse you've set to read only and press "Delete selected"

This time an error message is displayed (although it doesn't say specifically *why* it failed).

![image](https://user-images.githubusercontent.com/9030085/27294423-e2f5f078-555c-11e7-8071-f0f279c08c34.png)

Works on any timelapse file you may wish to "protect" by setting it to read only.

#### What did you expect to happen?

Some sort of error message along the lines of the regular error messages that pop up during failure to capture timelapses, failure to acquire timelapse images, etc

#### What happened instead?

Nothing when using the old method of pressing the garbage can icon.

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.4.0.dev419+g24dc120 (devel branch)

#### Operating System running OctoPrint

windows 7 x64

#### Printer model & used firmware incl. version

none / virtual

#### Browser and Version of Browser, Operating System running Browser

google chrome
edit: Oops forgot the version: Version 58.0.3029.110 (64-bit)

#### Link to octoprint.log

pretty sure we know why it can't delete the file :)

#### Link to contents of terminal tab or serial.log

not a serial issue

#### Link to contents of Javascript console in the browser

![image](https://user-images.githubusercontent.com/9030085/27294516-26a735c0-555d-11e7-8fac-9020bb2fcee5.png)

#### Screenshot(s)/video(s) showing the problem:

see above

#### Additional Thoughts:

I'm aware that this would be a severely remote chance of a user going and setting a timelapse file as read only but still, isn't it worth putting up a big red "Failed to delete" box just to let the user know OctoPrint *tried* to delete it, and it didn't just silently fail?

I have read the FAQ.

**Comment by ntoff** [comment]
possible fix:

\octoprint\src\octoprint\static\js\app\viewmodelstimelapse.js - line 226

	self.removeFile = function(filename) {
        var perform = function() {
            OctoPrint.timelapse.delete(filename)
                .done(function() {
                    self.markedForFileDeletion.remove(filename);
                    self.requestData()
                })
                .fail(function() {
                        var html = "<p>" + gettext("Failed to remove timelapse file");
                        html += pnotifyAdditionalInfo('File: <pre style="overflow: auto">' + filename + '</pre>');
                        new PNotify({
                            title: gettext("Could not remove timelapse"),
                            text: html,
                            type: "error",
                            hide: false
                            });
                    });
        };

        showConfirmationDialog(_.sprintf(gettext("You are about to delete timelapse file \"%(name)s\"."), {name: filename}),
                               perform)
    };

though this doesn't show *why* it failed, is it possible to get the reason easily?

**Comment by foosel** [comment]
Thanks for the heads-up, I expanded a bit on your suggestion, it now will show a reason as well:

![image](https://user-images.githubusercontent.com/83657/27588914-05596eae-5b4a-11e7-8fc8-99a1f9ec46c1.png)

![image](https://user-images.githubusercontent.com/83657/27589061-5a6d3f1a-5b4a-11e7-9142-33fe9dd53128.png)

Fixed in `maintenance`, soon `devel` and to be released with 1.3.5.

**Comment by ScottyMakesStuff** [comment]
Hi Foosal,
Firstly wanted to say a big thankyou for making Octoprint so awesome!!

I've had a number of timelapses fail over the last few months. Thanks to your update the latest one gave me the message that the tmp file was deleted. My problem is that the previous tmp files weren't deleted and have filled up my 16GB sdcard. I've had a look over SSH and can't find where they're located?

**Comment by foosel** [comment]
Timelapse snapshot files are usually stored under `~/.octoprint/timelapse/tmp` or whatever else you have configured under Settings > Folders > Timelapse Temp Folder. But you should also be able to delete them by expanding "Unrendered Timelapses" here (as long as you have the necessary permissions of course):

![image](https://user-images.githubusercontent.com/83657/28451600-6b16bfe2-6dee-11e7-9036-1c873eec817f.png)

**Comment by ScottyMakesStuff** [comment]
Thanks Foosel, I missed that link. 
Just cleared 11GB of unrendered timelapses and I'm back in business :)
