### ISSUE TITLE
[Request]: Slider to control fan speed 

### ISSUE THREAD

**Issue by bipsendk** [foosel/OctoPrint#2002]
On the Control pane of the web interface, it is currently possible to turn the extruder fan on/off

It would be desirable, if there also was a slider 0-100% to control the fan speed when switching the fan on.

**Comment by fiveangle** [comment]
http://docs.octoprint.org/en/master/features/custom_controls.html#custom-controls

**Comment by ntoff** [comment]
Give this a test https://github.com/ntoff/OctoPrint-FanSpeedSlider

**Comment by kantlivelong** [comment]
Closing as a plugin exists.
