### ISSUE TITLE
[Request] Dark mode

### ISSUE THREAD

**Issue by HarlemSquirrel** [foosel/OctoPrint#2023]
I would love a dark mode option for the appearance. I'm happy to build the feature and open a PR if the project is open to it. I'm thinking something like the new YouTube dark mode with light text on a dark background.

**Comment by jneilliii** [comment]
Go into settings and change the theme to Black...

![image](https://user-images.githubusercontent.com/5249455/28496829-320fcdf0-6f43-11e7-83ea-969eaeb9a813.png)

**Comment by nophead** [comment]
That setting only changes the title bar for me.

**Comment by HarlemSquirrel** [comment]
I'm running version 1.3.4 and that setting only changes the title bar for me as well.

**Comment by ntoff** [comment]
http://plugins.octoprint.org/plugins/cyborgtheme/

**Comment by jneilliii** [comment]
Oh yeah, forgot I had installed that. Install the cyborg theme plugin and then set the appearance setting to black to match.

**Comment by HarlemSquirrel** [comment]
That works, thanks!
