### ISSUE TITLE
Can't edit or add new printer settings

### ISSUE THREAD

**Issue by djarami** [foosel/OctoPrint#2037]
#### What were you doing?
I updated some settings in the printer config and I changed the origin to 0 instead of center.  That caused some other error later when I went to print saying that things were out of bounds.  So I tried to go back and change it, the edit pencil is greyed out.  

I tried adding a new printer, but the confirm button keeps circling even when I haven't clicked on it.

I tried restarting octoprint, nothing.
I tried rebooting and still not able to edit the printer config.

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.5rc1 (rc/maintenance branch)

#### Printer model & used firmware incl. version

ANet 8 - Skynet3D

#### Browser and Version of Browser, Operating System running Browser

Chrome, Mac OS Sierra 10.12.5

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

*[edited by @foosel: Removed template boilerplate to make more obvious what information is missing]*

**Comment by foosel** [comment]
Could you please provide _all_ requested information? Your ticket is missing a lot of what is needed to further look into this. Thanks.

**Comment by djarami** [comment]
That's a lot of information.  I tried to get as much as I could. I watched your video and got excited about your new RC.  I'm new to octoprint and love it. I'm not new to development so I understand why you want all that.  I just wanted to let you know something weird is going with the printer settings. 

One thing I can't seem to find is how to back out the RC and go back to the general release.  I'm very excited about the new function.  

I also noticed that when I out it safe mode, things work fine.   I don't know if that means one of the plugins are affecting things or if there is something else in the system. 

Btw - enjoy your upcoming vacation. 

I look forward to learning more about your system and being able to collaborate more.

**Comment by djarami** [comment]
I just updated to RC2, same problem.  I was able to edit once and doesn't let you edit again even when you restart octoprint.  It works fine under safe mode.  I'll take a look at the JS Console log in a little bit - that could have something.

**Comment by foosel** [comment]
If it works fine under safe mode, it's one of your third party plugins that's causing the issues. Safe mode disables all plugins that do not come bundled with plugin, so it basically turns your OctoPrint instance into kind of a stock install again while its active.

What plugins do you have installed?

And yes, the JS console might give a hint here. What you are describing sounds like something gets confused in request processing.

**Comment by foosel** [comment]
Anything new here?

**Comment by foosel** [comment]
Closing due to lack of response.
