### ISSUE TITLE
[Request] choose filament slicing

### ISSUE THREAD

**Issue by leobel96** [foosel/OctoPrint#2054]
Hello. Is there a way to choose filament for slicing? I saw that in Settings I can add filaments but this is only for heatbed and nozzle preheating and not also for printing. Should I upload a different printing profile for EVERY filament I use? Thank you

**Comment by Kunsi** [comment]
Slicing is provided by either [https://github.com/OctoPrint/OctoPrint-Slic3r/issues Slic3r plugin] or [https://github.com/OctoPrint/OctoPrint-CuraEngine/issues Cura plugin]. So that request is related to whichever plugin you're using. Please refer to the issue tracker of the corresponding plugin for your request.

**Comment by leobel96** [comment]
@Kunsi The point is that, how you can see in this screen, there isn't a selector for filament. Regardless of the slicer chosen, the screen doesn't change and the selectable items remain that same. So I think it's a limitation of octoprint and not of the slicer.


 ![28966517-f2a62b04-7916-11e7-8127-7d011b3ca828 png](https://user-images.githubusercontent.com/19806799/29094348-50d323f2-7c8d-11e7-8e55-2f610030947f.png)

**Comment by foosel** [comment]
> Is there a way to choose filament for slicing

No, this is simply not part of the (limited) slicing workflow in OctoPrint and also not a priority. Some slicers allow stuff like filament profiles, others don't, so it's not trivial to solve either. The current approach is to define one slicer profile per filament - or to use your desktop slicer and just upload the file to OctoPrint (Cura & Slic3r even support doing this automatically).

For anything more sophisticated than that I suggest to take a look at [e.g. this plugin](http://plugins.octoprint.org/plugins/slicer/)-
