### ISSUE TITLE
[Request] Better Time Estimation

### ISSUE THREAD

**Issue by ComicBit** [foosel/OctoPrint#2068]
I saw that octoprint time estimations aren't that great, can't we make something better? I find Simplify3D to be pretty accurate on times but not perfect. Octoprint seems to don't consider the speed changing and surface printed dimension

**Comment by fiveangle** [comment]
https://groups.google.com/forum/m/#!msg/octoprint/WWpm1FCUkAs/X3HomTM5DgAJ

**Comment by fiveangle** [comment]
Oh, I think Gina goes deep into this in this webcast: https://youtu.be/nCAMjqysBB0?t=44m45s

(Please close this issue if this answered your question)
