### ISSUE TITLE
[Brainstorming] Introducing gcode comments to prevent parsing the whole file

### ISSUE THREAD

**Issue by malnvenshorn** [foosel/OctoPrint#2097]
After uploading a ~30MB gcode file to OctoPrint it took quite some time on my little Raspberry Pi B+ to parse that file. So I thought it would be great to make it unnecessary to parse the whole file. If the information (used filament, estimated print time, dimensions of the model) are present at the beginning of the file the gcode interpreter could use these and stop going further.

**Comment by ntoff** [comment]
and how do you plan on getting that information into the gcode files in the first place? not every slicer puts it there, and the ones that do, don't all put it in the same place, and if you're still crazy enough (i.e. me) to even consider using skeinforge, it puts that info in a separate file along side the gcode file.

**Comment by malnvenshorn** [comment]
I'm talking about OctoPrint specific comments. Using the comments provided by various slicers is not feasible. Not every slicer produces the same comments or put them in the same place, if they create them at all.

Those comments could look like
```
; octoprint_filament_length = 701.9
[...]
```
and could be created by running a script after the slicer has finished. Basically the code already exists  and if the slicer supports post processing scripts (e.g. slic3r) this can be easily integrated into the workflow.

Maybe it is not a feature for everyone, but if OctoPrint doesn't  find those comments it will parse the file as usual. So nothing will change for those people, but it will speed things up a lot for people like me.

**Comment by ntoff** [comment]
ok, I guess that could work, octoprint hasn't bothered parsing any of my gcode for time estimation in forever, I never get print estimates anymore (until I hit print) so if there was a way to get time estimates out of slic3r that *don't* involve me uploading to gcode.ws then I'm all for that.

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by Andrei-Pozolotin** [comment]
another relevant performance issue: 
* why load 30MB gcode into client (and crash the browser)? 
* why not stream on demand (+/- 100 lines in context)?

**Comment by jneilliii** [comment]
This is actually possible via a plugin.  You could use the example on the [octoprint-filemanager-preprocessor}(http://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-filemanager-preprocessor) documentation page and just take out the check for ending in "_strip" and process all gcode files on upload.

**Comment by jneilliii** [comment]
Not sure if completely possible to set the meta data of the analyzed gcode (ie estimated time, etc.) but there are available plugin hooks to preprocess the uploaded files.  Documentation can be found over on the [octoprint-filemanager-preprocessor](http://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-filemanager-preprocessor) section.

**Comment by malnvenshorn** [comment]
@jneilliii Good thought, but how do you prevent that the file is nevertheless added to the analysis queue?

**Comment by malnvenshorn** [comment]
At the moment I always have to replace the _gcodeInterpreter.py_. It would be great if I could provide the metadata via plugin.

**Comment by malnvenshorn** [comment]
Made a plugin, therefore closed.
