### ISSUE TITLE
[Request] Change the order of tabs

### ISSUE THREAD

**Issue by Boogy62** [foosel/OctoPrint#2106]
Hi ! Is there a way to change the order of tabs (Temperature, Control...) ? When many plugins are installed, main tabs are hidden...

Thanks

**Comment by ntoff** [comment]
This is a bug tracker, not a support line, in future please use the google + group https://plus.google.com/communities/102771308349328485741 or the mailing list https://groups.google.com/forum/#!forum/octoprint for help / support.

There is no GUI way to alter the tab order, although you can edit config.yaml to reorder the tabs. http://docs.octoprint.org/en/master/configuration/config_yaml.html#appearance

**Comment by Boogy62** [comment]
Thanks, I didn't know where was the right place to post.

**Comment by ntoff** [comment]
No problem, I hope I didn't come across as being angry or anything, did that configuration documentation answer your question sufficiently? Do you need help figuring out how to find the names of the tabs?

**Comment by Boogy62** [comment]
No it's okay I found everything easily.

Thanks

2017-09-03 9:28 GMT+02:00 ntoff <notifications@github.com>:

**Comment by foosel** [comment]
Closing since this seems to have been solved.

**Comment by jneilliii** [comment]
New improved GUI way via plugin.

https://github.com/jneilliii/OctoPrint-TabOrder
