### ISSUE TITLE
[request] multiple printer/instances on windows

### ISSUE THREAD

**Issue by fraschizzato** [foosel/OctoPrint#2112]
I've seen that in Linux environment is possible to have multiple octoprint instances, how to get the same on Windows?

**Comment by foosel** [comment]
This is a bug and feature request tracker, not a support forum ;)

It works the same way - start a second instance with `--basedir` pointing to another base directory location for your second instance and `--port` setting a different port than the default `5000`. E.g.

    octoprint serve --basedir "C:\Users\YourUsername\AppData\Roaming\OctoPrint2" --port 5001

or

    octoprint serve --basedir "%APPDATA%\OctoPrint2" --port 5001

then access the second instance by connecting to `http://<yourIP>:5001` in your browser.
