### ISSUE TITLE
[Request] Possible workaround for the SerialException problem in the raspberry pi

### ISSUE THREAD

**Issue by maor1993** [foosel/OctoPrint#2125]
Hey, After a bit of research I might have found a workaround for this.

# Symptoms:
This was discovered using  `dmesg` , after a certain period of time, the usb hub on the raspberry pi has an internal issue that forces it to reset, causing all of the usb devices to get disconnected and reattempt arbitration.

# Workaround:
adding dwc_otg.speed=1 to cmdline.txt force the pi to work in 1.1 usb mode.

 this will slow down the ports, and might even disable the ability to connect multiple devices, but for the last couple of hours of printing I was getting no problems.

The usb hub issue is obviously an indicator of a bigger problem (i.e. as mentioned - EMI, PSU stability or others) but I can't seem to find mine. For now, this workaround works for me.

Workaround found here:

https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=8010&start=125

I think this should be added to the FAQ, at least to save people a bit of time trying to get octopi
working fast.

**Comment by foosel** [comment]
The FAQ is part of the Wiki, so anyone with a Github account can actually add information to it :) But I added it for you. Thanks for finding this!
