### ISSUE TITLE
[request] Offset parameters

### ISSUE THREAD

**Issue by johnryanlee** [foosel/OctoPrint#2128]
#### What were you doing?

Printing

#### What did you expect to happen?

Print to occur on bed

#### What happened instead?

Print runs off bed

#### Did the same happen when running OctoPrint in safe mode?

Don't think this is relevant

#### Branch & Commit or Version of OctoPrint

OctoPi 0.14 (downloaded on Saturday)

#### Operating System running OctoPrint

OctoPi 0.14 (downloaded on Saturday)

#### Printer model & used firmware incl. version

Geeetech Prusa I3 W DIY (GT2560)
Marlin 1.1.5

#### Browser and Version of Browser, Operating System running Browser

NA

#### Link to octoprint.log

Don't think this is necessary

#### Link to contents of terminal tab or serial.log

Don't think this is necessary

#### Link to contents of Javascript console in the browser

Don't think this is necessary

#### Screenshot(s)/video(s) showing the problem:

I think it's obvious enough - imagine, printer prints on an air bed, it ain't gonna work... nuf said

**Comment by ntoff** [comment]
First of all, the logs are requested for a reason (please include them), and also please enable the serial log and post that so we can see exactly what is being sent to your printer.

>I think it's obvious enough - imagine, printer prints on an air bed, it ain't gonna work... nuf said

What are you even talking about? OctoPrint sends gcode to your printer, if your slicer isn't producing the correct gcode then that's not OctoPrint's fault. If your printer's firmware isn't set up correctly, OctoPrint isn't to blame for that either.

Please don't be so arrogant in your posts, if you think there really is a bug, please include all the information that is asked of you (like I said, it's requested for good reason whether you think it is or not).

**Comment by johnryanlee** [comment]
@ntoff Apologies for my comment.  I was not trying to be arrogant, it was meant to be humorous sarcasm.  The software is awesome and I am grateful to be able to use it!  I will treat this professionally going forward.

I will do as you say tonight when I can test again.

**Comment by foosel** [comment]
Just for the record, positioning of your printed objects on the bed are between your slicer and your printer. OctoPrint only pumps GCODE produced by your slicer to your printer, it doesn't modify or add anything. See also https://github.com/foosel/OctoPrint/wiki/FAQ#octoprint-is-telling-my-printer-to-do-wrong-things. This also applies to your other ticket #2127

**Comment by johnryanlee** [comment]
Does the export of the Cura profile include printer information?  I see there are start/end GCODES in the profile file which I removed in an attempt to get this issue sorted out.

Please excuse me, I've only been at this for 2 days and only having a printer for 5 - made sure it worked and now started hacking it.

My reasoning for this being a "request" is that I feel the firmware just handles the "how to position" and failsafes while the software handles the "do this" and "do that".  So a start position or an offset/override could be configured through OctoPrint.  In my research I do see that there are codes to override stuff so that means OctoPrint can do it and does provide the feature through job statuses (start/cancel/end/complete; etc), but I don't know how to use that yet.  I am studying the RepRap wiki but perhaps you could assist.

**Comment by johnryanlee** [comment]
Recv: echo:busy: processing
Recv:  T:190.26 /190.00 B:69.99 /70.00 @:27 B@:127 W:0
Recv: ok
Send: N8 M107*45
Recv: ok
Send: N9 G0 F4800 X-9.897 Y5.298 Z0.200*57
Recv: ok
Send: N10 G1 F1800 X-18.900 Y5.298 E0.22458*46
Recv: ok
Send: N11 G1 X-18.900 Y-35.784 E1.24938*90
Recv: ok
Send: N12 G1 X-18.852 Y-36.778 E1.27420*88
Recv: ok
Send: N13 G1 X-18.685 Y-37.907 E1.30267*89
Recv: ok
Send: N14 G1 X-18.406 Y-39.028 E1.33149*81
Recv: ok
Send: N15 G1 X-18.025 Y-40.096 E1.35977*93
Recv: ok
Send: N16 G1 X-17.537 Y-41.131 E1.38832*87
Recv: ok
Send: N17 G1 X-16.948 Y-42.115 E1.41692*92
Recv: ok
Send: N18 G1 X-16.268 Y-43.032 E1.44540*86
Recv: ok
Send: N19 G1 X-15.503 Y-43.878 E1.47385*84
Recv: ok
Send: N20 G1 X-14.658 Y-44.648 E1.50237*86
Recv: ok
Send: N21 G1 X-13.737 Y-45.334 E1.53102*81
Recv: ok
Send: N22 G1 X-12.756 Y-45.920 E1.55952*80
Recv: ok
Send: N23 G1 X-11.712 Y-46.418 E1.58838*87
Recv: ok
Send: N24 G1 X-10.642 Y-46.799 E1.61671*86
Recv: ok
Send: N25 G1 X-9.540 Y-47.077 E1.64506*110
Recv: ok
Send: N26 G1 X-8.395 Y-47.249 E1.67394*99
Recv: ok
Send: N27 G1 X-7.389 Y-47.300 E1.69907*98
Recv: ok
Send: N28 G1 X23.885 Y-47.300 E2.47920*123
Recv: ok
Send: N29 G1 X24.879 Y-47.250 E2.50403*112
Recv: ok
Send: N30 G1 X26.008 Y-47.084 E2.53249*116
Recv: ok
Send: N31 G1 X27.115 Y-46.807 E2.56096*126
Recv: ok
Send: N32 G1 X28.192 Y-46.425 E2.58947*122
Recv: ok
Send: N33 G1 X29.228 Y-45.936 E2.61804*120
Recv: ok
Send: N34 G1 X30.210 Y-45.351 E2.64656*123
Recv: ok
Send: N35 G1 X31.133 Y-44.668 E2.67520*118
Recv: ok
Send: N36 G1 X31.981 Y-43.899 E2.70376*112
Recv: ok
Send: N37 G1 X32.749 Y-43.054 E2.73224*116
Recv: ok
Send: N38 G1 X33.430 Y-42.137 E2.76073*119
Recv: ok
Send: N39 G1 X34.019 Y-41.157 E2.78925*127
Recv: ok
Send: N40 G1 X34.511 Y-40.124 E2.81780*126
Recv: ok
Send: N41 G1 X34.898 Y-39.044 E2.84641*115
Recv: ok
Send: N42 G1 X35.180 Y-37.924 E2.87522*117
Recv: ok
Send: N43 G1 X35.347 Y-36.804 E2.90347*124
Recv: ok
Send: N44 G1 X35.398 Y-35.797 E2.92862*113
Recv: ok
Send: N45 G1 X35.399 Y5.298 E3.95374*111
Recv: ok
Send: N46 G1 X25.997 Y5.298 E4.18828*105
Recv: ok
Send: N47 G1 X25.997 Y7.400 E4.24071*102
Recv: ok
Send: N48 G1 X35.399 Y7.400 E4.47524*108
Recv: ok
Send: N49 G1 X35.399 Y17.674 E4.73153*94
Recv: ok
Send: N50 G1 X-12.011 Y47.300 E6.12610*123
Recv: ok
Send: N51 G1 X-22.499 Y47.300 E6.38772*112
Recv: ok
Send: N52 G1 X-22.499 Y40.997 E6.54495*112
Recv: ok
Send: N53 G1 X-24.602 Y40.997 E6.59741*112
Recv: ok
Send: N54 G1 X-24.602 Y47.300 E6.75464*126
Recv: ok
Send: N55 G1 X-29.515 Y47.300 E6.87719*115
Recv: ok
Send: N56 G1 X-30.671 Y47.116 E6.90639*121
Recv: ok
Send: N57 G1 X-31.173 Y47.032 E6.91909*118
Recv: ok
Send: N58 G1 X-32.888 Y46.160 E6.96708*120
Recv: ok
Send: N59 G1 X-34.262 Y44.786 E7.01555*120
Recv: ok
Send: N60 G1 X-35.139 Y43.059 E7.06387*114
Recv: ok
Send: N61 G1 X-35.398 Y41.420 E7.10526*120
Recv: ok
Send: N62 G1 X-35.400 Y13.285 E7.80709*117
Recv: ok
Send: N63 G1 X-35.216 Y12.129 E7.83629*113
Recv: ok
Send: N64 G1 X-35.133 Y11.631 E7.84889*124
Recv: ok
Send: N65 G1 X-34.262 Y9.911 E7.89698*76
Recv: ok
Send: N66 M105*23
Recv: ok T:190.00 /190.00 B:70.45 /70.00 @:31 B@:0
Send: N67 G1 X-32.899 Y8.552 E7.94499*67
Recv: ok
Send: N68 G1 X-31.168 Y7.664 E7.99352*76
Recv: ok
Send: N69 G1 X-29.522 Y7.402 E8.03510*64
Recv: ok
Send: N70 G1 X-9.897 Y7.400 E8.52465*124
Recv: ok
Send: N71 G1 X-9.897 Y5.298 E8.57708*117
Recv: ok
Send: N72 G1 F2400 E4.07708*58
Recv: ok
Send: N73 G0 F4800 X-5.997 Y1.398*90
Recv: ok
Send: N74 G1 F2400 E8.57708*53
Recv: ok
Send: N75 G1 F1800 X-15.000 Y1.398 E8.80166*36
Recv: ok
Send: N76 G1 X-15.000 Y-35.693 E9.72690*94
Recv: ok
Send: N77 G1 X-14.966 Y-36.394 E9.74441*94
Recv: ok
Send: N78 G1 X-14.854 Y-37.149 E9.76345*83
Recv: ok
Send: N79 G1 X-14.667 Y-37.904 E9.78285*94
Recv: ok
Send: N80 G1 X-14.417 Y-38.605 E9.80142*83
Recv: ok
Send: N81 G1 X-14.094 Y-39.288 E9.82026*92
Recv: ok
Send: N82 G1 X-13.698 Y-39.951 E9.83953*87
Recv: ok
Send: N83 G1 X-13.248 Y-40.557 E9.85835*92
Recv: ok
Send: N84 G1 X-12.736 Y-41.123 E9.87739*81
Recv: ok
Send: N85 G1 X-12.180 Y-41.630 E9.89616*92
Recv: ok
Send: N86 G1 X-11.564 Y-42.088 E9.91531*91
Recv: ok
Send: N87 G1 X-10.909 Y-42.480 E9.93435*87
Recv: ok
Send: N88 G1 X-10.216 Y-42.811 E9.95351*90
Recv: ok
Send: N89 G1 X-9.506 Y-43.063 E9.97230*109
Recv: ok
Send: N90 G1 X-8.776 Y-43.248 E9.99109*109
Recv: ok
Send: N91 G1 X-8.002 Y-43.364 E10.01061*81
Recv: ok
Send: N92 G1 X-7.291 Y-43.400 E10.02837*88
Recv: ok
Send: N93 G1 X23.790 Y-43.400 E10.80369*76
Recv: ok
Send: N94 G1 X24.494 Y-43.365 E10.82127*69
Recv: ok
Send: N95 G1 X25.246 Y-43.254 E10.84024*75
Recv: ok
Send: N96 G1 X25.989 Y-43.068 E10.85934*68
Recv: ok
Send: N97 G1 X26.708 Y-42.813 E10.87837*68
Recv: ok
Send: N98 G1 X27.393 Y-42.490 E10.89726*74
Recv: ok
Send: N99 G1 X28.045 Y-42.101 E10.91620*79
Recv: ok
Send: N100 G1 X28.652 Y-41.652 E10.93504*123
Recv: ok
Send: N101 G1 X29.227 Y-41.131 E10.95439*118
Recv: ok
Send: N102 G1 X29.728 Y-40.579 E10.97299*120
Recv: ok
Send: N103 G1 X30.188 Y-39.960 E10.99223*120
Recv: ok
Send: N104 G1 X30.580 Y-39.308 E11.01120*119
Recv: ok
Send: N105 G1 X30.905 Y-38.626 E11.03005*123
Recv: ok
Send: N106 G1 X31.164 Y-37.905 E11.04916*123
Recv: ok
Send: N107 G1 X31.350 Y-37.165 E11.06819*125
Recv: ok
Send: N108 G1 X31.462 Y-36.413 E11.08716*127
Recv: ok
Send: N109 G1 X31.498 Y-35.708 E11.10477*124
Recv: ok
Send: N110 G1 X31.499 Y1.398 E12.03038*108
Recv: ok
Send: N111 G1 X22.097 Y1.398 E12.26491*101
Recv: ok
Send: N112 G1 X22.097 Y11.300 E12.51192*80
Recv: ok
Send: N113 G1 X31.499 Y11.300 E12.74645*83
Recv: ok
Send: N114 G1 X31.499 Y15.513 E12.85155*92
Recv: ok
Send: N115 G1 X-13.129 Y43.400 E14.16427*114
Recv: ok
Send: N116 G1 X-18.599 Y43.400 E14.30072*117
Recv: ok
Send: N117 G1 X-18.599 Y37.097 E14.45795*113
Recv: ok
Send: N118 G1 X-28.502 Y37.097 E14.70498*119
Recv: ok
Send: N119 G1 X-28.502 Y43.400 E14.86221*114
Recv: ok
Send: N120 G1 X-29.205 Y43.400 E14.87975*114
Recv: ok
Send: N121 G1 X-29.944 Y43.282 E14.89842*122
Recv: ok
Send: N122 G1 X-30.568 Y42.965 E14.91588*114
Recv: ok
Send: N123 G1 X-31.064 Y42.469 E14.93337*122
Recv: ok
Send: N124 G1 X-31.383 Y41.841 E14.95094*126
Recv: ok
Send: N125 G1 X-31.498 Y41.112 E14.96935*124
Recv: ok
Send: N126 G1 X-31.500 Y13.595 E15.65577*116
Recv: ok
Send: N127 G1 X-31.382 Y12.857 E15.67441*125
Recv: ok
Send: N128 M105*44
Recv: ok T:189.95 /190.00 B:69.55 /70.00 @:31 B@:0
Send: N129 G1 X-31.066 Y12.232 E15.69188*125
Recv: ok
Send: N130 G1 X-30.575 Y11.742 E15.70919*122
Recv: ok
Send: N131 G1 X-29.943 Y11.419 E15.72689*115
Recv: ok
Send: N132 G1 X-29.211 Y11.302 E15.74538*126
Changing monitoring state from 'Printing' to 'Operational'
Recv: ok
Send: M400
Recv: ok
Send: M114
Recv: X:0.00 Y:11.30 Z:0.20 E:15.75 Count X:0 Y:890 Z:512
Recv: ok
Send: M84
Recv: ok
Send: M104 T0 S0
Recv: ok
Send: M140 S0
Recv: ok
Send: M106 S0
Recv: ok
Send: M117 Job cancelled!
Recv: ok
Send: M105
Recv: ok T:190.00 /0.00 B:68.79 /0.00 @:0 B@:127
Send: M105
Recv: ok T:189.66 /0.00 B:68.60 /0.00 @:0 B@:0
Recv: echo:enqueueing "G28"
Recv: echo:busy: processing
Send: M105
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: X:0.00 Y:0.00 Z:0.00 E:15.75 Count X:0 Y:0 Z:0
Recv: ok T:185.42 /0.00 B:65.30 /0.00 @:0 B@:0
Send: M105
Recv: ok T:185.42 /0.00 B:65.30 /0.00 @:0 B@:0
Send: M105
Recv: ok T:183.85 /0.00 B:64.81 /0.00 @:0 B@:0
Send: M105
Recv: ok T:180.82 /0.00 B:64.17 /0.00 @:0 B@:0
Send: M105

**Comment by johnryanlee** [comment]
I managed to figure out the X axis offset and saved to EEPROM
M206 X-20, what I actually needed was M206 X-40
Then M500 to save
Then M501 to recall to confirm

Now what i'm finding is that when it's filling in, it's moving straight instead of diagonal and the X axis is showing what the Y axis is doing.  However on the control screen, everything works as it should.

This issue can be closed.  As much as it would be a nice to have it's apparent that the setting should be in the on the printer.  Apologies for coming across as arrogant earlier.  It was never my intention.

**Comment by johnryanlee** [comment]
Issue is the slicer. most likely the slicer profile.
I saved the slice from the easyprint 3d software. Uploaded to Octopi and it worked. 

A lot of knowledge gained today and hopefully not enemies.

**Comment by ntoff** [comment]
>This issue can be closed.

You have the power to close your own issues, if you really are done with it then you should be able to close it yourself (to save foosel the trouble).

Also if you require assistance, you may wish to use the G+ group or the mailing list and save this place for bug reports as your issue seems to be more one of how to set up your slicer to match your printer than some sort of bug in the way OctoPrint works (given your other thread).

https://groups.google.com/group/octoprint

https://plus.google.com/communities/102771308349328485741

Or there's always reddit https://www.reddit.com/r/3Dprinting although that's more of a general 3d printing forum, it's not dedicated to octoprint, but it might yield some info if you need help setting up your slicer.

**Comment by foosel** [comment]
Closing this as requested. No enemies gained I think ;)
