### ISSUE TITLE
[Request] Prevent non-authenticated users from seeing printer status, camera and downloading STL files

### ISSUE THREAD

**Issue by HongkaiWuLab** [foosel/OctoPrint#2149]
I would like to request that the printer information not be visible for non-authenticated users. Currently users that visit the octoprint website can see the printer information, view the camera, printer status, view and download STL files without entering any login or password. Is it possible to force a login screen (instead of having it in the top right corner) before they get to see this info?

#### What did you expect to happen?
I think it is better if non-authenticated users cannot view and download STL files and/or the printers camera.

1. One possibility would be to add a guest account: if enabled then keep it the same as it is now, if disabled show the login screen until authenticated (best option).
2. Another option would be to just prevent users from downloading / viewing the STL queue, printer status and camera until they are authenticated via the login dialog box in the top right corner.

#### Branch & Commit or Version of OctoPrint
OctoPrint 1.3.4 (master branch) 

#### Operating System running OctoPrint
OctoPi

#### Printer model & used firmware incl. version
not applicable

#### Browser and Version of Browser, Operating System running Browser
Firefox 56.0

**Comment by foosel** [comment]
Already tracked in #1110, closing as duplicate
