### ISSUE TITLE
Plugin manager broken (maintenance / devel branch)

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#2151]
#### What were you doing?

Trying to install touchui

#### What did you expect to happen?

Touch UI to be installed, that I might bask in its majesty

#### What happened instead?

big red error box of death (also see screenshot)

#### Did the same happen when running OctoPrint in safe mode?

You can't install plugins in safemode so I'm not sure how I'd test that one.

#### Branch & Commit or Version of OctoPrint

This seems to be the commit in question where it stopped working: https://github.com/foosel/OctoPrint/commit/c5e7212fa2a75ab20b1d8c0a437eb6777627337e

The previous commit works fine, while that one gives me an error

As for an actual version number: OctoPrint 1.3.6.dev59+gd1fdbd5 (maintenance branch) but I tested it using a bunch of different commit hash things to figure out that it worked prior to that previous commit.

#### Operating System running OctoPrint

linux mint 18 (I think), which is running in virtualbox on windows 10

`uname -a`
>Linux mint-VirtualBox 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Printer model & used firmware incl. version

virtual printer plugin

#### Browser and Version of Browser, Operating System running Browser

firefox 56.0 (64-bit) linux mint

#### Link to octoprint.log

BEHOLD! in all its glory https://gist.github.com/ntoff/fd0f0620d50f82c3dd17fd01507115f0

#### Link to contents of terminal tab or serial.log

not serial related

#### Link to contents of Javascript console in the browser

![image](https://user-images.githubusercontent.com/9030085/31444617-0cddae8a-aee0-11e7-8909-7cb26cad4099.png)

#### Screenshot(s)/video(s) showing the problem:

see above

#### Other Info / Extras ####

Installing manually using `octoprint dev plugin:install` works (only tested using my own plugins though)

I have read the FAQ.

**Comment by foosel** [comment]
And fixed on both `maintenance` and `devel`. Thanks for spotting this, slightly embarrassing.
