### ISSUE TITLE
Spelling errors in "Approx. Total Print Time" hover message

### ISSUE THREAD

**Issue by arose62** [foosel/OctoPrint#2167]
#### What were you doing?

Hovering mouse over "Approx. Total Print Time" in the "State" region.

#### What did you expect to happen?

A pop-up message saying "Estimated total print time based on statistical analysis of past prints"

#### What happened instead?

A pop-up message saying "Estimated total print time base on statical analysis or past prints"
3 spelling and/or grammatical errors: "base" should be "based", "statical" should be "statistical", and "or" probably should be "of".

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.4 (master branch)

#### Operating System running OctoPrint

OctoP Jessie.

#### Printer model & used firmware incl. version

Cocoon Touch

#### Browser and Version of Browser, Operating System running Browser

Google Chrome Version 46.0.2490.86

#### Screenshot(s)/video(s) showing the problem:

![spellingerrors](https://user-images.githubusercontent.com/3906422/31860873-809859d4-b76d-11e7-81ff-a6d29f296ad1.png)

I have read the FAQ.

**Comment by foosel** [comment]
Thanks. "base" indeed was a typo, "statical" a horrible mixture of "static" and "statistical", both of which more misleading than accurate, and "or" is actually correct (it's analysis of the file or past prints). 

Changed to "Estimated total print time based on analysis of the file or past prints" on `maintenance`, soon `devel`, will be released with 1.3.6.
