### ISSUE TITLE
REST API connection internal server error

### ISSUE THREAD

**Issue by aurror** [foosel/OctoPrint#2189]
#### What were you doing?

Trying to connect octoprint to the printer via the REST API.
The api/connection GET method works, but while trying to set the connection with POST,
i got an error.

Relevant code in my setup:
`

function connectToPrinter(){

        let connectInfo = {"command": "connect", "port": "/dev/ttyACM0", "baudrate": "115200", "printerProfile": "PrintIt 3020", "save": false, "autoconnect": true}

        $.ajax({
          url: 'http://printit.local/api/connection',
          headers: { 'X-Api-Key': 'XXXXXXXXXXXXXXXXXXXXXX...'},
          crossDomain: true,
          contentType: 'application/json, charset=UTF-8',
          method: 'POST',
          data: JSON.stringify(connectInfo),
          dataType: 'json',
          success: function(responseData, textStatus, jqXHR){
            
          },
          error: function (responseData, textStatus, errorThrown) 
          {
              console.warn(responseData, textStatus, errorThrown);
              alert('could not connect to printer');
              alert(errorThrown);
          }
        })
      }
`

#### What did you expect to happen?

Octoprint connects to the printer.

#### What happened instead?

Octoprint did not connect to the printer, and I got an INTERNAL SERVER ERROR message.

Log error: AttributeError: 'NoneType' object has no attribute 'keys'

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.5 (master branch) 

#### Operating System running OctoPrint

Linux

#### Link to octoprint.log

https://gist.github.com/aurror/1f8769c9d6b9e7b0c71459d87533ade2

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
You are sending an invalid request, your content-type header is wrong. The charset is to be separated with a `;`, not a `,`. See also [here](https://tools.ietf.org/html/rfc7231#section-3.1.1.5).

This should work:

``` javascript
function connectToPrinter(){

    let connectInfo = {"command": "connect", "port": "/dev/ttyACM0", "baudrate": "115200", "printerProfile": "PrintIt 3020", "save": false, "autoconnect": true}

    $.ajax({
      url: 'http://printit.local/api/connection',
      headers: { 'X-Api-Key': 'XXXXXXXXXXXXXXXXXXXXXX...'},
      crossDomain: true,
      contentType: 'application/json; charset=UTF-8',
      method: 'POST',
      data: JSON.stringify(connectInfo),
      dataType: 'json',
      success: function(responseData, textStatus, jqXHR){
        
      },
      error: function (responseData, textStatus, errorThrown) 
      {
          console.warn(responseData, textStatus, errorThrown);
          alert('could not connect to printer');
          alert(errorThrown);
      }
    })
}
```
