### ISSUE TITLE
Temperature fields don't select text in MS Edge on focus

### ISSUE THREAD

**Issue by Mikk36** [foosel/OctoPrint#2214]
Seems to be a simple fix where you'd need to queue the select() with setTimeout to get it working. Fix doesn't affect other browsers.

https://github.com/foosel/OctoPrint/blob/37990996b7c0ec24a0363406f9d8cad8654a5849/src/octoprint/static/js/app/viewmodels/temperature.js#L725
https://github.com/foosel/OctoPrint/blob/37990996b7c0ec24a0363406f9d8cad8654a5849/src/octoprint/static/js/app/viewmodels/temperature.js#L727

Change to
`setTimeout(() => event.target.select(), 0);`

**Comment by foosel** [comment]
Fix on `maintenance`, soon `devel`, will be part of 1.3.6
