### ISSUE TITLE
[Request] Full screen webcam preview in Control tab

### ISSUE THREAD

**Issue by 14422** [foosel/OctoPrint#2225]
I'd like to have a button to toggle webcam preview to full screen in Control tab. The button could be on the right bottom corner for this, visible only when hovering mouse on the preview. Esc-key would be used to get back to normal view.

**Comment by ntoff** [comment]
already a plugin for that http://plugins.octoprint.org/plugins/fullscreen_webcam/

**Comment by foosel** [comment]
As already pointed out - available through a plugin. Closing.
