### ISSUE TITLE
Movement distance buttons don't disable with the other buttons on the control tab

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#2232]
#### What were you doing?

Testing something

Ideally provide exact steps to follow in order to reproduce your problem:

1. load gcode
2. press print
3. notice the distance selection buttons don't disable along with the direction buttons

Alternatively:

1. disconnect from the printer
2. notice the distance selectors are still active

#### What did you expect to happen?

That the distance buttons follow the same `data-bind="enable: isOperational() && !isPrinting() && loginState.isUser(), ...` as the movement direction buttons.

#### What happened instead?

The distance selectors only care about whether a user is logged in `data-bind="enable: $root.loginState.isUser(), ...` and ignore print status and connection status.

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.5 (master branch)

#### Operating System running OctoPrint

linux mint 18

#### Printer model & used firmware incl. version

virtual printer / no printer

#### Browser and Version of Browser, Operating System running Browser

![image](https://user-images.githubusercontent.com/9030085/33103614-ff2e39b2-cf6e-11e7-90ee-8af6fc7429f8.png)

#### Link to octoprint.log

n/a

#### Link to contents of terminal tab or serial.log

Not a serial issue

#### Link to contents of Javascript console in the browser

Not a javascript issue

#### Screenshot(s)/video(s) showing the problem:

printing:

![image](https://user-images.githubusercontent.com/9030085/33103548-9decf008-cf6e-11e7-9c61-90c145ece730.png)

disconnected:

![image](https://user-images.githubusercontent.com/9030085/33103798-53bf2d50-cf70-11e7-8446-bd249790ce7a.png)

I have read the FAQ.

**Comment by foosel** [comment]
Good point. Has been changed on `maintenance`, soon `devel`, will be part of 1.3.6.
