### ISSUE TITLE
Store filter setting (checked filter boxes) in the "terminal" tab

### ISSUE THREAD

**Issue by hp-bioing** [foosel/OctoPrint#225]
Situation:
It is not a big thing, but every time you restart OctoPrint you have to re-check your favorite filters in the "terminal" tab.

Aim of this issue:
Would be handy, if the filter settings would be stored based on the user logged into OctoPrint.

**Comment by foosel** [comment]
Implemented via the [ActiveFilters plugin](https://github.com/MoonshineSG/OctoPrint-ActiveFilters).
