### ISSUE TITLE
[Request] Get filename of selected file from the API

### ISSUE THREAD

**Issue by Nedevski** [foosel/OctoPrint#2251]
I am creating an Alexa skill and I've found that I have no way to get information about the currently selected file via the API.

I need only the filename, but if it's the full file object, that would be useful too.

**Comment by foosel** [comment]
Uhm... http://docs.octoprint.org/en/master/api/job.html#retrieve-information-about-the-current-job

**Comment by Nedevski** [comment]
Oh, so when you select a file, it becomes visible in the job, even if it's not started yet?

If that's so - my bad.

**Comment by foosel** [comment]
Yes. A job is a job even before it's started. Current modelling only ever has one active job, and that maps 1:1 to the currently selected file in the UI. I'll add a note to the docs though, you are the second person in the past two months that's stumbled over this :)

May I ask where you were looking for a way to retrieve the currently selected file? In the [file operations section](http://docs.octoprint.org/en/master/api/files.html)?

**Comment by Nedevski** [comment]
No, I was looking in the job operations section, I just assumed that a job exists only when the printer is printing.

But I admit that I completely overlooked the Retrieve info about current job endpoint, since I assumed it's of no use to me. My bad there.

Thanks for the fast responses!
