### ISSUE TITLE
[REQUEST] Color of navbar in #xxxxxx format?

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#2252]
Could we have the color of the navbar user selectable in RGB format instead of a dropdown of predefined colors? OR a way to add more colors to that list from a plugin maybe?

Thanks!

**Comment by ntoff** [comment]
https://github.com/birkbjo/OctoPrint-Themeify

**Comment by bolsoncerrado** [comment]
Awesome! Thanks!

**Comment by foosel** [comment]
I guess that plugin solves that ;)
