### ISSUE TITLE
Add user defined tabs to OctoPrint 

### ISSUE THREAD

**Issue by hp-bioing** [foosel/OctoPrint#227]
Would be nice if a user could add additional tabs (similar to "control", "terminal" etc.) to OctoPrint for separating special custom buttons out of the "control" tab. 

For example for bed-leveling I defined a set of custom buttons with special g-ocde commands for driving to special positions; I need this buttons maybe once a week, when changing something on my printer.  In the meantime these buttons are not used and only taking up room on the "control" tab.

**Comment by foosel** [comment]
Possible in `devel` through plugins, see [the TemplatePlugin mixin](http://docs.octoprint.org/en/devel/plugins/mixins.html#templateplugin)
