### ISSUE TITLE
Extended features for timelapse video recording

### ISSUE THREAD

**Issue by CTPalle** [foosel/OctoPrint#228]
The aim it to improve the videos and make them also user-definable in length.

 - SEVERAL IMAGES PER LAYER

When Timelapse Mode "On Z Change" is used. Videos only record one frame per layer. Sometimes the final videos would be nicer to look at if they where prolonged.  A way to define this would be to let the user input the number of frames to record per layer. These would be distributed more or less evenly across the duration of the layer print.

The user interface would give a feedback of how many hours/minutes/seconds the final video would become in relation to the frames-per-second of the MPG-file.

 - USER-SPECIFIED TOTAL VIDEO DURATION

Here the user can choose to simply input the number of hours/minutes/seconds that the final video should last. The frames would then be calculated and spread more or less evenly across the total 3D print.

![octoprint time-lapse video feature suggestion](https://f.cloud.github.com/assets/5244671/975291/84b43326-0673-11e3-861a-d0380b2bd70c.png)

**Comment by foosel** [comment]
fps can be defined on `devel`. Don't see a way to make the other things requested work, so closing this.
