### ISSUE TITLE
Stream the sound of the 3D printer

### ISSUE THREAD

**Issue by CTPalle** [foosel/OctoPrint#229]
As a complementary feature to the video streaming there could be sound streaming as well.

This would make it easy for an experienced 3D printer operator to hear what is happening instead of just being able to see the video.

It would be nice if on could choose only to have sound and no video as an option to save bandwidth.

Naturally the sound streaming feature should be an optional thing since it tends to create privacy issues if one can hear what is going on in the same room as the 3D printer.

**Comment by foosel** [comment]
Not going to implement this (I just don't see the use case), if someone wants to give it a go as a plugin, feel free.

**Comment by sheepslinky** [comment]
I may give this a try at some point, as I see the utility. I am an acoustician and musician, and can hear printing problems easily. Both my printers have very different pitch / rhythms which depends on stable, repetitive movement. If the pitch and cadence change suddenly, it indicates a drastic change in the printing behavior.

**Comment by JohnOCFII** [comment]
@sheepslinky You might want to look at the UV4L utilities to stream audio from your Raspberry Pi: http://www.linux-projects.org/uv4l/

**Comment by alex-gibson** [comment]
@sheepslinky did you ever manage this?  I have built a huge 3d printer.  It takes several days to print large, detailed objects over 2m tall.  It would be impractical to constantly watch the video, but I could have a constant audio feed to my office and act immediately if there were an issue!

**Comment by Jaaaacccckk** [comment]
I'm just a hobbyist.  But, I think that sound is the logical addition to video.  My son's teacher wants to see what a 3d printer is like and we are going to demo using an OctoPrint feed.  Sound would be great to have there as well!  I also don't think of my printer as sounding like it is grinding.  It has taken so much effort to get it to work that I find the sound part of the overall gratifying effect.

**Comment by vandal98** [comment]
I absolutely agree that sound would be a great option.  My printer sits behind me in my office, and sound is usually the first thing that alerts me to a problem.  The "crinkle" of support material that has detached and is being struck by the nozzle.  The "click" of a filament that has jammed.  The "jump" of the final strand of filament that has just pulled out of the spool and indicates that you have only a few minutes to feed a fresh spool in behind it, if you want to save the print.  By the time you see the problem visually, it's usually too late to save it.

**Comment by clinthart2003** [comment]
As a second use-case,  Say I have a printer under warranty.   during the print there is grinding or some other noise that isn't easily reproducible because it happens at layer 500+.   If there is sound and audio being recorded, I can trim the video with audio and send that as part of the warranty request.  Or for Support to review.   It is totally a valid use-case, and one I run into a lot with the new Ender 5+

**Comment by mrbodiddley** [comment]
Hej guys and girls, I would love sound as an option. Ordered a Pi Mic and Cam for Octoprint before my first 3d printer arrived ;)

To me it would also be an obvious very helpful addition to the video feed. After a couple month experience with 3dprinting, I could imagine also the spaghetti detective could easily learn some sound patterns? I mean a stripping filament or knocked off object has such a “typical” sound.

Unfortunately my experience does not allow yet to contribute to a plugin in any way.

Maybe? Any chance?

**Comment by clinthart2003** [comment]
Nope.    I wish they would.

**Comment by jneilliii** [comment]
Being this is more of a request related to streaming and not octoprint directly, you guys may want to open a request on the octopi repo, as that is what is setting up mjpgstreamer and not octoprint. I do know there is an experimental HLS stream support enabled in the nightly builds of octoprint and you may be able to utilize that as an alternative to mjpgstreamer. More details can be found here. 

https://community.octoprint.org/t/experimental-hls-support/20336

**Comment by mrbodiddley** [comment]
Thx Guys, I’ll take a look at HLS then
