### ISSUE TITLE
Temperature monitoring on Sprinter(?) firmware

### ISSUE THREAD

**Issue by splitbrain** [foosel/OctoPrint#23]
When sending the M105 command, my RepRapPro Huxley answers with current temperatures only:

```
Send: M105
Recv: ok T:198 B:59
```

There's no info about the current target. It should be possible to watch the gcode for any temperature target changes within OctoPrint itself and adjust the UI accordingly.

**Comment by foosel** [comment]
That is actually solved since ages, I just never remembered to close this O_O
