### ISSUE TITLE
Update Issue 1.3.5 -> 1.3.6 - Missing Functions?

### ISSUE THREAD

**Issue by camronnie** [foosel/OctoPrint#2306]
#### What were you doing?

Updating from 1.3.5 to 1.3.6.
I deleted my OctoPrint folder in the C drive, and started over from scratch, following the same Windows installation steps that I used to install 1.3.5.

#### What did you expect to happen?

To successfully install 1.3.6.

#### What happened instead?

1.3.6 installs, but I am missing functions.  I no longer have calibration functions, slicing does not initiate my Cura plugin for modification, and when I hit print on a previous part, I do not get a prompt for print temperature.

I tried to revert back to 1.3.5, but the OctoPrint web interface appears to be the same.  To revert I deleted the OctoPrint folder from my C drive, and followed the Windows instructions I followed initially to install 1.3.5 on the Wiki, but the missing functions are still missing.

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Version of OctoPrint

1.3.6.

#### Operating System running OctoPrint

Windows 7

#### Printer model & used firmware incl. version

M3D Micro - using iMe / M33 Fio

#### Browser and Version of Browser, Operating System running Browser

Firefox 57.0.2

#### Link to octoprint.log

[octoprint.log](https://github.com/foosel/OctoPrint/files/1575253/octoprint.log)

#### Screenshot(s)/video(s) showing the problem:

![octoprint missing functions](https://user-images.githubusercontent.com/34710270/34204088-0fab42f0-e543-11e7-8d28-5157131ce791.PNG)

I have read the FAQ.

**Comment by ntoff** [comment]
1.3.6 changed the way plugins are loaded, plugins that relied on global variables no longer function.

https://octoprint.org/blog/2017/12/01/heads-up-plugin-authors/

It's possible the plugins you rely on will need to be updated by the authors to be compatible with OctoPrint's new system. In the mean time you can open OctoPrint's settings dialog, go to features, and tick the checkbox to enable legacy plugin bundling.

**Comment by kantlivelong** [comment]
@camronnie if the legacy option works please let us know as well as open a ticket with the plugin developer.

**Comment by camronnie** [comment]
I tried the legacy plugin bundling, but that is not changing anything.  I am still missing the previous functions that I had.

Currently:
![octoprint missing functions](https://user-images.githubusercontent.com/34710270/34235648-a7226602-e5b8-11e7-9035-c35b9211268b.PNG)

And a few screen shots from https://www.thingiverse.com/groups/m3d-the-micro-3d-printer/forums/general/topic:5096 of what I am missing:

![missing 1](https://user-images.githubusercontent.com/34710270/34235659-b75267fc-e5b8-11e7-8cac-4f1e050510dd.PNG)
![missing 2](https://user-images.githubusercontent.com/34710270/34235660-b76e7c94-e5b8-11e7-82f0-cc7f61a01de5.PNG)

I am able to connect to my printer, and move it, but am missing key features to be able to print.  I was also unable to correct this by trying to revert back to 1.3.5.  Maybe I was on 1.3.4.... I'll try that just to be sure.

**Comment by camronnie** [comment]
So the same thing is still happening on 1.3.4.  It also seems/feels like the web/user interface is not changing?

I never had a webcam stream screen until I installed 1.3.6, and that is also when my calibration controls went away.

![capture](https://user-images.githubusercontent.com/34710270/34236296-7b7e2096-e5bc-11e7-8469-2c6450393e4f.PNG)


Is the best way to uninstall to install a different version to simply delete the OctoPrint folder and start over?

**Comment by kantlivelong** [comment]
You can delete the config directory. https://github.com/foosel/OctoPrint/wiki/Configuration

Webcam stream can be disabled by clearing out the webcam related settings.

As for M33-Fio:
While it is possible that there could be a bug in OctoPrint you're going to need to open an issue on the M33-Fio repo. This issue tracker is specifically for OctoPrint core issues.

**Comment by camronnie** [comment]
Got everything sorted back out, and I'm back on 1.3.5 for now, I'll try 1.3.6 later.  I had to find under my roaming files (Windows OS) an OctoPrint folder that needed to be deleted.  Once that was deleted, and 1.3.5 reinstalled, everything is working correctly.

**Comment by kantlivelong** [comment]
Closing
