### ISSUE TITLE
Gcode editor

### ISSUE THREAD

**Issue by MrBalonio** [foosel/OctoPrint#231]
One thing I would be nice is a way to modify uploaded gcode files. Some times there's a need to just adjust the temperature or another parameter on the gcode file and instead of re-uploading it, it would be nice to be able to edit the file in octoprint.

anyone else need this?

**Comment by smartroad** [comment]
I was just thinking this! I wanted to edit temps in the gcode for a couple of files. Currently I have to delete, re-slice and upload a whole new file.

**Comment by Salandora** [comment]
Working on this as a little side project, main project is actually the FileManager.
Will report back when I have to show something.

**Comment by foosel** [comment]
Just for the record:

> or maybe an editable "post-print" gcode section

Settings > GCODE Scripts

> conditionally set up an event (like a checkbox that says "shutdown when
print complete")

http://plugins.octoprint.org/plugins/automaticshutdown/

Both possible with 1.2.0

**Comment by foosel** [comment]
This has been implemented [via this plugin](http://plugins.octoprint.org/plugins/GcodeEditor/).
