### ISSUE TITLE
Plugin GPX not saving settings

### ISSUE THREAD

**Issue by edacraneo** [foosel/OctoPrint#2347]
**What were you doing?**

Save settings in plugin GPX 2.6.0

**What did you expect to happen?**

my settings stay saved

**What happened instead?**

In the plugin settings, I configure this one like this: "replicator 2 with HBP" and "Makerbot", and i save. When i reboot the raspberry, the setting is different, as originally, it disappeared.

I tried different ways to record but impossible, my setting disappears each reboot.

**Version of OctoPrint**

1.3.6 Stable
GPX 2.6.0

**Printer model & used firmware incl. version**

Makerbot replicator 2 with HBP and latest firmware

**I have read the FAQ.**

Thank You a lot

**Comment by ntoff** [comment]
If you have a problem with a plugin, please post the issue in the plugin's own git issue tracker.

**Comment by kantlivelong** [comment]
As @ntoff said. This should be reported to the appropriate plugin tracker. Closing.
