### ISSUE TITLE
[Request] Speed up initial load

### ISSUE THREAD

**Issue by fabianhu** [foosel/OctoPrint#2360]
Hi!

Looking at the page source, I noticed that this is aiming for a responsive user experience.
But is it necessary to include the AGPL in full text and all the (old) notifications and news in the main html file?
This takes up almost 50% of the html.
Skipping this parts out of the responsiveness could speed up the initial load significantly on slow machines and over VPN/mobile.

Best regards & many thanks for the great work.

**Comment by kantlivelong** [comment]
Hi @fabianhu,

While the license does take up a decent chunk of the overall HTML(excluding js, css, images, etc..) it only amounts to roughly 40K which on a 1Mbit connection would take less than half a second to load. I'd say its a drop in the bucket and the time to load falls more on other dependencies and processing speed of the device that is loading the content.
