### ISSUE TITLE
No warning popup when "Not only cancel ongoing prints but also disconnect" not selected

### ISSUE THREAD

**Issue by KevinOConnor** [foosel/OctoPrint#2364]
#### What were you doing?

When I unselect the checkbox "Not only cancel ongoing prints but also disconnect on unhandled errors from the firmware" (via Settings->Serial Connection) and the firmware reports an error (via a response message starting with "!!") then OctoPrint successfully stops the print, but it does not report the error to the user in an obvious way.  In contrast, when the checkbox is selected (as is the default), OctoPrint does popup an error message - for example: Unhandled communication error
There was an unhandled error while talking to the printer. Due to that OctoPrint disconnected. Error: Move out of range: 0.000 -999.000 255.793 [0.000].

#### What did you expect to happen?

I expected OctoPrint to popup an error message.

#### What happened instead?

OctoPrint did react to the error, but did not warn the user.  I have to look through the terminal tab to find out what the error was.  Looking in the terminal tab is not convenient because OctoPrint also adds additional lines of status messages after the initial error message.

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Version of OctoPrint

OctoPrint 1.3.6 running on OctoPi 0.14.0

#### Operating System running OctoPrint

OctoPi 0.14.0

#### Printer model & used firmware incl. version

This is with Klipper (https://github.com/KevinOConnor/klipper).  Klipper reports errors via messages starting with "!!".

#### Browser and Version of Browser, Operating System running Browser

N/A

#### Link to octoprint.log

[octoprint.log](https://github.com/foosel/OctoPrint/files/1629575/octoprint.log)

#### Link to contents of terminal tab or serial.log

https://gist.github.com/KevinOConnor/427bfe9f6f7f50ddfbb6790cc61fdf17#file-gistfile1-txt

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s)/video(s) showing the problem:

N/A

I have read the FAQ.

**Comment by foosel** [comment]
Fixed as per b3fff6e, available on `maintenance`, soon `devel`, to be rolled out as part of 1.3.7
