### ISSUE TITLE
[Request] // action:stop

### ISSUE THREAD

**Issue by Nibbels** [foosel/OctoPrint#2367]
Hello there, I hope I did not miss some discussion on this when I scanned the Issues for the same request discussed earlier.

Octoprint supports these upstream commands natively:

- // action:disconnect
- // action:pause
- // action:resume

**Request: Please add** 
- // action:stop 
(or)
- // action:stopprint
to have a 100% pendant to repetiers "RequestStop:", which just stops printing.

When I look to repetier-server / repetier-host I have those:

- RequestStop:
- RequestPause:
- RequestContinue:

Why do I make this Request?

Because I want to have some kind of a feature standard. Once a while ago I startet to patch my printers custom firmware to a usable state. On that weird journey I found these upstream commands which are actually quite nice.
Sometimes I want to stop a print comming from the Raspberry PI without having to open some tablet or smartphone. This works when I print from SD. (Printers Menu -> Quicksettings -> Stop Print ...)
So I included the feature that when I do not print from the SD-Card the "RequestStop:" gets sent out.
When I heard from "// action:disconnect" I did the same. (The printer always sends the commands in both languages: Octoprint and Repetier).
The same behaviour works for pause and continue.
**I know about this plugin which would be the universal solution for this, but I personally think that if pause and continue is some global standard then stop should be a global standard too.**

Why does // action:disconnect not make the job? Because it is to harsh. Disconnecting means reconnecting. I see several states and possible errors that should stop a print but not disconnect the printer completely.

Greetings from Stuttgart

**Comment by Wessix** [comment]
+1

**Comment by foosel** [comment]
Agreed, definitely makes sense. Added to `maintenance` via the above commit, soon `devel`, will be released with 1.3.7.
