### ISSUE TITLE
[Request] Real time update functionality for gcode commands

### ISSUE THREAD

**Issue by markwain** [foosel/OctoPrint#2377]
Hello!
Thanks for your work first! You are doing amazing product :)

It would be great to have the possibility of adding some gcode command that can run repeatedly(like temperature update ) in order to get continuous updates from the printer for example for current position. Is that possible?
If it is - just point me in the right direction - I can write a realization/plugin. 

Thanks.

**Comment by foosel** [comment]
You probably want to [build a plugin](http://docs.octoprint.org/en/master/plugins/gettingstarted.html) utilizing a [`RepeatedTimer`](http://docs.octoprint.org/en/master/modules/util.html#octoprint.util.RepeatedTimer) to [send commands](http://docs.octoprint.org/en/master/modules/printer.html#octoprint.printer.PrinterInterface.commands) via [`self._printer`](http://docs.octoprint.org/en/master/plugins/injectedproperties.html).

**Comment by markwain** [comment]
Thanks!
