### ISSUE TITLE
[Request] Add PTZ support

### ISSUE THREAD

**Issue by networxnet** [foosel/OctoPrint#2390]
Please add PTZ support for webcam. Perfect would be if tilt could be set dependent to actual layer height.

For example Logitech's Orbit/Sphere AF would be a perfect cam. Cheap to get, 2MP, pan and tilt skills and an additional autofocus.

**Comment by wescrockett** [comment]
Check this: https://sourceforge.net/p/mjpg-streamer/discussion/739917/thread/b624f69c/

**Comment by ntoff** [comment]
The version of mjpeg streamer used by octopi is actually this one I believe https://github.com/jacksonliam/mjpg-streamer and not the version up on sourceforge

**Comment by foosel** [comment]
In any case, this is a duplicate of #1231.
