### ISSUE TITLE
Cannot Login to OctoPrint with new computer

### ISSUE THREAD

**Issue by dmathias1974** [foosel/OctoPrint#2434]
#### What were you doing?

1. ...Connected fine with laptop to my Octoprint as always.
2. ...Started using a new desktop computer on the same network and tried to login to Octoprint web page.
3. ...Username/password are accepted but will not log in.

#### What did you expect to happen? 
Login as usual.

#### What happened instead? 
No login accepted (with no message)

#### Did the same happen when running OctoPrint in safe mode? 
How do I do this?

#### Version of OctoPrint 
v1.3.6

#### Operating System running OctoPrint 
Windows Vista 64-bit

#### Printer model & used firmware incl. version 
Creality CR-10 (stock firmware)

#### Browser and Version of Browser, Operating System running Browser
Internet Explorer v11
Google Chrome v64

#### Link to octoprint.log
??

#### Link to contents of Javascript console in the browser
packed_libs.js?eebed41b:9176 POST http://10.0.1.53/api/login 500 (INTERNAL SERVER ERROR)

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Please provide _all_ requested information. Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by foosel** [comment]
Well, it's impossible to tell for certain since you still haven't provided the information necessary to analyse this, but if you had the Astroprint plugin install and disabled it, this would be an explanation. See #2442.

Closing this for now, feel free to request a reopen once you can provide all the requested information.
