### ISSUE TITLE
My new printer (FLSUN QQ) will not print from Octoprint unless in safe mode

### ISSUE THREAD

**Issue by Meridian64** [foosel/OctoPrint#2465]
----

#### What were you doing?

Octoprint connects to the printer but when I upload a gcode file and hit Print the heatbed will heat up and when it reaches the correct temperature the nozzle will not heat up and the heatbed temperature will drop again and nothing happens. 

Also I cannot upload the file to sd card as I used to with my previous  printed. ( I cannot access the sd card at all through Octoprint)

If I manually copy the same file to sd card and transfer it to printer the files prints without problem

#### Did the same happen when running OctoPrint in safe mode?

In safe mode it will start printing but after a few minutes it will stop.

#### Version of OctoPrint

OctoPrint 1.3.6 running on OctoPi 0.14.0 

#### Operating System running OctoPrint

Windows 10

#### Printer model & used firmware incl. version

FLSUN QQ

#### Browser and Version of Browser, Operating System running Browser

Firefox 58.0.2 64bit

#### Link to octoprint.log

https://www.dropbox.com/s/a9eo6qn9l2ldyxl/octoprint.log?dl=0

#### Link to contents of terminal tab or serial.log

https://gist.github.com/foosel/a5e2e775ba03bb269fc520713a6ea805

#### Link to contents of Javascript console in the browser

https://gist.github.com/Meridian64/37f20c96098e8aa5554abf48901b4d51

#### Screenshot(s)/video(s) showing the problem:

Not Applicable

*edit by @foosel* Made terminal tab output readable

**Comment by foosel** [comment]
Please provide _all_ requested information. Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by kantlivelong** [comment]
To add onto that. The octoprint.log appears to be funky version of a serial(or terminal?) log. Please correct this.

**Comment by Meridian64** [comment]
Working on it now….

**Comment by foosel** [comment]
@Meridian64 The serial output you provided is a bit... limited. There's basically nothing in there except two state changes and a ton of temperature responses from your firmware. It doesn't even show your issue.

Please enable safe mode, then [enable `serial.log`](https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299), connect to your printer, reproduce the problem and provide the resulting `serial.log`.

**Comment by foosel** [comment]
Closing due to lack of response.
