### ISSUE TITLE
Behaviour of error handling is not set on maintenance branch

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#2472]
#### What were you doing?

Seeing what's new in maintenance branch

#### What did you expect to happen?

Serial error handling should be set to one of 3 radio boxes

#### What happened instead?

Nothing is set
![image](https://user-images.githubusercontent.com/9030085/37211182-d9d5d59e-23f6-11e8-9b88-0757381c7468.png)

#### Did the same happen when running OctoPrint in safe mode?

yes

![image](https://user-images.githubusercontent.com/9030085/37211223-fa051c3a-23f6-11e8-8de2-e1cfbc7c950b.png)

#### Version of OctoPrint

OctoPrint 1.3.7.dev132+g4c3e44d

#### Operating System running OctoPrint

linux mint

#### Printer model & used firmware incl. version

virtual

#### Browser and Version of Browser, Operating System running Browser

google chrome

#### Link to octoprint.log

https://gist.github.com/ntoff/80b2e0d13f719794fe96d891b9e57f48

seems to be quite a few errors if you don't configure cura, that can be an issue ticket for another day

#### Link to contents of terminal tab or serial.log

not a serial issue

#### Link to contents of Javascript console in the browser

the errors seem to be related to not having cura set up

![image](https://user-images.githubusercontent.com/9030085/37211807-dd2dabd4-23f8-11e8-860e-8bd01ada9d11.png)

#### Further notes

Adding this to config.yaml seems to be the source of the issue:

    serial:
      autoconnect: true
      baudrate: 115200
      disconnectOnErrors: false
      port: VIRTUAL

I believe the ``disconnectOnErrors: false`` is the cause (and the default value of true DOES set something in the disconnect behaviour radio boxes)

I have read the FAQ.

**Comment by foosel** [comment]
Hah, thanks. Found and fixed!
