### ISSUE TITLE
Custom controls broken by 88b622e28291f1ee11a1433dbaef1dbd405e03f8

### ISSUE THREAD

**Issue by kantlivelong** [foosel/OctoPrint#2489]
#### What did you expect to happen?
Custom controls to display in the UI

NOTE: Controls display properly in the custom controls editor plugin

#### What happened instead?
Most are missing

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
maintenance / ccbe9311d7e57959d50c6be0342f46e78f941b4f

#### Operating System running OctoPrint

OctoPi 0.13.0

#### Printer model & used firmware incl. version

N/A

#### Browser and version of browser, operating system running browser

Chromium | 64.0.3282.167 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

#### Link to octoprint.log

http://paste.debian.net/1015394/

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

https://paste.debian.net/1015395/

#### Screenshot(s)/video(s) showing the problem:

https://i.imgur.com/rPEodih.png
https://i.imgur.com/V3A7eqf.png

### Additional Notes
9a8b8d86d5ed6dd2d59a5794947af1887f0fb730 works fine
88b622e28291f1ee11a1433dbaef1dbd405e03f8 broken

I have read the FAQ.

**Comment by foosel** [comment]
Thanks for reporting this. I only had `command` type controls configured during development and hence didn't notice this since it only triggered on `commands` and `script` type controls. Now fixed.
