### ISSUE TITLE
Smoothie SD Support

### ISSUE THREAD

**Issue by TopherMan** [foosel/OctoPrint#250]
I'm messing around trying to get this working for myself, but I know almost no Python, and even less Javascript, so I'm basically bashing my head against the wall. Smoothie is an ARM firmware that's quite nice to use, and has SD support, but it works a little differently than other firmwares. It shows up as a USB Mass Storage device, so files are added with drag and drop rather than the streaming nonsense. I've made control buttons to do the following, but it would be nice to be fully supported.

Basically, the changes I propose are this: first, add a "Smoothie SD" option. Then if this is true, either "Upload to SD" transfers the files to an SD folder specified in options, or specify the SD folder as the normal upload folder and have Print send M24.

The following M-codes were added today, and seem to be most of the codes used by OctoPrint for sd printing: M20, M23, M24, M25, M27, M32 (which is select and print).

Oh, and M27 returns a slightly different format:

```
21 % complete, elapsed time: 303 s, est time: 1110 s
```

**Comment by foosel** [comment]
@TopherMan is this still relevant?

**Comment by foosel** [comment]
Apparently not.
