### ISSUE TITLE
How to upgrade ?

### ISSUE THREAD

**Issue by davidmarli** [foosel/OctoPrint#2515]
Hi,

I installed octoprint v1.3.5
In the interface a message show me that 1.3.6 and 1.3.7 are avaible (for a while) but I can't update with the interface (it says update not poissible)

I can I upgrade with commandline by putty ?

Thank you.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
