### ISSUE TITLE
Cannot negotiate baud rate connecting to Prusa i3 MK3

### ISSUE THREAD

**Issue by purist69** [foosel/OctoPrint#2517]
What were you doing?
Trying tonnect OctoPrint server to Prusa i3 MK3 via USB

Ideally provide exact steps to follow in order to reproduce your problem:
1. Connect USB from Server to Printer
2. Set Port and Speed to AUTO OR manually configure to specific Port/Speed
3. Click Connect

What did you expect to happen?
OctoPrint to negotiate speed and connect

What happened instead?
Unable to negotiate speed

Did the same happen when running OctoPrint in safe mode?
Yes

Version of OctoPrint
Happens with 1.36-1.37RC2

Operating System running OctoPrint
DietPi

Printer model & used firmware incl. version
Prusa i3 MK3 FW 3.1.3

Browser and version of browser, operating system running browser
Chrome 65, 64bit
Link to octoprint.log

https://gist.github.com/foosel/b369299ab9297a84e9c6b2cddaf9ffd2#file-octoprint-log

Link to contents of Javascript console in the browser
Unsure how

Link to Serial.log

https://gist.github.com/foosel/b369299ab9297a84e9c6b2cddaf9ffd2#file-serial-log

Link to Screenshot
![image](https://user-images.githubusercontent.com/34849863/37878959-4f089c4a-3025-11e8-9488-2ec28a158c37.png)

I have read the FAQ.

*edit by @foosel* Extracted logs into gists to improve readability.

**Comment by foosel** [comment]
The controller appears to be sensitive to baudrate detection starting less than a second after initial connect (at least that's what I saw in my tests against a MK3 just now). Introducing a delay there solves the issue. Solved on `maintenance`, will be released with 1.3.8 (this report sadly came about a week too late for the fix to still make it into 1.3.7).

**Comment by purist69** [comment]
Thank you for investigating this.  Could you please let me know when 1.3.8 is expected to be released?

**Comment by foosel** [comment]
Subscribe to blog, twitter, facebook, g+, whatever works best for you. I always post announcements there for new release candidates. 

1.3.8 will take at least two months though. As I said, I *just* froze 1.3.7 for release last week, and in order to give me some chance to work on 1.4.0 I no longer do a monthly cycle for maintenance releases (the exception being really really breaking issues, which this certainly is not considering that you can just manually select the baudrate to connect).

**Comment by foosel** [comment]
Quick update on this: fix will be released with OctoPrint **1.3.9**, 1.3.8 was just turned into a hotfix release.
