### ISSUE TITLE
Plugin Manager: Greyed delete icon remains clickable on broken plugin

### ISSUE THREAD

**Issue by ntoff** [foosel/OctoPrint#2549]
#### What were you doing?

Trying to remove a broken plugin that results in the little delete icon being greyed out and a padlock symbol appearing in OctoPrint's plugin manager

![image](https://user-images.githubusercontent.com/9030085/38306485-0a8ae0be-3854-11e8-8462-9308f25dcb96.png)

#### What did you expect to happen?

Absolutely nothing because the delete icon is greyed out and I would assume is disabled in line with all the other greyed out and disabled delete icons. I would expect OctoPrint to ignore any clicking on that little icon.

#### What happened instead?

Delete icon remains clickable even though it's greyed, and OctoPrint still attempts (and fails) to uninstall the plugin.

#### Did the same happen when running OctoPrint in safe mode?

Yes (although I thought plugin management was disabled in safe mode?)

![image](https://user-images.githubusercontent.com/9030085/38306219-310ac0c0-3853-11e8-866d-5b0d6e941679.png)

#### Version of OctoPrint

1.3.7rc4

#### Operating System running OctoPrint

Linux Mint 18.2

#### Printer model & used firmware incl. version

virtual printer

#### Browser and version of browser, operating system running browser

![image](https://user-images.githubusercontent.com/9030085/38306361-b09e8452-3853-11e8-8405-1e5b5ede9510.png)

#### Link to octoprint.log

https://gist.github.com/ntoff/b1ebbaea5602c2b635ff55cbb5b781a6

#### Link to contents of terminal tab or serial.log

not serial related

#### Link to contents of Javascript console in the browser

![image](https://user-images.githubusercontent.com/9030085/38306543-3eea46ba-3854-11e8-8da9-ad8b7948fe2a.png)

although  I'm pretty sure the forbidden thing is the fact the plugin is broke

#### Screenshot(s)/video(s) showing the problem:

See 2nd screenshot

#### Other Notes:

Obviously the plugin not uninstalling isn't the main subject of this issue, it's broken, I broke it, it's what I do. The issue at hand is that the delete icon appears to be disabled as if to say "hey, I don't know how to uninstall this, I haven't got write permission here" and yet remains a clickable icon.

Also, I'm not entirely sure *how* I broke the plugin. It's still there, mocking me, taunting me. But that's my issue to deal with. But if you need any extra commands run, let me know.

edit: If it helps any

![image](https://user-images.githubusercontent.com/9030085/38307365-daa4e57c-3856-11e8-9ffe-da9dd9ae94ce.png)

The plugin egg is all sorts of broke, not sure if that helps you  somehow replicate this (or is an easy enough fix without replication).

I have read the FAQ.

**Comment by ntoff** [comment]
Changing line 590 of pluginmanager.js https://github.com/foosel/OctoPrint/blob/1.3.7rc4/src/octoprint/plugins/pluginmanager/static/js/pluginmanager.js#L590

from enableManagement to enableUninstall seeeeeems to have fixed it

    if (!self.enableUninstall(data)) {
        return;
    }

seems to fix it without any negative effects. Still can't uninstall plugins while printing (normal), and you're no longer able to click the button in safe mode (also I assume normal). More testing required though, just to be sure.

**Comment by ntoff** [comment]
Ok, to clarify, you **can't** click the *broken* plugin delete button in safe mode, you **can** still uninstall *normal* plugins while in safe mode.

**Comment by ntoff** [comment]
The other "issue" persists even on a version that I'm pretty sure I haven't been at yet (had to restore my VM from a backup that was made pre-plugin manager knob twizzling). So looks like this fix doesn't really break anything that I'm aware of and the other thing is unrelated to my tweaking.

The other issue is that while in safe mode, uninstalling a plugin does *not* turn the delete icon grey, even though the uninstall was successful. The icon also remains clickable even after the plugin was uninstalled, and then obviously will present an error. So in summary: While in safe mode, no visual indication a plugin was uninstalled is present apart from the auto closing green "uninstall successful" popup

![image](https://user-images.githubusercontent.com/9030085/38452378-c3b21f74-3a86-11e8-9865-fe386b299337.png)

Not even the typical reload needed icon

**Comment by foosel** [comment]
The other issue should now be fixed. That was a general problem with detecting the uninstall of disabled plugins. Good find!
