### ISSUE TITLE
Hi there i am trying to print from S3D through octoprint on my trinus. after slicing the file send over to the printer the hot end heats up and the bed also but after running to temp the hot ens and bed turn off but the print keeps running but with out extruding as the temp is to cold

### ISSUE THREAD

**Issue by sno8oy** [foosel/OctoPrint#2562]
#### What were you doing?

printing a file sliced in s3d and sent auto to the kodama trinus

Ideally provide exact steps to follow in order to reproduce your problem:
-->

1. ...slice print in s3d
2. ...save and have auto send to printer
3. ...hot end and bed heat up, print starts then temps for both hot end and bed turn off

#### What did you expect to happen?
the temp to be maintained at the set point in the gcode
#### What happened instead?
once hitting set point the temp set points changed to off
#### Did the same happen when running OctoPrint in safe mode?
yes the same thing happened

#### Version of OctoPrint
Version 1.3.6

#### Operating System running OctoPrint
windows 10

#### Printer model & used firmware incl. version
Kodama trinus

#### Browser and version of browser, operating system running browser
internet explorer 11

#### Screenshot(s)/video(s) showing the problem:

![capture](https://user-images.githubusercontent.com/38203185/38483952-45e0ec4e-3bc4-11e8-9f9d-8c1b43c5e917.JPG)

I have read the FAQ.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
