### ISSUE TITLE
Prusa i3 MK3 - Stuck on "Canceling" after resetting w/ button

### ISSUE THREAD

**Issue by BattlePizza** [foosel/OctoPrint#2578]
Hi, before upgrading to 1.3.7 I would often simply cancel prints that looked wrong by pressing the reset button. Octoprint will ask me if I resetted the printer intentionally, and everything works fine. After updating to 1.3.7, however, whenever I press the reset button on my printer the status on Octoprint will be stuck on "canceling" until I manually disconnect and reconnect the printer from Octoprint. Is anyone else experiencing a similar issue?

Raspberry Pi 3 Model B, Octopi

**Comment by foosel** [comment]
That's a known issue, see #2509. Closing this since it's a duplicate :)
