### ISSUE TITLE
Bl touch alarm closes conection

### ISSUE THREAD

**Issue by vMeph** [foosel/OctoPrint#2582]
#### What were you doing?
bl touch autolevel Mesh

1. ... G28
2. .. G29 P1 start autolevel
3. ...

#### What did you expect to happen?
expect to do autolevel and if the probe and if fail do a reset on the bl touch
#### What happened instead?
the bl touch  when it does a alarm will close conection, and im not able to reset alarm
#### Version of OctoPrint
version 1.3.8

#### Operating System running OctoPrint
windows 10

#### Printer model & used firmware incl. version
marlin bugfix 2.x.x

#### Browser and version of browser, operating system running browser
chrome

#### Link to contents of terminal tab or serial.log

Recv: echo:busy: processing
Recv:  T:17.81 /0.00 B:18.01 /0.00 @:0 B@:0
Recv: Error:STOP called because of BLTouch error - restart with M999
Changing monitoring state from "Operational" to "Error: STOP called because of BLTouch error - restart with M999"
Changing monitoring state from "Error: STOP called because of BLTouch error - restart with M999" to "Offline (Error: STOP called because of BLTouch error - restart with M999)"
Connection closed, closing down monitor
#### Screenshot(s)/video(s) showing the problem:
![1](https://user-images.githubusercontent.com/12812111/38766288-94e3c83c-3fc7-11e8-9ed3-b234b9f637e3.jpg)

I have read the FAQ.

**Comment by Grogyan** [comment]
This is a problem with your printer control board not being able to supply
enough current, which causes the CPU to go into brown out and restarts

**Comment by vMeph** [comment]
thanks
