### ISSUE TITLE
1.3 version do not let raise in Z axis

### ISSUE THREAD

**Issue by CreativeBR** [foosel/OctoPrint#2608]
Hi. After the 1.3 update of this plugin my printer do not respond to G1 commands to raise in the Z axis. I can move the Z down but not up. 

The move commands in the LCD menu is working ok in all axis.

If i disable the plugin all the Z movements return.

Generic Prusa i3 with Marlin 1.18 and octoprint 1.3.8

{}s
CreativeBR

#### What were you doing?

1. ...
2. ...
3. ...

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by ntoff** [comment]
Please fill out the ticket in its entirety, including *all* the requested logs.

>If i disable the plugin all the Z movements return.

Which plugin? If disabling a plugin fixes your issue, then your issue isn't with OctoPrint and you should contact the author of whichever plugin causes your issue.

**Comment by foosel** [comment]
> After the 1.3 update of this plugin
> [...]
> If i disable the plugin all the Z movements return.

Sounds like you are having an issue with a third party plugin and not OctoPrint. Report this in the plugin's bug tracker instead of here. If that's not the case, fill out the *full ticket template* and request a reopen.

**Comment by leftside2** [comment]
I have the same problem after installing DisplayLayerProgress plugin on 1.3.8. 
Once the plugin removed, everything works fine. 
My symptom was z up never worked in octoprint web UI as well as in .gcode start gcode, but in printer interface panel.
