### ISSUE TITLE
Error when trying to print in maintenance branch

### ISSUE THREAD

**Issue by hashashin** [foosel/OctoPrint#2610]
#### What were you doing?

Upload gcode file and click print or upload via api with print after option.

#### What did you expect to happen?
Octoprint starting the print job.

#### What happened instead?
Octoprint error: AttributeError: 'Printer' object has no attribute '_setPrintingUser'
Related to #2576 I bet

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
1.3.9.dev131+gbe4b98b9

#### Operating System running OctoPrint
Armbian 5.43.180423

#### Printer model & used firmware incl. version

Anet A8, Repetier 1.0.1

#### Browser and version of browser, operating system running browser
Chrome: version 65.0.3325.181 (Build oficial) (32 bits)
Windows 10 1709

#### Link to octoprint.log

https://gist.github.com/hashashin/92b38bef79c5c0219a1ade103a8ecded

#### Link to contents of terminal tab or serial.log
Not relevant as nothing it's send to the printer.

#### Link to contents of Javascript console in the browser
https://gist.github.com/hashashin/ff4f8bc7cd4d8228a5b42222e31510d8

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

Thanks, salud.

**Comment by foosel** [comment]
This should be fixed by the above commit.
