### ISSUE TITLE
Camera stream stops working after first print since boot

### ISSUE THREAD

**Issue by nbasse** [foosel/OctoPrint#2622]
#### What were you doing?

I have recently (a few months ago) replaced my old raspberry pi 1 with a new Rpi3. I started fresh with the latest version of octopi and doing all the setup from the beginning. I did copy over some of my old gcode files and statistics files for octoprint to the new system, but everything else was new.
The camera stream works when the pi is freshly rebooted.

1. Starting any print as usual through octoprint on chrome on windows 10.
2. ...
3. ...

#### What did you expect to happen?
The camera stream (from  a Raspberry Pi Camera Module v2) under the control tab in octoprint works fine before starting any prints.

#### What happened instead?
The camera stream stops working when a print is started from octoprint and the stream window gets black with the text "Webcam steam loading..."
After rebooting the RPi the stream works again until the next print is started. 

#### Did the same happen when running OctoPrint in safe mode?
Yes.

#### Version of OctoPrint
1.3.8 

#### Operating System running OctoPrint
OctoPi 0.14.0

#### Printer model & used firmware incl. version
Rigidbot Big, original firmware v1.1 (2014-08-11)

#### Browser and version of browser, operating system running browser
Chrome, Version 65.0.3325.181 (Officiell version) (64 bitar)
Windows 10 Home

#### Link to octoprint.log
https://pastebin.com/VrEpviHe

#### Link to contents of Javascript console in the browser
https://pastebin.com/5ya9cwrC

#### Screenshot(s)/video(s) showing the problem:
https://photos.app.goo.gl/uUBC5jcbygzwQ7yF9

I have read the FAQ.

**Comment by foosel** [comment]
OctoPrint is merely embedding a camera stream provided by a webcam server outside of the control of OctoPrint. So this sounds more like either a problem with your webcam or `mjpg-streamer`. Best get in touch about this on the [community forum](https://discourse.octoprint.org). This tracker is reserved for bugs and feature request for OctoPrint proper, not any third party software (or hardware) used in conjunction with it.
