### ISSUE TITLE
[Request] how about new streamer?

### ISSUE THREAD

**Issue by Vexatuspl** [foosel/OctoPrint#2623]
Hi,

As you know a lot of people are having issues with making the mjpg-streamer work and as a matter of fact the project has been already abandoned.
Have you been thinking about moving to a different piece of software? I've heard some good opinions about motion for example. 

Best regards
Greg

**Comment by foosel** [comment]
`mjpg-streamer` isn't a part of OctoPrint, so this is the wrong tracker. I suggest to take this over to either the [OctoPi tracker](https://github.com/guysoft/OctoPi) or better yet the [community forum](https://discourse.octoprint.org).
