### ISSUE TITLE
Logging option not saving

### ISSUE THREAD

**Issue by jneilliii** [foosel/OctoPrint#2628]
#### What were you doing?

When saving logging options using `octoprint.util.comm.command_phases` as the selection, after save and restart of OctoPrint, the option reverts to just `octoprint`.

1. Open settings.
2. Click Logging on the left.
3. Press the add button.
4. Choose the option `octoprint.util.comm.command_phases`.
5. Save
6. Restart OctoPrint
7. Reload is triggered.
8. After reload go to settings.
9. Click Logging on the left.
10. Notice `octoprint.util.comm.command_phases` has been converted to `octoprint`.

From my testing it seems that the specific option `octoprint.util.comm.command_phases` is only available if a printer is connected, so I suspect that the setting is getting wiped out due to the printer not being connected during a restart and therefore is not in the list to bind to during startup.

#### What did you expect to happen?

Expected for the setting to remain as saved.

#### What happened instead?

Setting was changed to something other than that selected.

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

OctoPrint 1.3.8

#### Operating System running OctoPrint

OctoPi 0.14.0

#### Printer model & used firmware incl. version

Customized Creality CR-10 running Marlin 1.1.8 on Einsy RAMBo board.

#### Browser and version of browser, operating system running browser

Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

#### Link to octoprint.log

[octoprint (28).log](https://github.com/foosel/OctoPrint/files/1976384/octoprint.28.log)

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

No errors listed whatsoever, and console gets cleared upon reload.

#### Screenshot(s)/video(s) showing the problem:

During Save
![capturesaving](https://user-images.githubusercontent.com/5249455/39660326-635faf1c-500a-11e8-9c1f-b9721e739d62.PNG)

After Save and restart
![captureaftersaveandrestart](https://user-images.githubusercontent.com/5249455/39660328-7414752c-500a-11e8-92c7-f9faa605fb5f.PNG)

I have read the FAQ.

**Comment by foosel** [comment]
You are doing this the wrong way around ;)

Select what you want to add, *then* press the add button:

![add_logging](https://user-images.githubusercontent.com/83657/39662954-8e559474-506a-11e8-880b-4747f3d55bcf.gif)

and it will persist just fine.

**Comment by jneilliii** [comment]
Thanks @foosel, that was what I was missing.  Maybe because I was only adding one I was confused by the interface.  Maybe persist the add row at the top of the list instead of the bottom  and add a dividing element between the data and the header/add row might help with the confusion.  Something like this.

![image](https://user-images.githubusercontent.com/5249455/39669145-85bdf2ce-50b1-11e8-841f-59f170f0e6f2.png)

**Comment by ntoff** [comment]
ok, maybe there needs to be an inline help there then because I've seen some things do it the other way, where you press add then select / enter the info. My router pages is one of those things. You press "add new..." and then enter the information.
