### ISSUE TITLE
Frequent failure of prints longer than ~4 or 5 hours on Lulzbot TAZ 6

### ISSUE THREAD

**Issue by cmadson** [foosel/OctoPrint#2640]
#### What were you doing?

Printing via the Octoprint 1.3.8 webgui

Loaded files via web gui to RaspPi internal storage
Started printing
Wait for print to fail mid print

#### What did you expect to happen?

The printer to to print the whole gcode file with a smiley face at the end

#### What happened instead?

The printer stopped printing mid print

#### Did the same happen when running OctoPrint in safe mode?

Haven't tried yet, after losing several large prints I have stopped using the RPi and have been printing via the SD card directly from the printer with no problems.

I'm afraid to try this in safe mode as i've wasted a few Kg of material already, but will try if it helps.  

Nervousness and trepidation and money

#### Version of OctoPrint

1.3.8

#### Operating System running OctoPrint
OctoPi 0.14.0

#### Printer model & used firmware incl. version
Lulzbot TAZ6

#### Browser and version of browser, operating system running browser
Safari Version 11.1 (13605.1.33.1.2) 
The problem has occurred across MacOS 10.13.3 and 10.13.4

#### Link to octoprint.log
https://pastebin.com/mrhSJkLL

#### Link to contents of terminal tab or serial.log
https://pastebin.com/rGCL6QLq

#### Link to contents of Javascript console in the browser
Didn't capture

#### Screenshot(s)/video(s) showing the problem:
https://www.dropbox.com/s/xnxgl79g74ejc88/Screen%20Shot%202018-04-18%20at%206.30.32%20AM.png?dl=0

I have read the FAQ.

**Comment by foosel** [comment]
Based on the logs you provided, your printer stops responding to a simple temperature query. There's not much that OctoPrint can do about that, if your printer doesn't respond it can't drive a print to it.

However your logs show a successfully completed print with the mentioned issue arising only 20min after the print ends. I don't see anything related to a failure *during* a print in your logs. I'd need a reproduction of the actual problem you are reporting here (failure *during* a print) with enabled `serial.log` to look further into this.

**Comment by foosel** [comment]
@cmadson are you looking into providing a `serial.log`?

**Comment by foosel** [comment]
Closing due to lack of response.
