### ISSUE TITLE
[Request] Brim for supports only

### ISSUE THREAD

**Issue by slikk66** [foosel/OctoPrint#2646]
Often times I have a model I'd like to not print with a brim on it, but then there are teeny tiny support structures (<3mm round for example) that never stick unless I add brim to the entire print.  Is a "brim for support only" option possible?

**Comment by ntoff** [comment]
That's a job for your slicer, OctoPrint only provides a way to utilise the cura slicer (and a super old version at that), there's no real way for OctoPrint to control the slicer's behaviour. There are 3rd party  plugins that give more control, and access to other slicers, but again they only provide a way to change settings in the slicer, not dictate how it does its thing.

tl;dr: Not something OctoPrint has any control over

**Comment by slikk66** [comment]
sorry, im an idiot.. posted in the wrong hub.
