### ISSUE TITLE
Motor movement failiure with OctoPrint 1.3.8

### ISSUE THREAD

**Issue by Zamundaaa** [foosel/OctoPrint#2653]
Sorry that some information is missing but I got the idea of filing this bug here just when I fixed it by downgrading to 1.3.6. I will append it once I try again with 1.3.8

#### Link to contents of terminal tab or serial.log: -

I have read the FAQ.

**Comment by foosel** [comment]
Please provide _all_ requested information. Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by Zamundaaa** [comment]
I will. Right now I have upgraded to a Raspberry PI 3B and am running into different problems there (that are most likely my fault). Once that's resolved I can test it again and provide the rest of the information

**Comment by Zamundaaa** [comment]
Sorry, I totally forgot about this. After I resolved new issues with my 3D printer and those with my raspberry pi I updated OctoPi once again and the issue never came up again (so it might have been an issue with OctoPi or my installation all the time)
