### ISSUE TITLE
Octoprint --- too many lines to buffer, cut off ---

### ISSUE THREAD

**Issue by yo8aiv** [foosel/OctoPrint#2659]
my latest issue **--- too many lines to buffer, cut off ---**

Print Failure Octoprint !!
what's the fix ?
- usbserial issue

using this to connect printer and webcam to orangepi 
https://sgcdn.startech.com/…/gallery_la…/ST4200MINI.Main.jpg
- probably i'll try to breakout at least one more usb port

UPDATE : 23may 
-changed usb cable between octoprint and AnetA8 board
- added 2 more usb ports (not using st4200) on the breakout pins of the orangepi zero - now webcam is stable timelapse works ok .. sometimes stream shutoff (guess it needs at least 2 threads)
-added user to dialout group and removed my little workaround (chmod 777 ttyUSB0) that seems to solved the problem - still testing ... 3h printing with no disconnection ..
--> almost failed the print because the filament got twisted and got stuck and the roll fell down from the support so extruder was running empty.. managed to save the print.
- so far im happy with it - i might save this as a backup image.🤔
- spoke too soon - --- too many lines to buffer, cut off --- .. after few minutes printing continues but seems octoprint is keeping processor high so the server isn't accesible 

adding post fromFB with the evollution [https://www.facebook.com/groups/1068531466501015/permalink/1829715380382616/?comment_id=1829717243715763](url)

**Comment by foosel** [comment]
This doesn't sound like a general issue with OctoPrint but more like a problem with your specific setup. Please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)

**Comment by yo8aiv** [comment]
thanks.
