### ISSUE TITLE
bug: Cannot start print from mobile chrome

### ISSUE THREAD

**Issue by TTGeek2** [foosel/OctoPrint#2671]
#### What were you doing?

1. Open up the website on mobile, chrome version 67.0.3396.68, android 8.0.0, SM-G930F build/R16NW (latest update on samsung s7, for me in sweden with danish phone)
2. Make sure you are logged in.
3. after printer connected, try to initiate a print with the printer icon in the file explorer, left side of screen. Nothing happends. I expected octoprint to 
4. cry a little as you realize you cant and then walk over to your PC to initiate the print. That worked. (chrome v66.0.3359.181).

#### What did you expect to happen?
Expected octoprint to start printing the file.

#### What happened instead?
nothing happened, except for the button animation that confirms i did klick the button.

#### Did the same happen when running OctoPrint in safe mode?
yes

#### Version of OctoPrint

OctoPrint 1.3.8

#### Operating System running OctoPrint
OctoPi 0.14.0

#### Printer model & used firmware incl. version
Prusa i3 mk2s

#### Browser and version of browser, operating system running browser
chrome version 67.0.3396.68, android 8.0.0, SM-G930F build/R16NW (latest update on samsung s7, for me in sweden with danish phone)

#### Link to contents of Javascript console in the browser
dont know how to do that on mobile.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Please provide _all_ requested information. Without that information this ticket cannot be looked into and will be closed. Thanks.

**Comment by TTGeek2** [comment]
It seems the issue has vanished. I have no idea what changed.
just a thought: Maybe include bug report functionality in octoprint, so the bug-report plugin could gather required logs automatically.
