### ISSUE TITLE
Error while installing OctoPrint in Windows 10

### ISSUE THREAD

**Issue by almaefogo** [foosel/OctoPrint#2685]
#### What were you doing?

1.Installing octoprint in windows

#### What did you expect to happen?
Install Octoprint
#### What happened instead?
I got a command error but with a unicodedecoder ascii error
link to cmd log here https://pastebin.com/icybaQ6M

#### Did the same happen when running OctoPrint in safe mode?
no
Cant install

#### Screenshot(s)/video(s) showing the problem:

 

I have read the FAQ.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
