### ISSUE TITLE
Request: Make "Print Time Left" / "Estimated Print Time" more accurate

### ISSUE THREAD

**Issue by davr** [foosel/OctoPrint#270]
Currently it appears to just guess how much time is left based on bytes of gcode? Which is wildly inaccurate unless you are printing an object that is very uniform in shape and print speed. Ideally it should scan through the gcode and estimate the amount of time all the moves would take, including taking into account acceleration and maximum speeds. Initially just have some default values hardcoded, later let people set their acceleration from their machine for more accurate estimates, and the final goal should be to have it query the firmware (Marlin at least supports this) to get the actual values.

**Comment by foosel** [comment]
The whole print time estimation has been changed completely in `devel`. OctoPrint now only display live-evaluations once they become stable, but uses analysis & slicing output as well as previous prints of the same file on the same printer if available.
