### ISSUE TITLE
[Request] Chamber temperature comming from printer

### ISSUE THREAD

**Issue by maukcc** [foosel/OctoPrint#2702]
Is there already something in place to read chamber temperature from a printer?
When you give a M105 command, the printer will give you hotend and bed temps. 
If there was also a cxxx info given, would octoprint recognize this, or will the whole line be dropped?
And can this info be added to the temp graph?

**Comment by foosel** [comment]
> If there was also a cxxx info given, would octoprint recognize this, or will the whole line be dropped?

Neither. The chamber temperature will just not be parsed, hotend and bed however will.

> And can this info be added to the temp graph?

That would be a duplicate of #321
