### ISSUE TITLE
Get request to Object stored on sdcard returns server error 500

### ISSUE THREAD

**Issue by mrnic3** [foosel/OctoPrint#2705]
#### What were you doing?

I tried to retrieve info about a file through the REST API which is stored on my sd card and uses an 8.3 filename.

Went to postman did a GET on http://192.168.178.171:5000/api/files/sdcard/flanec%7E1.gco

#### What did you expect to happen?

Retrieve JSON about the object like this:
{
    "date": 1500384992,
    "display": "cableorganizer.gcode",
    "gcodeAnalysis": {
        "dimensions": {
            "depth": 186.75,
            "height": 14,
            "width": 191.75
        }

#### What happened instead?

<title>500 Internal Server Error</title>

    raise NoSuchStorage("No storage configured for destination {destination}".format(**locals()))
NoSuchStorage: No storage configured for destination sdcard

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

OctoPrint 1.3.8

#### Operating System running OctoPrint

Raspbian GNU/Linux 8 \n \l

#### Printer model & used firmware incl. version

ORIGINAL PRUSA I3 MK2/S MULTI MATERIAL 
FW 3.1 (i know i know)

#### Link to octoprint.log

https://pastebin.com/tGjrfWuw

I have read the FAQ.

**Comment by foosel** [comment]
Fixed by the above commit, already available on `maintenance`, soon `devel` and to be released with 1.3.10.
