### ISSUE TITLE
Autoscroll in terminal tab not working

### ISSUE THREAD

**Issue by Ellmen** [foosel/OctoPrint#2716]
Currently you have to specifically click autoscroll to get a continuous feed from the terminal tab. It strikes me that this would be the expected default behaviour. Also, when the browser window loses focus (i.e. switching tabs), autoscroll gets disabled again which is kind of annoying.

I have read the FAQ.

**Comment by ntoff** [comment]
Really? I'm pretty sure it's always auto scrolled  by  default for me, do you have the auto scroll plugin installed by any chance? The one that turns off auto scrolling if you manually scroll.

**Comment by foosel** [comment]
It's auto scrolling just fine here in Chrome (but on Windows, not OSX).

Please test if the issue persists in safe mode. If not it's one of your installed third party plugins that's causing problems. If yes fill out [the ticket template](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#what-should-i-include-in-a-bug-report) and ideally include a video that shows the wrong behaviour.

**Comment by foosel** [comment]
Closing due to lack of response. Feel free to request a reopen once the requested information is available.
