### ISSUE TITLE
[Request] Allow additional video formats to appear in the timelapse tab

### ISSUE THREAD

**Issue by FormerLurker** [foosel/OctoPrint#2729]
Is it possible to add support for the following formats within the timelapse file browser:
GIF
AVI
FLV
VOB
MPEG (might already work actually, need to test)

As you may have guessed, this is for Octolapse so that I can synchronize additional formats that are supported by the plugin.  Currently I can copy the files into the timelapse folder, but they will not display and I cannot download them with a direct link.

Thanks!

#### What were you doing?

1. ...
2. ...
3. ...

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by koenkooi** [comment]
I added some formats a while ago, have a look at https://github.com/foosel/OctoPrint/pull/2409 to see the work involved.

FWIW, 'vob' is currently the default format, but using the 'mpg' suffix.

**Comment by foosel** [comment]
I just added a new hook [`octoprint.timelapse.extensions`](http://docs.octoprint.org/en/maintenance/plugins/hooks.html#octoprint-timelapse-extensions) that can be used to add additional supported extensions.

Available on `maintenance`, soon `devel`, to be released with 1.3.10.

**Comment by FormerLurker** [comment]
@foosel,  the hook worked as expected, excellent!  👍  This is a pretty big upgrade for Octolapse since the other video formats were too much of a bother to use before.

I did have to remove the _sendingLock from the _handle_ok method to test it out, but I was expecting that.  Now to remove all of the warnings about which formats will sync from my settings and help files.

**Comment by foosel** [comment]
1.3.10 has been released.
