### ISSUE TITLE
Selected Printer port not kept between session

### ISSUE THREAD

**Issue by gege2b** [foosel/OctoPrint#2740]
Note : this is about [this issue](https://github.com/foosel/OctoPrint/issues/2736#issuecomment-405546014)

#### What were you doing?

I was using Virtual printer to test some stuffs

1. Go to octoprint UI and connect to the virtual printer (of course, virtual printer should be enabled first)
2. close and repoen the browser tab of octoprint (OR refresh the page)
4. The selected printer port is not the virtual printer but ```/dev/whatever``` (I think it revert to the default printer)

I cannot test with two real printers

#### What did you expect to happen?

The selected port to be kept

#### What happened instead?

The selected port switch to, I think, the one of the defaut printer
Manual commands are still sent to the vritual printer

It's not a killer bug, probably a JS thing

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.3.9rc3
Same on 1.4-dev
I think it's here since some time, but as I never used virtual printer until now, I didn't notice

#### Operating System running OctoPrint

raspbian strech 9.3 on rpi3

#### Printer model & used firmware incl. version

marlin 1.1.8

#### Browser and version of browser, operating system running browser

Firefox 61 on win10

#### Link to octoprint.log

[octoprint.log](https://framabin.org/p/?042d600ec6030812#4OnvCRsBCRRep7PXOUFj38usye4SvJZ7Jj194ij6IEI=)

#### Link to contents of terminal tab or serial.log

n/a

#### Link to contents of Javascript console in the browser

the copy/paste is a mess but there is neither errors nor warnings, only the usual stuffs

I have read the FAQ.

**Comment by foosel** [comment]
Should be fixed by the above commit (and was broken at least since 2013). Pushed to `maintenance`, soon `devel`, to be released with 1.3.10.
