### ISSUE TITLE
Triggering rpicam by a gcode

### ISSUE THREAD

**Issue by rafaa1988** [foosel/OctoPrint#2743]
#### What were you doing?

1. ...
2. ...
3. ...

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
?

**Comment by rafaa1988** [comment]
Sorry, I'm newbie. I simply want to let the picam capture image on z change and or on gcode in octoprint. I found in Octoprint timelapse recording or image capturing but this is not what i need. As an example the m300 works for sound. Is there a specific gcode for triggering the camera? and is z change implemented in octoprint. Thanks.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
