### ISSUE TITLE
triggering picam on gcode

### ISSUE THREAD

**Issue by rafaa1988** [foosel/OctoPrint#2744]
#### What were you doing?

I want to let the picam to capture images on z change and on special gcode line like the m300 for sound. I found only the timelapse capturing in octoprint. I ask if it's possible to capture images by z change and if there's a special gcode order (Msomething) to trigger the picam.

#### Version of OctoPrint
1.3.8
 

#### Operating System running OctoPrint
octoprint runs on raspbian stretch

#### Printer model & used firmware incl. version
repetier firmware

#### Browser and version of browser, operating system running browser
Chromium.

I have read the FAQ.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
