### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by RideOn123** [foosel/OctoPrint#2750]
#### What were you doing?
Finished a print yesterday. Today I started up Octoprint like everytime. Nothing special.

#### What did you expect to happen?
Octoprint starting like everytime.

#### What happened instead?
Got 500 Internal Server Error
#### Did the same happen when running OctoPrint in safe mode?
yes

#### Version of OctoPrint
1.3.8

#### Operating System running OctoPrint
Armbian

#### Printer model & used firmware incl. version
Anet A8, Marlin 1.1.8

#### Browser and version of browser, operating system running browser
Chrome 67.0.3396.99, Windows 10

#### Link to octoprint.log
https://pastebin.com/7Cdzpa5t

#### Link to contents of terminal tab or serial.log
https://pastebin.com/9ZSj0HTF

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
The log appears to be truncated. Please share a full log.

**Comment by foosel** [comment]
Closing due to lack of response.
