### ISSUE TITLE
Camera Control

### ISSUE THREAD

**Issue by IzakKrige** [foosel/OctoPrint#2755]
#### What were you doing?

1. ...
2. ...
3. ...

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by IzakKrige** [comment]
I have a Raspberry Pi3 with a Raspberry camera V2 running Octoprint as OS
I can see the video image from the camera on octoprint on my laptop under the control tab.
I have putty running on the laptop and can see the terminal window and input info and commands.
I have VNC running on Pi3 and laptop and can interact with the Pi3.

I want to be able to switch the camera on and off. What are the commands and on what system

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
