### ISSUE TITLE
keeping the jpg pictures in tmp folder after rendering

### ISSUE THREAD

**Issue by rafaa1988** [foosel/OctoPrint#2776]
#### What were you doing?
I just want to keep the jpg pictures in the /home/pi/.octoprint/timelapse/tmp

#### What did you expect to happen?
Keep the jpg pictures after rendering
#### What happened instead?
The jpg files are deleted after rendering

#### Version of OctoPrint
1.3.9

#### Operating System running OctoPrint
raspbian

#### Printer model & used firmware incl. version
repetier

#### Browser and version of browser, operating system running browser
google

I have read the FAQ.

**Comment by foosel** [comment]
This is intentional behaviour and not going to be changed in core OctoPrint.
