### ISSUE TITLE
[help] how to call confirm dialog from js

### ISSUE THREAD

**Issue by Alissonverd** [foosel/OctoPrint#2790]
Hello,

For a few days I've been trying to add a confirmation dialog to my plugin. But so far without success.
I need to call the confirmation dialog (from plugin js file) before executing a command/function, how I can do this?
If confirmed by user, I need call one function into js file.

The dialog:
![10dbef1e-1e1b-11e4-9fc8-b5b5abaab9ae](https://user-images.githubusercontent.com/35609430/43997180-f85767a2-9daa-11e8-87d8-b80adc12200b.png)

**Comment by ntoff** [comment]
For any and all help, please use the forum located at https://discourse.octoprint.org/

Thankyou.
