### ISSUE TITLE
[Request] Terminal "Suppress echo:busy: processing" option

### ISSUE THREAD

**Issue by AbuMaia** [foosel/OctoPrint#2821]
~~Could we get an option on the Terminal tab to suppress "echo:busy: processing" messages that pop up during a G29? Or perhaps a way to add filters on our own?~~ Explained below by ntoff. Thanks!
Another request I'd like to make is a way to change the default options on the Gcode Viewer tab. It seems every time I have to reload the page, I have to go back and reset the checkboxes to my preferences.

**Comment by ntoff** [comment]
There already is a way to add your own filters in the settings, I think under perhaps it's own category called terminal or terminal filters (can't check for sure right now). Also to take care of the remembrance of the checkboxes I believe there's a plugin for that (also can't check at the moment but may update later if you haven't found it).
