### ISSUE TITLE
File Manager Panel

### ISSUE THREAD

**Issue by savorywatt** [foosel/OctoPrint#284]
So I thought I'd open an issue for what I'm working on just to get some discussion here and on the G+ community as well. I've been thinking of building a re-usable visual component in Javascript and then integrating it into Octoprint.

The javascript side would be.
Backbone
JQuery
Underscore
Underscore templating.
The latest from https://github.com/hudbrog/gCodeViewer

The component would have a defined API REST schema that any server/web app could use.

/Folders/<id>
/Folder/<id>
/Folder/File/<id>/

Folders could be nested in other folders

/Folder/1234/Folder/1314/File/124123

This is the general layout. The file manager is on the left and the gCodeViewer is on the right but tweaked to allow you to actually edit the Gcode file rather than just view the lines.

![screenshot from 2013-10-20 23 36 16](https://f.cloud.github.com/assets/1856097/1369944/5cb9582c-3a0a-11e3-8b13-f13e7e75d0fe.png)

The UI would be built by following the tree of the end points and pulling out relevant information and then the actions would be triggered by hitting 

/Folder/12312/File/13123 HTTP PUT/UPDATE/DELETE
/Folder/12312/File/12312/Slice POST

**Comment by ZhuDaHai** [comment]
Just started using OctoPrint (and I love it), So this may be a stupid/already addressed request. But I think it would be really nice if there was support for folders/subsfolders in Pi. A real file manager: copy/paste/move/create/delete files and folders. 
Objects that I have and want to print many times often have multiple gcode parts and it would be nice to be able to organize and access them via folders on the OctoPrint Pi.
If this plugin already exists, then sorry for the redundancy. Please tell me where to find it, as I've looked in the plugins page of OctoPrint.org

**Comment by Salandora** [comment]
Well actually this is impöemented in the devel branch.
There is also a filemanager plugin in my repository which needs the devel branch to be used.

It is planned to be in stable with 1.3.0.

**Comment by foosel** [comment]
Filemanager plugin is released, 1.3.0 is released too, closing this.
