### ISSUE TITLE
babel_extract doesn't work unless messages.pot already exists

### ISSUE THREAD

**Issue by eyal0** [foosel/OctoPrint#2846]
#### What were you doing?

Running `python setup.py babel_extract` in my new plugin.

#### What did you expect to happen?

```
└──> octoprint dev plugin:new Test
plugin_package [octoprint_Test]: 
plugin_name [OctoPrint-Test]: 
repo_name [OctoPrint-Test]: 
full_name [You]: 
email [you@example.com]: 
github_username [you]: 
plugin_version [0.1.0]: 
plugin_description [TODO]: 
plugin_license [AGPLv3]: 
plugin_homepage [https://github.com/you/OctoPrint-Test]: 
plugin_source [https://github.com/you/OctoPrint-Test]: 
plugin_installurl [https://github.com/you/OctoPrint-Test/archive/master.zip]: 
└──> cd OctoPrint-Test 
└──> python setup.py babel_extract
Found packages: ['octoprint_Test']
running babel_extract
extracting messages from octoprint_Test/__init__.py
extracting messages from octoprint_Test/static/js/Test.js (extract_messages="gettext, ngettext")
writing PO template file to ./translations/messages.pot
```

#### What happened instead?

```
└──> octoprint dev plugin:new Test
plugin_package [octoprint_Test]: 
plugin_name [OctoPrint-Test]: 
repo_name [OctoPrint-Test]: 
full_name [You]: 
email [you@example.com]: 
github_username [you]: 
plugin_version [0.1.0]: 
plugin_description [TODO]: 
plugin_license [AGPLv3]: 
plugin_homepage [https://github.com/you/OctoPrint-Test]: 
plugin_source [https://github.com/you/OctoPrint-Test]: 
plugin_installurl [https://github.com/you/OctoPrint-Test/archive/master.zip]: 
└──> cd OctoPrint-Test 
└──> python setup.py babel_extract
Found packages: ['octoprint_Test']
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'babel_extract'
```

#### Did the same happen when running OctoPrint in safe mode?

I was not running the OctoPrint server.

#### Version of OctoPrint

git commit 1ccc1fa4

#### Operating System running OctoPrint

Linux

#### Printer model & used firmware incl. version

None

#### Browser and version of browser, operating system running browser

None

#### Link to octoprint.log

None

#### Link to contents of terminal tab or serial.log

None

#### Link to contents of Javascript console in the browser

None

#### Screenshot(s)/video(s) showing the problem:

Text above.

I have read the FAQ.

**Comment by ntoff** [comment]
This has nothing to do with octoprint, if you need help developing plugins then please use the forum located at https://discourse.octoprint.org/

**Comment by eyal0** [comment]
It is a bug in octoprint that babel_extract requires that messages.pot exist first.  Would you please look at the PR and reconsider?

**Comment by eyal0** [comment]
By the way, it's not octoprint for which I found the bug, it's the octoprint_setuptools.

**Comment by foosel** [comment]
Fixed by #2847 which was just merged to `maintenance`, soon `devel` and will be included in the 1.3.10 release.

**Comment by foosel** [comment]
> Maybe I am the only developer to have ever tried translating a plugin?

Sadly only all too possible ;)

**Comment by foosel** [comment]
1.3.10 has been released.
