### ISSUE TITLE
Autoscrolling with M105 and M27 hidden

### ISSUE THREAD

**Issue by tjhowse** [foosel/OctoPrint#286]
If autoscroll is enabled, along with M105 and M27 hiding enabled, the terminal still scrolls to the bottom when an M105 ack message is received, even if it's not displayed.

**Comment by foosel** [comment]
For some reason I forgot to reference this issue when I reworked the terminal tab a couple of weeks back...

Disabling Autoscroll now completely disables cutting off the lines (so you can have way more than 300 lines while that's disabled), filtering has been improved too and doesn't cause scrolling anymore. See e9623fdc36c658a5b8abe7769b1b308edfc3f424.

![image](https://cloud.githubusercontent.com/assets/83657/7482462/f09f001e-f377-11e4-86cf-ce565c766b44.png)
