### ISSUE TITLE
[1.3.10rc1] GCODE viewer not functioning due to 403 when trying to load the GCODE file

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#2873]
### Problem

As reported by @hashashin in https://github.com/foosel/OctoPrint/issues/2871#issuecomment-436234068:

>Hi @foosel, seems like there's a problem with the gcode viewer in this version:
2018-11-06 13:19:26,075 - tornado.access - WARNING - 403 GET /downloads/files/local/honor7A.gcode (2a01:c50e:221e:7d00:90e5:9d8e:5a18:154e) 13.35ms
This happens with any file, reverting to 1.3.9 make it work again.
Salud.

**Comment by foosel** [comment]
Fixed by the above commit, will be part of 1.3.10rc2

**Comment by ChrisHeerschap** [comment]
Ah, looks like this is what I was running into. Will confirm with RC2.

**Comment by foosel** [comment]
1.3.10rc2 was just released.

**Comment by ChrisHeerschap** [comment]
Glorious! So nice to have the GCode viewer back, thank you!!
