### ISSUE TITLE
[1.3.10] SVG Favicon doesn't show in Firefox

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#2879]
### Problem 

Firefox doesn't show the new SVG Favicon:

![image](https://user-images.githubusercontent.com/83657/48194572-af6ddd80-e34d-11e8-9121-656dae6bbd85.png)

~~According to [this comment](https://github.com/foosel/OctoPrint/issues/2871#issuecomment-436944080) and [this link](https://caniuse.com/#feat=link-icon-svg) this seems to be due to the used mime type.~~ Doesn't seem to be the mime type, that's already set to `image/svg+xml`.

**Comment by foosel** [comment]
Correct mime type *is* already set, favicon still doesn't show up. Investigating...

**Comment by foosel** [comment]
Fixed by the above commit. The issue was actually that [drawing a SVG to a canvas used internally fails silently in Firefox if the SVG doesn't have width and height attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=700533). Simply adding those solved the issue immediately.

Pushed and ready for 1.3.10rc2

**Comment by ThaliaFromPrussia** [comment]
Thank you!

**Comment by foosel** [comment]
1.3.10rc2 was just released.
