### ISSUE TITLE
[Request] Confirmation dialog when removing a plugin

### ISSUE THREAD

**Issue by yet-another-average-joe** [foosel/OctoPrint#2896]
Hello, and thanks for this great piece of software !

A confirmation dialog box would be usefull when deleting or even deactivating a plugin.

**Comment by ntoff** [comment]
Removing one I can see a confirmation being handy, but do you really need one when de-activating? I'm pretty sure there are warnings when you try to disable one of the system critical plugins, but as far as disabling 3rd party plugins, if you accidentally disable one you don't want to disable, just re-enable it.

Also if you're removing multiple plugins, a dialog for each would be super annoying so some way to suppress it, or even select multiple plugins for mass removal, would need to be thought up first.

**Comment by ntoff** [comment]
Then perhaps you should post an issue to that plugin's github page, to see if the issue can be fixed.

**Comment by yet-another-average-joe** [comment]
Yes, I did it already. It is TouchUI. I found a solution that works, at least for me.

A question : could a plugin display its own warning dialog box when the user flips the activation switch, or hits the delete button ? Can a plugin do something, or is it completely passive ? I searched the OctoPrint Wiki for some sort of deactivate/uninstall event that a plugin could handle, but I found nothing...

**Comment by dovecode** [comment]
I think we can close this issue now that the changes are in `maintenance`, right (cf. 79558fd)?

**Comment by foosel** [comment]
Actually, I'll mark it as solved and close it once 1.3.12 (the release that includes that change) is released.

**Comment by dovecode** [comment]
Ah, ok. That makes sense. Thanks.

**Comment by foosel** [comment]
1.3.12 has been released.

**Comment by yet-another-average-joe** [comment]
Thanks for this enhancement !
