### ISSUE TITLE
Action buttons of announcement plugin can become inaccessible on small resolutions.

### ISSUE THREAD

**Issue by tonymaglioni** [foosel/OctoPrint#2959]
#### What were you doing?

I recently updated octoprint to 1.3.10. After opening for the first time after update, there was a big yellow sticky note labeled "Release Announcements" the highlighted the new features. I cannot click anywhere to make it go away. Scrolling does not affect the sticky note. Maximizing and minimizing the window does not fix it. Restarting pc does not fix it. Reproduced on several web browsers.

#### Operating System running OctoPrint 

windows 7 pro

#### Printer model & used firmware incl. version

Ender 3

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by tonymaglioni** [comment]
![release announcements](https://user-images.githubusercontent.com/45924082/50059405-fc628200-014b-11e9-8354-f5944064d55d.png)

**Comment by foosel** [comment]
That isn't a new feature introduced with 1.3.10, for some reason (network outage?) your OctoPrint instance wasn't able to fetch announcements for a long while.

Your screen resolution of 1024x768 is as bit on the small side these days, and I simply didn't anticipate that here - the action buttons for the notication are at its bottom. I'll look into fixing that in 1.3.11. Until then I suggest to access OctoPrint from a PC with a higher resolution and close the notification there.

**Comment by foosel** [comment]
Solved by the above commit that adds a `max-height` to all notifications that is calculated from the available viewport size:

![image](https://user-images.githubusercontent.com/83657/51184685-53877e00-18d5-11e9-83fe-87f0f2dd08c4.png)

Available on `maintenance`, soon `devel`, to be released with 1.3.11.
