### ISSUE TITLE
[Request] Log file to easy deletable!

### ISSUE THREAD

**Issue by dahuafschmied** [foosel/OctoPrint#2962]
Hi Gina!

I think I dicovered a little bug and I want to give you a perfect bug report. BUT! My mouse aiming was a little disturbed by my cat and i hit the delete button instead of the download button. They are real close together. So the log is gone and I have to wait some days to reproduce the random bug.

My suggestion:
Please add a "Are you sure?" (Yes / No / HabAngst / Call Telefonseelsorge) button to the logs dialog.

Merry Christmas and a happy new year
dahuafschmied

**Comment by foosel** [comment]
I like the two additional answer options ;)

**Comment by foosel** [comment]
Implemented by the above commit, already on `maintenance`, soon `devel`, to be part of 1.3.11.

**Comment by foosel** [comment]
1.3.11 was released yesterday.
