### ISSUE TITLE
[Request] Enable/Disable Webcam/Timelapse functionality instead of clearing a string.

### ISSUE THREAD

**Issue by thantik** [foosel/OctoPrint#2974]
I have read the FAQ.

Enabling and disabling the webcam and timelapse features in OctoPrint should be simplified from: Make these two text boxes empty.  If I want to enable them again, I've gotta go somewhere external and look up what strings need to be placed back in those boxes to make the webcam work again.

Please either break these out into a plugin I can enable/disable, so that I can disable this functionality or simply add an enabled/disabled flag so I can disable the functionality without losing the strings needed for the webcam software to pick up the image.

This is just one of those 'death by a thousand paper cuts' things.  You've actually run into a bug regarding this functionality because of the odd way it's handled: https://github.com/foosel/OctoPrint/issues/2206

Instead of the additional logic to handle all of that, a simple enabled/disabled flag would simplify things immensely.

**Comment by foosel** [comment]
Implemented by the above commit, pushed to `maintenance`, soon `devel`, to be released with 1.3.11.

**Comment by foosel** [comment]
1.3.11 was released yesterday.
