### ISSUE TITLE
When print sent and heated. It homes then does nothing

### ISSUE THREAD

**Issue by rotaryfurball** [foosel/OctoPrint#2985]
#### What were you doing?

1. Press print. Wait for bed and nozzle to heat up
2. ...
3. ...

#### What did you expect to happen?
For the print to start printing
#### What happened instead?
It homes then does nothing
#### Did the same happen when running OctoPrint in safe mode?
Yep

#### Version of OctoPrint
OctoPrint 1.3.10 running on OctoPi 0.14.0

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by tedder** [comment]
Please upload your octoprint log and serial log or *we can't help you*.

**Comment by FanDjango** [comment]
Oh, I get this kind of problem often. As a matter of fact I will open an issue soon on this, but I want to collect more info and also check what is really happening - pyserial is flaky, in my opinion.
Look at the screenshots, solely after a fresh connect to the printer, it is a matter of luck for octoprint to actually see a vaild "ok" to the "M113 S29" at the end of its specific initialisation sequence.
![20-01-2019 22-35-53](https://user-images.githubusercontent.com/5990805/51445393-96e25200-1d04-11e9-9e63-e5e062a26e08.png)

![20-01-2019 22-37-14](https://user-images.githubusercontent.com/5990805/51445398-9b0e6f80-1d04-11e9-8833-815e44b608e2.png)

![20-01-2019 22-38-18](https://user-images.githubusercontent.com/5990805/51445400-9d70c980-1d04-11e9-8476-1072cd3734fa.png)
This also happens after a "Firmware Update", of course, = a reconnect, and takes some measures to fix before you can start a print.

Like I said, I have read ALL the other threads about serial communications problems and am following this topic. There is definitively a problem here and connection via minicom do NOT reflect these symptoms.

**Comment by foosel** [comment]
Closing due to lack of response & logs.
