### ISSUE TITLE
Question only: System Commands

### ISSUE THREAD

**Issue by h4nc** [foosel/OctoPrint#2989]
I have integrated „Printer on“ and „... off“ commands in my system command menu.

I‘d like to add those commands to home assistant.

Is there a way to control it outside of the ui of OctoPrint? Maybe a single link that points to a command?

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://discourse.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
