### ISSUE TITLE
[maintenance branch] sdcard hook => no start print after upload

### ISSUE THREAD

**Issue by devildant** [foosel/OctoPrint#3005]
Hello, 
I made a plugin that uses this new hook.
everything works fine except for the automatic start of the print after upload.

I created for you a plugin to test : https://github.com/devildant/OctoPrint-Test/archive/master.zip
gco and stl file : [test.gcod.stl.zip](https://github.com/foosel/OctoPrint/files/2765741/test.gcod.stl.zip)
step 1 : 
install the test plugin

step 2 : put the test.gco file inside the sd (in attachment)

step 3 : send file to octoprint for upload sd with auto start print
with cura : with plugin octoprint, and activate sd upload and auto start (use test.stl in attachment)
![image](https://user-images.githubusercontent.com/8700106/51273713-b2302300-19cd-11e9-9c7e-dd19a350a766.png)

with curl : curl -k -H "X-Api-Key:XXX" -F "select=true" -F "print=true" -F "file=test.stl" "http://XXXX/api/files/local"

step 4 : 
after the upload, everything goes well in the view, but the file is not selected and printing does not start automatically

#### Version of OctoPrint
branch maintenance

#### Operating System running OctoPrint
OctoPi

#### Printer model & used firmware incl. version

CR-10S, marlin 1.1.9 th3d

#### Browser and version of browser, operating system running browser

chrome

#### Link to octoprint.log

[octoprint.log](https://github.com/foosel/OctoPrint/files/2765739/octoprint.log)

**Comment by devildant** [comment]
I think I found the problem, it seems that there was a small error on the success callback :)
original code : 
```
		def sd_upload_succeeded(local_filename, remote_filename, elapsed):
			payload = dict(local=local_filename,
			               remote=remote_filename,
			               time=elapsed)
			eventManager().fire(Events.TRANSFER_DONE, payload)
			if callable(self._streamingFailedCallback):
				self._streamingFinishedCallback(remote_filename, remote_filename, FileDestinations.SDCARD)
```

correct code i think : 
```
def sd_upload_succeeded(local_filename, remote_filename, elapsed):
			payload = dict(local=local_filename,
			               remote=remote_filename,
			               time=elapsed)
			eventManager().fire(Events.TRANSFER_DONE, payload)
			if callable(self._streamingFinishedCallback):
				self._streamingFinishedCallback(remote_filename, remote_filename, FileDestinations.SDCARD)

```

**Comment by devildant** [comment]
I just tested, that's the problem.
I can make you a pull request if you want :)

**Comment by foosel** [comment]
🤦‍♀️ Copy paste strikes again. I'll quickly fix that, faster than going the route of a PR for both of us ;) But thanks for the offer!

**Comment by foosel** [comment]
Should be fixed by the above commit, can you please test as well?

**Comment by devildant** [comment]
the curse of copying/pasting :p
I test this after work

**Comment by foosel** [comment]
👍 

Btw, if you stop deleting any lines that aren't commented out from the ticket template the bot will also stop commenting and marking everything from you as incomplete ;)

**Comment by devildant** [comment]
👍
