### ISSUE TITLE
Option to add the api token to the bonjour details [Request]

### ISSUE THREAD

**Issue by wess** [foosel/OctoPrint#3013]
Adding this here would be nice because as desktop apps and such are being developed, we don't always want to have to add the api key directly to the app, it's a lot to type, but if we put the token in the bonjour details, the connecting client can get it (And it's local network only). Just an optional thing, to simplify desktop, in network (trusted) access/development.

**Comment by foosel** [comment]
No. Broadcasting a key that gives full admin access to an instance across the LAN is *not* going to happen. 

I suggest to look into the [Application Key workflow](http://docs.octoprint.org/en/master/bundledplugins/appkeys.html) introduced in 1.3.10 instead - that no longer requires manually copying over a key but instead involves a user acknowledged app specific key exchange.
