### ISSUE TITLE
Embed webcam image as an iframe

### ISSUE THREAD

**Issue by smurfix** [foosel/OctoPrint#3020]
#### What were you doing?

I tried to add my webcam to OctoPrint.

The camera streams via my icecast2 server, so it's a WebM stream, not mjpeg.

#### What did you expect to happen?

See the camera image of course ;-)

#### What happened instead?

Broken image icon.

#### Did the same happen when running OctoPrint in safe mode?

yes

#### Version of OctoPrint

Version 0.post5561+g902cc04

#### Operating System running OctoPrint

not relevant

#### Printer model & used firmware incl. version

all of them

#### Browser and version of browser, operating system running browser

all of them

#### Link to octoprint.log

not relevant

#### Link to contents of terminal tab or serial.log

not relevant

#### Link to contents of Javascript console in the browser

not relevant

#### Screenshot(s)/video(s) showing the problem:

not interesting

#### How to fix

Embed the remote link in an IFRAME instead of an IMG.

**Comment by foosel** [comment]
I think instead of going for an iframe as a general means of embedding, a better solution is to allow a `video` tag as an option, and maybe also an iframe. And we already have that tracked in #2001 ;)
