### ISSUE TITLE
Missing access.js in flask.py 

### ISSUE THREAD

**Issue by Salandora** [foosel/OctoPrint#3021]
#### What were you doing?

I updated from an old devel version to the new devel version :-)
And after that opened the settings and went to Access Control.

#### What did you expect to happen?

I expected to see a list of users and groups.

#### What happened instead?

I saw nothing ^^

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.4.0.dev1719+g5b4f4e3d.dirty <-- I fixed it locally so it's dirty ^^

#### Operating System running OctoPrint

Debian on a raspberry pi 3

#### Printer model & used firmware incl. version

Not necessary

#### Browser and version of browser, operating system running browser

Not necessary

#### Link to octoprint.log

Not necessary

#### Link to contents of terminal tab or serial.log

Not necessary

#### Link to contents of Javascript console in the browser

Not included

#### Screenshot(s)/video(s) showing the problem:

Not included

I have read the FAQ.

#### I have a fix for it

in server/util/flask.py:
search for assets["clientjs"] and append "js/app/client/acces.js" as this got missing from the original js_client list from server/__init__.py

Commit involved: 4f58c64881b08a3976d79015aa47bc9f6370d049

**Comment by foosel** [comment]
That should be fixed :)
