### ISSUE TITLE
UI issue (in Deutsch, da es sich um Textfehler der Oberfläche handelt)

### ISSUE THREAD

**Issue by TOTO-G** [foosel/OctoPrint#3029]
#### What were you doing?

1. Go to 'Settings'
2. Click on 'Server'
3. Noticed UI errors

#### Version of OctoPrint

1.3.10

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/29373534/52160686-69a98280-26ba-11e9-9a41-9e216854e0ab.png)

1. Bei Onlineprüfung sollte der erste Satz negiert werden, sonst ist der zweite Satz unlogisch/verwirrend.

"Wenn die Onlineprüfung deaktiviert ist, wird OctoPrint nicht in regelmäßigen Abständen prüfen, ob es mit dem Internet verbunden ist. 

2. Bei Pluginblackliste ist ein Schreibfehler

Um vor bekannte Probleme --> Um vor bekannten Probleme

I have NOT read the FAQ.

**Comment by TOTO-G** [comment]
Diese Info reicht für eine Benutzeroberflächenkorrektur.

**Comment by foosel** [comment]
>     1. Bei Onlineprüfung sollte der erste Satz negiert werden, sonst ist der zweite Satz unlogisch/verwirrend.
> 
> 
> "Wenn die Onlineprüfung deaktiviert ist, wird OctoPrint nicht in regelmäßigen Abständen prüfen, ob es mit dem Internet verbunden ist.

Nein, das wäre dann genau falsch herum. Wenn die Onlineprüfung aktiviert ist, dann nützt sie auch was, indem sie unnötige Anfragen (z.b. Updatechecks, Pluginrepositorychecks, ...) verhindert, die aufgrund einer fehlenden Verbindung ins Internet eh fehlschlügen. Wenn sie deaktiviert ist, nützt sie gar nichts.

"Wenn die Onlineprüfung deaktiviert ist, wird OctoPrint nicht in regelmäßigen Abständen prüfen, ob es mit dem Internet verbunden ist. Das ist nützlich [...]" ist somit eine Falschaussage.

>     1. Bei Pluginblackliste ist ein Schreibfehler
> 
> 
> Um vor bekannte Probleme --> Um vor bekannten Probleme

Korrigiert durch den obigen commit. Wird dann in 1.3.11 drin sein.

**Comment by foosel** [comment]
>     1. Bei Onlineprüfung sollte der erste Satz negiert werden, sonst ist der zweite Satz unlogisch/verwirrend.
> 
> 
> "Wenn die Onlineprüfung deaktiviert ist, wird OctoPrint nicht in regelmäßigen Abständen prüfen, ob es mit dem Internet verbunden ist.

Nein, dann wäre es genau falsch herum. Onlineprüfung an = nützlich, unnötige Anfragen werden unterbunden, wenn das System nicht mit dem Internet verbunden ist. Onlineprüfung aus = nicht nützlich, OctoPrint nimmt an, es sei online und schießt Anfragen (z.B. Updatechecks, Repositoryupdates) raus, selbst wenn sie fehlschlagen werden.



>     1. Bei Pluginblackliste ist ein Schreibfehler
> 
> 
> Um vor bekannte Probleme --> Um vor bekannten Probleme

Gefixt durch den obigen Commit, wird dann in 1.3.11 drin sein.

**Comment by foosel** [comment]
Sorry für den Doppelpost, irgendwie dachte ich, mein Browser hätte das gefressen.
