### ISSUE TITLE
[Request] Change backup file name

### ISSUE THREAD

**Issue by StefanIGit** [foosel/OctoPrint#3030]
So
it would be nice to have a more meaning full file name that currently e.g. 
> backup-20190131-162333.zip

This is kind of generic.... like the infamous setup.exe you down load sometimes.

It would help not just me if the name was like
> octoprint-backup-20190131-162333.zip

or 

>[HOSTNAME]-backup-20190131-162333.zip

Just any thing that reminds one which backup is in this file.

And it should be a very small change too :)
bye

**Comment by foosel** [comment]
Implemented by #3039, merged to `maintenance`, soon `devel`, to be released as part of 1.3.11

**Comment by foosel** [comment]
1.3.11 was released yesterday.
