### ISSUE TITLE
[Request] Enable unknownCommandsNeedAck when the firmware is detected as Klipper

### ISSUE THREAD

**Issue by Arksine** [foosel/OctoPrint#3038]
**Is your feature request related to a problem? Please describe.**
Klipper supports many gcodes that do not match Octoprint's regex for a valid gcode.  Klipper acknowledges these gcodes, however Octoprint can mistake these acknowledgements for other gcodes that have not yet been processed if `unknownCommandsNeedAck` is not set to True.

**Describe the solution you'd like**
Enable unknownCommandsNeedAck when M115 returns the FIRMWARE_NAME as Klipper.  Browsing Octoprint's source it seems like it would be a relatively simple solution, the following could be added below line 1819 in src/octoprint/util/comm.py:
```python
elif "klipper" in firmware_name.lower():
    self._logger.info("Detected Klipper firmware, enabling relevant features for issue free communication")

    self._unknownCommandsNeedAck = True
```

**Describe alternatives you've considered**
The alternative is to directly edit config.yaml.  While this is a workable solution, it can be intimidating for new users.   It would be preferable for Octoprint to handle this internally.

**Additional context**
If necessary I can submit a pull request for this fix myself, however I am not familiar with Octoprint's source.  Its possible that the fix I outlined above is not adequate to address the issue.

Tag to track this issue from the Klipper pull request this behavior was discovered: KevinOConnor/klipper#1191.

**Comment by foosel** [comment]
Implemented by the above PR which has been merged into `maintenance`, soon `devel` and will be part of 1.3.11.

**Comment by Arksine** [comment]
Thanks!
