### ISSUE TITLE
Disconnect During Print = problems

### ISSUE THREAD

**Issue by tenaciousRas** [foosel/OctoPrint#306]
Disconnect during a print causes problems for the server.
- - -
Version
OctoPrint-Devel, commit 481a750cf67ee445f89d68bee4201d48943b7a13

From what I recall this issue occurs on master also.
- - -
Expected:
OctoPrint disconnects without an error message even if the printer has just started a print.  If the user wants to restart the same print after reconnecting, then the user just clicks "print".
- - -
Actual:
When disconnecting during a print, this happens:

Recv: T:76.50 E:0 B:89.4
Changing monitoring state from 'Printing' to 'Closed'
Changing monitoring state from 'Closed' to 'Error: TypeError: 'an integ...'
Unexpected error while reading serial port: TypeError: 'an integer is required' @ comm.py:_readline:784

Reconnecting works OK after getting the above error; and the server still has the same file loaded, with the "Print" button enabled.  However, clicking print results in this (from JavaScript console):

POST http://192.168.1.33:5002/ajax/control/job 500 (Internal Server Error)
- - -
Steps to reproduce:
- open a web browser to a running Octoprint server
- load a valid gcode file
- click print
- click disconnect
- observe 'integer' error (above) in Terminal
- click connect
- click "Print"
- nothing happens - note error in browser's console

A workaround is to load a different file after reconnecting.  Then load the file originally intended for the job again.  Now "Print" works.

**Comment by foosel** [comment]
That actually has been fixed for ages.
