### ISSUE TITLE
RequestPause and RequestContinue not working

### ISSUE THREAD

**Issue by Goodfeat** [foosel/OctoPrint#3064]
Hello.
Why does not my printer pause from the display, does not resume printing?
Octoprint receives command, but they are not processed
"RequestContinue" and "RequestPause"

#### What were you doing?

when i press pause on the display
the printer is processing this command, but octoprint still waits to send commands to the printer, printing still works.

Resume printing also does not start when I press an item on the display.

#### What did you expect to happen?
Printing should pause.

#### What happened instead?
Printing continues despite the fact that the display of the printer says"resume printing"

#### Did the same happen when running OctoPrint in safe mode?
no

#### Version of OctoPrint
1.3.10

#### Operating System running OctoPrint
Raspberry pi 3

#### Printer model & used firmware incl. version
Repetier firmware 1.04

#### Browser and version of browser, operating system running browser
Google Chrome

#### Screenshot (s) / video (s) showing the problem:
![img_20190227_003037](https://user-images.githubusercontent.com/44455128/53420291-43f86a80-3a27-11e9-9828-55550f695af3.jpg)

**Comment by foosel** [comment]
That's because OctoPrint supports [documented action commands as agreed upon by several firmwares](http://docs.octoprint.org/en/master/features/action_commands.html) instead of the Repetier-only `Request*` commands.
