### ISSUE TITLE
Virtual printer - negative movement does not work

### ISSUE THREAD

**Issue by FlorianJa** [foosel/OctoPrint#3080]
#### What were you doing?

In web interface:
1. Connect to virtual printer
2. Switch to Control
3. Move axes in positive direction
4. check postion with m114 in terminal
5. move axes in negative direction
6. check postion with m114 in terminal 
7. see error: position does change

same happens for the home-button 

#### What did you expect to happen?
virtual printer should react to negative movement commands and home.

#### What happened instead?
no thing

#### Did the same happen when running OctoPrint in safe mode?
yes

#### Version of OctoPrint
1.3.10

#### Operating System running OctoPrint
Tested on Ubuntu and Windows 10

#### Browser and version of browser, operating system running browser
Edge and Chrome(73.0.3683.75) on Windows 10

#### Link to octoprint.log
https://pastebin.com/NudntBzn

#### Link to contents of terminal tab or serial.log
https://pastebin.com/MDxRe3yL

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Yep, the parsing of negative coordinates in the movement commands was broken, and the G28 command was using the wrong implementation.

Fixed by 
c1670d0 & d5eefcd1a55af5be49b2db41dfaec995b1b2868f, pushed to `maintenance`, soon `devel`, will be in 1.3.11.
