### ISSUE TITLE
"Fullscreen" Webcam view

### ISSUE THREAD

**Issue by vIiRuS** [foosel/OctoPrint#309]
Hey,

For print monitoring it would be nice to have a view, that displays only the webcam image (preferably scaled to the current window size or to the original webcam image size, if the window is bigger). This image could be overlayed with information like print time, remaining time, temperatures, etc. Possibly also a "cancel print button".

As our printer is in a different room than we work, monitoring it is good. Our webcam provides 1280*720px images and it would be nice to have a simple view for just viewing the current state in a bigger size than what octoprint normally shows.

As for implementation, maybe the view could open as a new window, when the user clicks on the webcam stream.

**Comment by pauly7300** [comment]
+1  I open the control tab numerous times a day just to see the print and hardly a time goes by that i don't wish i could click to expand the image either by clicking the image itself and having it expand into a larger size.  Kind of like how you can go to the wider view for Youtube video's before choosing to go to full screen.  I've been trying to figure out if I could somehow add a control to launch a web page so I could then just embed it in the page myself.  

@foosel I just want you to know how great i think OP is.  i've had a blast learning how to customize it.  I finally figured out how to key my lights coming on and going off based on opening and closing the client now.  Major cudos to you Gina!!

**Comment by rhuuk420** [comment]
+1.i've come around to these bugs/feature req's and i'm finding the value of having a bigger webcam view in the control tab that doesn't require me to go to another tab each time, or a new default "snapshot" tab that has the webcam and the gcode view in a single side by side pane, and a 20-30mm tall temp graph along the bottom would be an awesome dashboard.

**Comment by manust** [comment]
+1 
It would be nice if the Control Tab would adapt itself on the browser window size and not be limited by 588px x 441px.
Worst, when mjpg stream a big picture (ex:HD1080 resolution) only the up-left corner of the stream is shown.

**Comment by markwal** [comment]
@manust screensquish plugin does that to a certain extent.  It doesn't do fullscreen, but it does do some screen scaling (for the bootstrap breakpoints anyway)

**Comment by BillyBlaze** [comment]
I created this plugin, I will add this later to the plugin repository.

You can for now install it with: 
```
https://github.com/BillyBlaze/OctoPrint-FullScreen/archive/master.zip
```

It binds a double click event to the webcam image, if you double click on it, it should open the webcam feed into "fullscreen" mode.  In "fullscreen" mode, it will show an information bar at the bottom of the image, with the requested information (left side: temps, right side: pause button and print time)

I also added a small button next to the pause button that allow you to go in real fullscreen mode.

**Comment by foosel** [comment]
@BillyBlaze works great!

![image](https://cloud.githubusercontent.com/assets/83657/17078208/12a2afe8-50ed-11e6-9189-603a2c1e7dd8.png)

**Comment by foosel** [comment]
Plugin available and published on the repo, closing this.
