### ISSUE TITLE
Backup includes tmp files from timelapse

### ISSUE THREAD

**Issue by Harryhar** [foosel/OctoPrint#3098]
#### What were you doing?
Start a print with Timelapse enabled.
Goto : Settings->Backup & Restore
Start a new backup and exclude timelapse, uploaded files and meta data.

#### What did you expect to happen?
A fairly small backup file.

#### What happened instead?
The resulting backup is in my case around 90 MB. After looking into the backup I noticed the timelapse/tmp directory is included in the backup, but this should be excluded.

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
Version 1.3.10

#### Operating System running OctoPrint
Raspberry Pi 3

#### Printer model & used firmware incl. version
Anycubic I3 Mega

#### Browser and version of browser, operating system running browser
Chrome Versie 73.0.3683.86 (Officiële build) (64-bits), Windows 10 Proffesional

#### Link to octoprint.log
NA

#### Link to contents of terminal tab or serial.log
NA

#### Link to contents of Javascript console in the browser
NA

I have read the FAQ.

**Comment by foosel** [comment]
Indeed. Nicely spotted. And since the fix is very very trivial I'm going to even include in 1.3.11rc2 even though rc1 is already out. I hope I won't regret that ;)
