### ISSUE TITLE
Folders in GUI

### ISSUE THREAD

**Issue by hughht5** [foosel/OctoPrint#31]
Any chance you can implement folders for files?

Use case: Printing a prusa i2 takes 6 full plates for me. I'd like to upload prusa i2 folder easily then choose which plate to print.

**Comment by dragondgold** [comment]
Any updates on this? :)

**Comment by foosel** [comment]
In fact yes, @Salandora implemented folder support and it has been merged on devel since last week I think. He's also turning the file manager into a plugin. So I guess this can be closed :)

**Comment by foosel** [comment]
And some screenshots (only tablet atm, sorry)

![screenshot_2015-11-27-20-15-34](https://cloud.githubusercontent.com/assets/83657/11447273/db0c841a-9543-11e5-994f-40531645ab26.png)

![screenshot_2015-11-27-20-16-00](https://cloud.githubusercontent.com/assets/83657/11447282/e3b26512-9543-11e5-9c27-089955287204.png)

And now a round of applause for @Salandora please, that's an awesome job well done :)

**Comment by dragondgold** [comment]
Great! Thank you so much and thank you @Salandora it's working great and a very useful feature!

**Comment by Salandora** [comment]
@dragondgold I guess you will even more like the fileManager plugin when released.
Because you will have the ability to copy, move and rename files and folders then. And also a litte nice feature "upload to Sd" from an already uploaded file ;-)
I hope to get it released this weekend.

**Comment by dragondgold** [comment]
@Salandora that sounds greeeat! Looking forward for your plugin!
