### ISSUE TITLE
[Request] Notification when print has finished via email or SMS text 

### ISSUE THREAD

**Issue by sunapi386** [foosel/OctoPrint#3129]
**Is your feature request related to a problem? Please describe.**
I don't get notified when a print has finished so I can setup the next print.

**Describe the solution you'd like**
A email alert or text message alert sent once the job is complete.

**Comment by tedder** [comment]
Good news, there are several plugins for this!

https://plugins.octoprint.org/by_tag/#tag-notification

**Comment by sunapi386** [comment]
Thanks for the link @tedder! Resolved.
