### ISSUE TITLE
Plugin list not correctly resized in Plugin Manager

### ISSUE THREAD

**Issue by yet-another-average-joe** [foosel/OctoPrint#3161]
Sorry if this has already been reported, I searched for, but did'nt find anything...

#### What were you doing?

1. in the browser, open OctoPrint settings/Plugin Manager
2. Zoom the browser to 90% or more (ctrl+wheel)
3. The listbox containing the installed plugins is not fully visible ; Get More button is hidden

#### What did you expect to happen?

The listbox and the Get More button should be fully visible

#### What happened instead?

The listbox is partially visible, and the buttons are hidden (see uploaded pic below). This "frame" or its layout (listbox + buttons) is not correctly resized

**Workaround** : zoom the browser to 80% or less for Firefox, 75% or less for Slimjet

#### Version of OctoPrint

1.3.11

maybe it existed before, but I did'nt notice...

#### Operating System running OctoPrint

Windows 10

#### Browser and version of browser, operating system running browser

Firefox 66.0.5 64bit
Slimjet 22.0.4.0 64bit

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

Slimjet, Zoom 90% +

![OctoPrint 120](https://user-images.githubusercontent.com/43514870/57890128-0beb1180-7837-11e9-8896-ce59553d6cce.PNG)

Slimjet Zoom 80%

![OctoPrint 80](https://user-images.githubusercontent.com/43514870/57890150-21f8d200-7837-11e9-9b37-31eb2586862a.PNG)

Slimjet Zoom 75%

![OctoPrint 75](https://user-images.githubusercontent.com/43514870/57890571-58831c80-7838-11e9-8bdf-2af138a1a820.PNG)

Firefox 80%

![Capture](https://user-images.githubusercontent.com/43514870/57890604-810b1680-7838-11e9-8436-eab4b453cba0.PNG)

tested on 2 OctoPrint installations, one on a "real" server (Pi 3B+), the other on a printerless one (dedicated to testings, virtual printer, Pi3B).  

[EDIT] seems not being related to OS display/GUI scaling

**Comment by foosel** [comment]
Ah yeah, the size should probably rather adapt than be hard coded to avoid double scrollbars. Will look into this for 1.3.12.

**Comment by foosel** [comment]
Solved for now via the above commit by reducing the height to 400px instead of 500px, which translates to the size of the paginated table that used to be there with 5 items height. 

Dynamic size adjustment would still be better, but so far I don't have a good idea how to do that ideally only with CSS (I'd rather prefer to avoid having to implement dynamic resizing in JS here).

**Comment by foosel** [comment]
1.3.12 has been released.
