### ISSUE TITLE
[REQUEST] Keep dialogs open while a button is not clicked

### ISSUE THREAD

**Issue by yet-another-average-joe** [foosel/OctoPrint#3162]
Hi,

I wanted to ask for this feature for a long time. It would be more usefull if TouchUI is installed.

**Is your feature request related to a problem? Please describe.**

It is related to the interface default behaviour. When clicking outside a dialog window / box, it closes. This is sometimes frustrating in a browser, it can be irritating on a touchscreen because of the lack of precision (approximative touch)

**Describe the solution you'd like**

An option to keep the dialogs open as long as close / cancel / validate / etc. is not clicked / touched / taped

But maybe it is not possible...

**Describe alternatives you've considered**

**Additional context**

I could shoot a short video if neeeded

**Comment by foosel** [comment]
This has been implemented in form of a new optional setting:

![image](https://user-images.githubusercontent.com/83657/58427760-d3ea9680-80a0-11e9-99a1-4f64918de023.png)

and will be part of 1.3.12. Already available on `maintenance` & soon `devel`.

**Comment by foosel** [comment]
1.3.12 has been released.

**Comment by yet-another-average-joe** [comment]
Many thanks for this option !
