### ISSUE TITLE
[Request] API Documenation - Progress information

### ISSUE THREAD

**Issue by mdg357** [foosel/OctoPrint#3203]
**Is your feature request related to a problem? Please describe.**
The API documentation for the Progress information lacks a description of the `printTimeLeftOrigin` field. It is unclear what values may be returned in this field.

**Describe the solution you'd like**
Document all possible values that may be returned by the `printTimeLeftOrigin` field.

**Describe alternatives you've considered**
N/A

**Additional context**
Specific documentation section found here: `https://docs.octoprint.org/en/master/api/datamodel.html#progress-information`

**Comment by mdg357** [comment]
Seems like possible values _might_ be:
- linear
- estimate
- average
- analysis

**Comment by foosel** [comment]
Fixed by the above commit, pushed to `maintenance`, soon `devel`, to be part of 1.3.12.
