### ISSUE TITLE
[REQUEST] Add mode to support processing gcode with printer offline

### ISSUE THREAD

**Issue by drewzh** [foosel/OctoPrint#3205]
**Is your feature request related to a problem? Please describe.**
I have a relay connected to my OctoPI's GPIO pins that is used to toggle the printers power from within OctoPrint, using the PSU Control plugin. The PSU Control plugin is able to intercept gcode and automatically turn on the relay. This is great - however it has one major issue that stops this solution being as awesome as it can be. When the printer is powered off (after X minute idle, or from power off etc), no gcode can be received or processed within OctoPrint. This limits the plugin to use cases where the mainboard is always powered and the relay is only used to control power to supporting circuits.

**Describe the solution you'd like**
Add an (advanced) option to allow gcode to be parsed and as a side effect, picked up by listening plugins. This would allow the PSU Control plugin to receive gcode, power up the printer and then start printing from a complete power off state.

An ideal outcome would be that my slicer would be able to send a print to Octoprint and the PSU Control plugin would power up the printer and Octoprint would start printing.

Also, the gcode file print function within Octoprint would also be able to 'print', without the printer actually being on. Currently the UI elements are disabled when the printer is not connected.

Also the terminal would be able to issue commands still to the printer, regardless whether the printer is on or not.

**Describe alternatives you've considered**
No known alternative at this moment. Power on has to be done manually each time I print.

**Additional context**
N/A

**Comment by foosel** [comment]
I cannot send GCODE to a printer that is offline. There's simply nothing there to send it to. I'd have to come up with some sort of GCODE buffer in case the printer is offline that would add a WHOLE TON of issues on its own, let alone the questionable impacts on workflow and usability it would have for everyone else but people with your VERY specific use case.

Sorry, this is not going to happen.
