### ISSUE TITLE
Typo "_log_running_command" for comm.py property

### ISSUE THREAD

**Issue by Mrnt** [foosel/OctoPrint#3220]
#### What were you doing?

Reviewing Octoprint/src/util/comm.py as part of developing a plugin to support FlashForge printers, I noticed a typo at line 3581: it has `_log_running_command` instead of `_long_running_command`.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Thanks for the catch, should be fixed on `maintenance`, soon `devel` and to be part of 1.3.12.

**Comment by Mrnt** [comment]
Thanks for all your hard work on this project!
