### ISSUE TITLE
Print time estimate is way off from Cura and actual print time.

### ISSUE THREAD

**Issue by ilovecats516** [foosel/OctoPrint#3230]
#### What were you doing?

Printing a file that was uploaded from Cura.

#### What did you expect to happen?
Time estimate close to Cura's.

#### What happened instead?
Time estimate was off by 3 hours.

#### Did the same happen when running OctoPrint in safe mode?
Yes.

#### Version of OctoPrint
13.11

#### Operating System running OctoPrint
OctoPi 0.16.0

#### Printer model & used firmware incl. version
Anycubic i3 Mega.

#### Browser and version of browser, operating system running browser
Google Chrome, version 75.0.3770.142 (Official Build) (64-bit)
Windows 10 Home

#### Link to octoprint.log
https://gist.github.com/ilovecats516/8a82383d3fd711c91322ef4f62b78e16

#### Link to contents of terminal tab or serial.log
https://gist.github.com/ilovecats516/88be21dd6e2759e63053524a7dfafdc4

#### Link to contents of Javascript console in the browser
https://gist.github.com/ilovecats516/dfb2ecc7081fbec7fbc4712bf15d901b

#### Screenshot(s)/video(s) showing the problem:
![image](https://user-images.githubusercontent.com/30846409/61564585-9d3f5580-aa2b-11e9-9133-ac8862fbe3f1.png)

I have read the FAQ.
Yes.

**Comment by foosel** [comment]
There are plugins that extract estimation information from the GCODE, I suggest to install one of these, e.g. PrintTimeGenius.

Print time estimation *in every single scenario* is non trivial, I've talked about why endlessly on OctoPrint On Air.

Closing as won't fix.
