### ISSUE TITLE
Add handling of @pause in gcode files

### ISSUE THREAD

**Issue by Cylindric** [foosel/OctoPrint#324]
Hi, it would be useful for us single-extruder people to be able to pause the print at a precise position. Would it be possible to implement the @pause command similar to how Repetier does?

Basically if Octoprint sees @pause in the gcode, it enters the same pause state as if the pause button was pressed.

thanks

**Comment by guysoft** [comment]
Is this still the case?
Doesn't this make this plugin useless?
https://github.com/MoonshineSG/OctoPrint-MultiColors

**Comment by foosel** [comment]
Just noticed that I forgot to close this when 1.3.7 was released, which added native support for `@pause` [and some other commands](http://docs.octoprint.org/en/master/features/atcommands.html).
