### ISSUE TITLE
[FEATURE] Add stop button to the control menu. 

### ISSUE THREAD

**Issue by k0nradz** [foosel/OctoPrint#3242]
Hi,

It is possible to add STOP button to the control menu? When we push home button manually its im possible to stop the printer. Today I have collision nozzle with bed after manually push home button.

![obraz](https://user-images.githubusercontent.com/39839309/62293820-b43d6900-b469-11e9-885e-9d7280b0c390.png)

**Comment by foosel** [comment]
Take a look at one of the existing emergency stop plugins and custom controls.

Apart from that it's the job of your printer's firmware to keep the nozzle from ramming into the print bed, especially while homing.

**Comment by k0nradz** [comment]
I have found "Custom Control Editor (0.2.1)" plugin. It works great when I added "M84;" G-Code stop command. 

THANKS FOR HELP!
