### ISSUE TITLE
SKR 1.3 and no connection with OctoPrint

### ISSUE THREAD

**Issue by disco22522** [foosel/OctoPrint#3244]
#### What were you doing?
Connecting the Marlin 2.0 firmware on a SKR 1.3 board. Connection seems to happen, but then it drops out later on.

Flash SKR 1.3 with Marlin 2.0 bugfix, plug in latest OctoPrint and attempt connection.
Seeing 
Recv: FIRMWARE_NAME:Marlin bugfix-2.0.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:SKR V1.3 EXTRUDER_COUNT:2 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ffRecv: Cap:SERIAL_XON_XOFF:0Recv: Cap:EEPROM:1Recv: Cap:VOLUMETRIC:1Recv: Cap:AUTOREPORT_TEMP:1Recv: Cap:PROGRESS:0Recv: Cap:PRINT_JOB:1Recv: Cap:AUTOLEVEL:0Recv: Cap:Z_PROBE:0Recv: Cap:LEVELING_DATA:0Recv: Cap:BUILD_PERCENT:0Recv: Cap:SOFTWARE_POWER:0Recv: Cap:TOGGLE_LIGHTS:0Recv: Cap:CASE_LIGHT_BRIGHTNESS:0Recv: Cap:EMERGENCY_PARSER:0Recv: Cap:PROMPT_SUPPORT:0Recv: Cap:AUTOREPORT_SD_STATUS:0Recv: Cap:THERMAL_PROTECTION:0

#### What did you expect to happen?
Connection to work, and use OctoPrint with Marlin 2.0
#### What happened instead?
Didn't connect to SKR 1.3 w/ OctoPrint
#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
1.3.11

#### Operating System running OctoPrint
OctoPi 0.16.0

#### Printer model & used firmware incl. version
Custom cartesian 220x220x220mm , volcano e3d, heated bed, marlin 2.0 bugfix on SKR 1.3 TMC2208 UART

#### Link to octoprint.log
https://pastebin.com/n2xDk0jy

#### Link to contents of terminal tab or serial.log
https://pastebin.com/f0V1sg2L

I have read the FAQ.

#### Other notes

Successful thermistor readings on Simplify3D 
M303 sent through Terminal on OctoPrint gives a successful read-out of both heated bed and hot end. Connection also does not interrupt during this process. Here is the termina after running M303 - https://pastebin.com/nMSkCfu4

**Comment by foosel** [comment]
This doesn't sound like a general issue with OctoPrint but more like a problem with your specific setup. Please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
