### ISSUE TITLE
Custom Command Enabled/Javascript

### ISSUE THREAD

**Issue by randellhodges** [foosel/OctoPrint#3247]
#### What were you doing?

Creating a custom command with both javascript and enabled specified. When I clicked on the button, it didn't execute the code I specified in javascript, it executed what was in enabled.

#### What did you expect to happen?

Execute what was in javascript

#### What happened instead?

Executed what was in enabled

#### Did the same happen when running OctoPrint in safe mode?

N/A

#### Version of OctoPrint

1.3.11

#### Operating System running OctoPrint

Ubuntu

#### Printer model & used firmware incl. version

Ender 3 Pro, Marlin 2.0 bugfix

#### Browser and version of browser, operating system running browser

Chrome 75

#### Link to octoprint.log

N/A

#### Link to contents of Javascript console in the browser

https://github.com/foosel/OctoPrint/blob/81735d07c9d96720b4dfdc17a832f9be2affa950/src/octoprint/static/js/app/viewmodels/control.js#L206

```
            var js;
            if (control.hasOwnProperty("javascript")) {
                js = control.javascript;

                // if js is a function everything's fine already, but if it's a string we need to eval that first
                if (!_.isFunction(js)) {
                    control.javascript = function (data) {
                        eval(js);
                    };
                }
            }

            if (control.hasOwnProperty("enabled")) {
                js = control.enabled;

                // if js is a function everything's fine already, but if it's a string we need to eval that first
                if (!_.isFunction(js)) {
                    control.enabled = function (data) {
                        return eval(js);
                    }
                }
            }
```

It looks like the value is captured into a single variable, "js" and then eval'd at a later time. The code block for hasOwnProperty("enabled") is setting js to something else, and thus later, when I click on the button, it is running the overwritten js.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Good analysis, seems like that is exactly what happened here.

I've pushed a fixing commit. Will be part of 1.3.12. In the meantime - if you want - you can test the fixed behaviour on the `maintenance` branch.
