### ISSUE TITLE
[Request] Don't allow a print to be started by keyboard only/github like confirmation

### ISSUE THREAD

**Issue by dadosch** [foosel/OctoPrint#3250]
**Is your feature request related to a problem? Please describe.**
The following situation: a person who doesn't know 3d printing (for example family member) tries to log in to a computer. To wake up the screen she presses enter, but since the screen isn't locked (just turned off), octoprint starts to print since the tab hasn't been closed and the keyboard fokus was still on the print button. The printer then starts to print and might damage itself or the previous print. This might sound made up, but it just happened to me.

**Describe the solution you'd like**
A solution to this problem could be to allow a print only after a confirmation dialog is clicked (which can't be bypassed by accident) or a github like confirmation, where you have to type for example the first word of the stl file/your username/whatever.

**Describe alternatives you've considered**
An alternative would be to timeout octoprint sessions.

**Comment by skylu3d** [comment]
Hi, 
I just having some issue with have the octoprint to read and printing from yesterday.
I was able to load the gcode file and but when I click print from browser and it won't process the gcode...
so I restart octopi in safe mode and try again but seems it works fine.
Is there something can be done to resolve this issue?

Thanks in advanced.
![unload gcode screenshot-1](https://user-images.githubusercontent.com/53314663/63561487-a7a1c180-c58c-11e9-8d04-133ee55ffff8.JPG)
![safe mode screenshot](https://user-images.githubusercontent.com/53314663/63561503-b5574700-c58c-11e9-8707-968247a4b6f0.JPG)

**Comment by dadosch** [comment]
> Hi,
> I just having some issue with have the octoprint to read and printing from yesterday.
> I was able to load the gcode file and but when I click print from browser and it won't process the gcode...
> so I restart octopi in safe mode and try again but seems it works fine.
> Is there something can be done to resolve this issue?
> 
> Thanks in advanced.

I think this isn't related to this request. Would you mind using the forum instead:

https://community.octoprint.org/

**Comment by foosel** [comment]
There's now an optional print start confirmation:

![image](https://user-images.githubusercontent.com/83657/64343392-c5d7da80-cfec-11e9-8b50-9e31ebb9d7a8.png)

Check that box and you'll get a sanity check confirmation dialog when starting a print job via the UI:

![image](https://user-images.githubusercontent.com/83657/64343439-d9834100-cfec-11e9-8d78-2cf7c356f809.png)

Pushed to `maintenance`, soon `devel`, to be part of 1.3.12.

**Comment by foosel** [comment]
1.3.12 has been released.
