### ISSUE TITLE
Error when enabling/disabling/installing/uninstalling plugins while printer is paused

### ISSUE THREAD

**Issue by mdelecate** [foosel/OctoPrint#3278]
#### What were you doing?
1. Paused an ongoing print from the web interface
2. Clicked on OctoPrint Settings 
3. Clicked on Plugin Manager
4. Attempted to enable/disable/install/uninstall plugins 

#### What did you expect to happen?
Expected the action on the plugin to complete, e.g. enable/disable/install/uninstall plugin. 

#### What happened instead?
An error in red pops up: "Something went wrong / Please consult octoprint.log for details"

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
OctoPrint 1.3.12rc2

#### Operating System running OctoPrint
OctoPi 0.17.0

#### Printer model & used firmware incl. version
Artillery/Evnovo Sidewinder X1
Marlin 1.1.9

#### Browser and version of browser, operating system running browser
Max OS 10.14.6 (18G87) 
Safari Version 12.1.2 (14607.3.9)

#### Link to octoprint.log
https://gist.github.com/mdelecate/05b3c1ee499b8211a5181780c7ff7c5c#file-octoprint-log

#### Link to contents of terminal tab or serial.log
https://gist.github.com/mdelecate/05b3c1ee499b8211a5181780c7ff7c5c#file-serial-log

#### Link to contents of Javascript console in the browser
<img width="800" alt="Screenshot 2019-09-18 at 7 55 32 PM" src="https://user-images.githubusercontent.com/12543435/65146463-7236a980-da4e-11e9-80fd-d12e8a23be2f.png">

#### Screenshot(s)/video(s) showing the problem:
<img width="800" alt="Screenshot 2019-09-18 at 7 54 00 PM" src="https://user-images.githubusercontent.com/12543435/65146379-31d72b80-da4e-11e9-9b0a-daa84c5c90a8.png">

I have read the FAQ.

**Comment by foosel** [comment]
Denying plugin management while a print job is active (whether printing or paused is irrelevant here) is correct. But it should inform about that in the web interface and not even offer the options. That it does is a bug.

**Comment by mdelecate** [comment]
Holy moly you're as fast as lightning!!!

**Comment by foosel** [comment]
Coincidence ;) Trying to be as productive as possible while sitting in a waiting room.

**Comment by foosel** [comment]
Fixed by the above commit, already on `maintenance`, soon `devel`, to be released with 1.3.**13** (1.3.12 is already frozen).

**Comment by mdelecate** [comment]
All from a waiting room!!! 🤯
