### ISSUE TITLE
[Help]wget gcode file, 403 error

### ISSUE THREAD

**Issue by materdd** [foosel/OctoPrint#3279]
#### What were you doing?
I want to download gcode file uploaded on octoprint with wget.

1. I upload gcode file from octoprint.
2. I got gcode file path, "http://127.0.0.1:5000/downloads/files/local/CFFFP_3DBenchy.gcode"
3. wget http://127.0.0.1:5000/downloads/files/local/CFFFP_3DBenchy.gcode
4. I got error 403 forbidden.

I can download the gcode file from browsers. It looks like the gcode file doesn't have permission.

Any idea? Best regards.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
