### ISSUE TITLE
[Request] Filterable List in Plugin Manager

### ISSUE THREAD

**Issue by jneilliii** [foosel/OctoPrint#3288]
**Is your feature request related to a problem? Please describe.**
Now that the plugin list is a long list rather than paged, It would be beneficial to have a text filtering option for minimizing the list when trying to find something to enable/disable/uninstall.

**Describe the solution you'd like**
A simple text box at the top of the list, similar to the list when installing a plugin, that filters what's there based on the entered text.

**Comment by jneilliii** [comment]
I will look at this capability in the near future and potentially submit a PR for it.

**Comment by foosel** [comment]
Needed a quick win

![image](https://user-images.githubusercontent.com/83657/65714769-0da5cb00-e09c-11e9-8f9c-6e2e6897dbdf.png)

**Comment by jneilliii** [comment]
Thanks Gina. I see a couple of other filter buttons up there as well.  Any possibility to get enabled and disabled added to those?

**Comment by foosel** [comment]
I'll take a look

**Comment by foosel** [comment]
![image](https://user-images.githubusercontent.com/83657/67570696-518aff00-f732-11e9-8a3b-1fa979af53cf.png)

**Comment by jneilliii** [comment]
Your awesome @foosel, thanks.

**Comment by foosel** [comment]
1.4.0 has been released.
