### ISSUE TITLE
Action Command Prompt: Rendering error with long texts

### ISSUE THREAD

**Issue by leptun** [foosel/OctoPrint#3292]
#### What were you doing?

I was implementing a "Print from SD" with button with full filename structure into Prusa-Firmware that used Action Command Prompt as the plugin to display the files, but ran into rendering issues with it when the text in the button became too long. You can see it in the attached photo.

#### Did the same happen when running OctoPrint in safe mode?

This is using one of the built-in plugins and requires it to be enabled.
#### Version of OctoPrint

OctoPrint 1.3.11
#### Operating System running OctoPrint

Windows 10
#### Printer model & used firmware incl. version

Not applicable, but it's a Prusa Mk3S for reference. (Custom FW!!!)
#### Browser and version of browser, operating system running browser

N/A. Happens in all browsers. I use Chrome, tested also in Edge. The browser runs on the same machine as octoprint.
#### Link to octoprint.log
https://gist.github.com/leptun/ff3f1cfda1fe534b081f4ebf49e035db

#### Link to contents of terminal tab or serial.log
https://gist.github.com/leptun/234d887458210058d3cfc1c52d3d7b2a

#### Link to contents of Javascript console in the browser
https://gist.github.com/leptun/ae5ef70c34e1265d8915df5ac2a6633d

#### Screenshot(s)/video(s) showing the problem:

https://photos.app.goo.gl/xVqXAvABzW23c3Q26
![Screenshot (297)](https://user-images.githubusercontent.com/17808203/65826763-41971100-e293-11e9-9273-857d010ae52b.png)

I have read the FAQ.

**Comment by foosel** [comment]
Admittedly I never anticipated text as long as that and hence used a simple button here which doesn't wrap text on its own. Guess that needs to be extended slightly to accommodate use cases like this one.

**Comment by leptun** [comment]
Thank you for looking into this. :)

**Comment by foosel** [comment]
![image](https://user-images.githubusercontent.com/83657/67576454-db40c980-f73e-11e9-8f33-1a97a21d085c.png)

![image](https://user-images.githubusercontent.com/83657/67576482-e8f64f00-f73e-11e9-8aed-14870a924175.png)

Implemented by the above commit, will be in the next release.

**Comment by leptun** [comment]
Thank you! Closing issue.
