### ISSUE TITLE
[devel] autofocus in placeholder of login

### ISSUE THREAD

**Issue by jneilliii** [foosel/OctoPrint#3296]
#### What were you doing?
Starting up OctoPrint devel branch.  Username field in the login screen has `autofocus` in the placeholder and the field is not focused by default as intended.
#### What did you expect to happen?
Username field to receive focus and not have the word in the placeholder.
#### What happened instead?
`autofocus` in placeholder
#### Did the same happen when running OctoPrint in safe mode?
Yes
#### Version of OctoPrint
OctoPrint 1.4.0.dev2370+g0035e7c3.dirty

#### Operating System running OctoPrint

Windows on Python 3

#### Printer model & used firmware incl. version

N/A

#### Browser and version of browser, operating system running browser

Google Chrome

#### Link to octoprint.log

N/A

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/5249455/66262014-21d97e80-e7a6-11e9-8c0c-25ab8e911376.png)

Just need to move the autofocus outside of the parenthesis of the placeholder from this:

`<input type="text" data-bind="value: login_username" class="input-block-level" placeholder="{{ _('Username') }} autofocus">`

to this:

`<input type="text" data-bind="value: login_username" class="input-block-level" placeholder="{{ _('Username') }}" autofocus>`

[here](https://github.com/foosel/OctoPrint/blob/0035e7c3ff87f3c6f3821fa55192c9523a547bb5/src/octoprint/templates/index.jinja2#L174)

I have read the FAQ.

**Comment by foosel** [comment]
Fixed by the above commit
