### ISSUE TITLE
Vector3D is doing an instance check with every add or multiply

### ISSUE THREAD

**Issue by jmfrank63** [foosel/OctoPrint#3318]
#### What were you doing?
Reading the source code ;-)
Hi Gina,

I wanted to follow up on our conversation during the PyConDE.

Tests in ipython on my Mac showed that `try except `is about 6 times faster compared to `isinstance`

Since most of the time the type is either an int or a float try except will just pass through and only take significant more time in case of a TypeError (which should be used here instead of a ValueError)
I would therefore suggest to exchange the if isinstance in the Vector3D with try except blocks and thus getting a 6 times speedup with every vector addition and multiplication.

I'd put in a PR if you like me to. ;-)

Thanks Johannes

This is not an error it is just not ideal in the perspective of performance.

#### What did you expect to happen?
It would be beneficial to use the try except pattern instead, as this is around 6 times faster when the value is actually an integer or float.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Good point! Implemented by the above commit. Just for the record, this is only going to speed up the GCODE analysis though that happens outside of prints. Made me tuned to some more critical look at use of `isinstance` checks how ever, so that can only be good!
