### ISSUE TITLE
[Request] API Options

### ISSUE THREAD

**Issue by gcurtis79** [foosel/OctoPrint#3379]
**Is your feature request related to a problem? Please describe.**
Slicing applications with API access can print without any user authentication.

**Describe the solution you'd like**
Add options to disable "Start Print" and/or Heating End/Bed in the API section

**Describe alternatives you've considered**
I've looked for plug-ins, I've trying butchering the OctoPrint python files, and I can't seem to find a way to prevent the auto-start of prints from the API functions.

**Additional context**
I maintain the equipment (3D Printers, Laser Engravers, etc...) at our local Makerspace. I need to make our users log in to OctoPrint to start their prints after sending from Cura, but I can't prevent them from checking the "Automatically start print job after uploading". My best alternative is to prevent the API from being able to start prints, which would require users to upload their gcode to OctoPrint, then login (which only authorized, trained members could to) and start the print manually.

Thank you so much for all the work on this project, I hope to figure a solution out, maybe a plug-in or something. I feel like others could benefit from this feature as well.

**Comment by foosel** [comment]
What you are requesting here should be possible with the granular permission system as implemented by #1110 in 1.4.0 of which the first two RCs are already out. Closing this as duplicate.
