### ISSUE TITLE
Printer inactive on Octoprint 1.3.12 Marlin RC1.1.8

### ISSUE THREAD

**Issue by averter** [foosel/OctoPrint#3395]
#### What were you doing?
Trying to 3D print and had just installed/configured Octoprint 1.3.12 on a Raspberry Pi 3. The 3D printer is a Prusa i3 rework with an old version of Marlin (RC1.1.8). 
1- Hit the Print button
2- The printer set the hotbed temperature
3- After a few seconds received a "Error reported by printer Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Heating failed, system stopped! Heater_ID: bed - Printer halted. kill() called!"

#### What did you expect to happen?
Printer to respond to controls

#### What happened instead?
The printer is always inactive.

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
Octoprint 1.3.12

#### Operating System running OctoPrint
OctoPi 0.17

#### Printer model & used firmware incl. version
Prusa i3 Rework, Marlin RC1.1.8

#### Link to octoprint.log
See serial.log [here](https://gist.github.com/averter/ea9f55f8e67cff1b598b2aa1fb5026c6) instead 

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
That's your firmware telling you that your bed heater is not behaving as expected and not an issue with OctoPrint. Make sure your printer is actually powered on.

**Comment by averter** [comment]
Well...I know how silly this is. However and in my defense, it only happened because this raspberry pi is new and had a fan attached to it, which is quite noisy, and made me believe that the printer was on (with the passive cooling fan). Thanks and sorry for the waste of time

**Comment by foosel** [comment]
Don't worry, you aren't the first one to make this mistake or I wouldn't have immediately assumed this to be the problem 😅
