### ISSUE TITLE
Time-lapse with libx264 lists incorrect (0 byte) file size in GUI

### ISSUE THREAD

**Issue by JohnOCFII** [foosel/OctoPrint#3396]
<img width="678" alt="Screen Shot 2019-12-17 at 3 16 07 PM" src="https://user-images.githubusercontent.com/7844212/71036671-c00d8d00-20e3-11ea-8044-40734b31942b.png">

#### What were you doing?

Using the new `libx264` to create a time-lapse.

#### What did you expect to happen?

Timelapse to be be created showing accurate file size.

#### What happened instead?

Timelapse shows 0 bytes file size.

#### Did the same happen when running OctoPrint in safe mode?

Not tested.

#### Operating System running OctoPrint

1.4.0rc3

#### Printer model & used firmware incl. version

Prusa MK3S with MMU2S

#### Browser and version of browser, operating system running browser

Safari 13.0.4 on macOS Catalina (10.15.2)

#### Link to octoprint.log

https://gist.github.com/JohnOCFII/a1763040858b31dbf7e33d75adcad107

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
That turns out to actually have been a caching issue which is now fixed and ready for 1.4.0rc4. Thanks for reporting!

**Comment by foosel** [comment]
1.4.0rc4 is out
