### ISSUE TITLE
[1.4.0rc3] /api/settings accessible for guests

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#3425]
@Lantoit thanks for testing. Attachments in emails don't come across in github issues, so I cannot see the images, but the text says enough. I think this is a sideeffect of the granular permission system, but lets see what @foosel has to say about this when she is back.

Edit: Confirmed with `curl http://octopi/api/settings` (ie: no API key or other headers specified, no client-side cache) that 1.4.0 RC3 returns the full settings dict and 1.3.12 returns a Forbidden error.

_Originally posted by @fieldOfView in https://github.com/foosel/OctoPrint/issues/3389#issuecomment-572678251_

**Comment by foosel** [comment]
Now that was a bit more tricky than anticipated.

The "everything blocked for you" login dialog in 1.4.0* so far was done as part of the same page as the core UI. However, in order to initialize this in the first place, the settings are needed. After some brainstorming we are now back at the design of having said login dialog as a separate page like in 1.3.x with the forcelogin plugin, self contained and with a way less complicated initialization process.

That brings back the slightly annoying reload that's needed after login/logout but it makes everything way less of a horrible headache to maintain.

Patch ready for 1.4.0rc4

**Comment by fieldOfView** [comment]
I checked out and am running 8d31d66, but `curl http://octopi.local/api/settings` - without any additional headers - still returns a full settings dict.

On a possibly related note, in 1.3.12 `curl http://octopi.local/api/login?passive=true` (again, without an API key) returns a 204 No Content status code, which I understand because there is no login. In 1.4RC3 as well as 8d31d66, it returns a dict:
`{"_is_external_client":false,"needs":{"group":["guests"]}}`

**Comment by foosel** [comment]
Indeed... consider me slightly puzzled because I obviously tested this earlier and then it worked as expected. Investigating...

> In 1.4RC3 as well as [8d31d66](https://github.com/foosel/OctoPrint/commit/8d31d6687ec86539ee54e818cafa0463cfbe710c), it returns a dict:
> `{"_is_external_client":false,"needs":{"group":["guests"]}}`

That is intentional because in 1.4.0 even "no user" is an anonymous user which depending on the configuration might have some amount of access configured (if you change the permissions of the "read only" group).

**Comment by foosel** [comment]
So apart from the wonky english in the corresponding commit message above this should now be fixed. Slightly embarrassing XD

**Comment by foosel** [comment]
Also fixed a caching issue after restart that got introduced by the refactoring that took place as part of this fix.

**Comment by fieldOfView** [comment]
It seems to work now with curl, and with a "fresh" browser. When the browser is logged in to OctoPrint, the X-Api-Key header is ignored and the browser uses the credentials of the session instead (which is fine).

**Comment by foosel** [comment]
1.4.0rc4 is out
