### ISSUE TITLE
More Relevant Time Scale

### ISSUE THREAD

**Issue by cakeller98** [foosel/OctoPrint#343]
I'd like to request a more relevant time scale.  It's really great to have a lot of history, but I use octoprint as a server... and hence leave it on all the time.  what that means is - when the printer is idle octoprint gathers thousands of minutes of data... and displays it all at the same scale.

would be great if the time scale was logarithmic, so the latest information always has the highest level of detail while the oldest data gets more and more compressed.

IOW - the right 1/2 the graph should show the last 5 minutes always, then the next 1/4 would show the last 50 minutes, then the next 1/8th 500, then the next 1/16 5000....

or some form of that...

**Comment by foosel** [comment]
Fixed in `devel`
