### ISSUE TITLE
[1.4.0rc3] Folder Test fails

### ISSUE THREAD

**Issue by willhoh** [foosel/OctoPrint#3431]
#### What were you doing?
I test the folders under Settings > Folder

#### What did you expect to happen?
That the tests are completed positively

#### What happened instead?
When I test the folders under Settings > Folder, I get an error for each one that it is not writable. 

#### Did the same happen when running OctoPrint in safe mode?
Don't know, didn't done yet.

#### Version of OctoPrint
1.4.0rc3 but running with Python3

#### Operating System running OctoPrint
Rasbian On Pi B+ v1.2

#### Browser and version of browser, operating system running browser
Chrome on Win10, Ubuntu 19.10 and Android

#### Link to octoprint.log
https://gist.github.com/willhoh/73be27baaaa57ccc782f194de1287396

#### Screenshot(s)/video(s) showing the problem:
[Settings > Folder](https://i.imgur.com/86R7Poa.png)

I have read the FAQ.

**Comment by foosel** [comment]
Fixed by the above commit, ready for 1.4.0rc4

**Comment by foosel** [comment]
1.4.0rc4 is out
