### ISSUE TITLE
OctoPi does not detect rasp v2 cam and instead defaults to usb type cam.

### ISSUE THREAD

**Issue by finasfinas** [foosel/OctoPrint#3462]
#### What were you doing?
I am trying to configure my original raspberry cam v2.

#### What did you expect to happen?

I expected that the configuration parameter "camera_raspi_options=" on octopi.txt to work.

#### What happened instead?

no matter what I set that parameter to, it doesn't change anything. The camera view stays the same at 640x480 resolution. If I set the "camera" parameter from auto to raspi, the camera view stays black ( does not work ). If I set it back to auto and change the parameter "camera_usb_options" then I can see changes in the camera view but if I select any resolution besides 640x480 I can only see pixelated video.

#### Did the same happen when running OctoPrint in safe mode?

no idea of what safe mode is.

#### Version of OctoPrint
1.4.0rc5 running on octopi 0.17.0

#### Operating System running OctoPrint
OctoPi,  0.17.0.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
This is the repository of OctoPrint, you are looking for [OctoPi](https://github.com/guysoft/OctoPi) or rather the community forums at https://community.octoprint.org
