### ISSUE TITLE
[Request] Add Logitech Webcam C120 to "Webcams known to work" list

### ISSUE THREAD

**Issue by ghostolo90** [foosel/OctoPrint#3466]
I have a raspberry pi 3B+ and octoprint 1.3.12.
I tried to connect a Logitech Webcam C120 and it worked with default parameters.
I'm not sure if is needed "additional_brokenfps_usb_devices=("046d:080f")" like the C110, but i can check it if you explain me how to do.
Is it possible to add Logitech Webcam C120 to "Webcams known to work" list?
Thanks

**Comment by foosel** [comment]
If it works, just add it to the wiki, any GitHub user should be able to edit that. For any changes to the configuration shipped on OctoPi, you'd rather want to get in touch on that project's repository: https://github.com/guysoft/OctoPi
