### ISSUE TITLE
Request for Gcode script creation / execution from control or terminal interface

### ISSUE THREAD

**Issue by vshie** [foosel/OctoPrint#347]
I know I can upload a few of the small gcode files I use for leveling the bed and run them, but a way of writing a few lines and saving it as a built in script would be pretty handy. See Repetier host -> printer -> send script 1 (through 4) for what I mean.

**Comment by foosel** [comment]
Available in `devel` (Settings > GCODE Scripts and [extended custom controls](http://docs.octoprint.org/en/devel/features/custom_controls.html#sec-features-custom-controls-examples-gcode-script))
