### ISSUE TITLE
Install error when using Python 3.5

### ISSUE THREAD

**Issue by normen** [foosel/OctoPrint#3470]
#### What were you doing?
Trying to install OctoPrint in a python 3 virtual environment

```
pi@makerpi:~/OctoPrint $ virtualenv --python=/usr/bin/python3 venv3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pi/OctoPrint/venv3/bin/python3
Also creating executable in /home/pi/OctoPrint/venv3/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
pi@makerpi:~/OctoPrint $ source venv3/bin/activate
(venv3) pi@makerpi:~/OctoPrint $ pip install "OctoPrint>=1.4.0rc1"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting OctoPrint>=1.4.0rc1
  Downloading https://www.piwheels.org/simple/octoprint/OctoPrint-1.4.0-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 111 kB/s 
ERROR: Package 'OctoPrint' requires a different Python: 3.5.3 not in '>=2.7.9, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, <4'
```

Same results with the current master (1.4.0 tag)

```
pi@makerpi:~/OctoPrint $ ./venv2/bin/pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/OctoPrint
ERROR: Package 'OctoPrint' requires a different Python: 3.5.3 not in '>=2.7.9, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, <4'
```

#### What did you expect to happen?
Octoprint would install into the virtual environment

#### What happened instead?
It didn't install

#### Did the same happen when running OctoPrint in safe mode?
It didn't install

#### Version of OctoPrint
1.4.0

#### Operating System running OctoPrint
Raspbian GNU/Linux 9 (stretch)

#### Printer model & used firmware incl. version
--

#### Browser and version of browser, operating system running browser
--

#### Link to octoprint.log
--

#### Link to contents of terminal tab or serial.log
--

#### Link to contents of Javascript console in the browser
--

#### Screenshot(s)/video(s) showing the problem:
--

I have read the FAQ.

**Comment by foosel** [comment]
That's as designed. OctoPrint requires at least python 3.6. The line had to be drawn somewhere to reduce testing overhead, and 3.6 has been out since 2016.
