### ISSUE TITLE
Print stops right after start. Error code: Hotend too cold

### ISSUE THREAD

**Issue by andresorensen** [foosel/OctoPrint#3487]
#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

Hi
I just installed octoprint and every time I start a print I get the following error code: 

Printer: Ender 5
Board: 1.1.5
Firmware: th3d unified firmware
Raspberry Pi 4 2GB
OctoPrint 1.4.0 running on OctoPi 0.17.0
tl-smoothers

Send: M105
Recv: ok T:145.59 /0.00 B:55.59 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:140.91 /0.00 B:55.88 /60.00 @:0 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:136.25 /0.00 B:57.07 /60.00 @:0 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:134.46 /0.00 B:57.65 /60.00 @:0 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:132.80 /0.00 B:58.24 /60.00 @:0 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:131.19 /195.00 B:58.81 /60.00 @:127 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:130.65 /195.00 B:59.39 /60.00 @:127 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:131.83 /195.00 B:59.88 /60.00 @:127 B@:127
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:134.18 /195.00 B:60.17 /60.00 @:127 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:137.34 /195.00 B:60.19 /60.00 @:127 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:141.18 /195.00 B:60.16 /60.00 @:127 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:144.90 /195.00 B:60.00 /60.00 @:127 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:148.71 /0.00 B:60.00 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:152.70 /0.00 B:59.82 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:155.37 /0.00 B:59.39 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: echo:enqueueing "M23 cebf36~1.gco"
Recv: echo:enqueueing "M24"
Recv: echo:Now fresh file: cebf36~1.gco
Recv: File opened: cebf36~1.gco Size: 14677209
Recv: File selected
Recv: ok T:152.30 /0.00 B:58.76 /0.00 @:0 B@:0
Send: M27
Recv: ok T:152.13 /0.00 B:58.73 /60.00 @:0 B@:0
Recv:  T:152.13 /0.00 B:58.73 /60.00 @:0 B@:0 W:?
Recv:  T:151.24 /0.00 B:58.63 /60.00 @:0 B@:127 W:?
Recv:  T:150.33 /0.00 B:58.80 /60.00 @:0 B@:127 W:?
Recv:  T:149.41 /0.00 B:58.92 /60.00 @:0 B@:127 W:?
Recv:  T:148.58 /0.00 B:59.04 /60.00 @:0 B@:127 W:4
Recv:  T:147.60 /0.00 B:59.22 /60.00 @:0 B@:127 W:3
Recv:  T:146.64 /0.00 B:59.44 /60.00 @:0 B@:127 W:2
Recv:  T:145.71 /0.00 B:59.61 /60.00 @:0 B@:127 W:1
Recv:  T:144.70 /0.00 B:59.83 /60.00 @:0 B@:127 W:0
Recv: ok T:144.27 /195.00 B:60.00 /60.00 @:0 B@:127
Recv:  T:144.27 /195.00 B:60.00 /60.00 @:0 B@:127 W:?
Recv:  T:143.34 /195.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:142.53 /195.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:142.04 /195.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:142.04 /195.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:142.44 /195.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:143.23 /195.00 B:60.08 /60.00 @:127 B@:0 W:?
Recv:  T:144.29 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:145.52 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:146.96 /195.00 B:59.91 /60.00 @:127 B@:127 W:?
Recv:  T:148.54 /195.00 B:60.02 /60.00 @:127 B@:0 W:?
Recv:  T:150.12 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:151.88 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:153.89 /195.00 B:59.99 /60.00 @:127 B@:127 W:?
Recv:  T:155.67 /195.00 B:60.01 /60.00 @:127 B@:0 W:?
Recv:  T:157.49 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:159.27 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:161.13 /195.00 B:60.02 /60.00 @:127 B@:127 W:?
Recv:  T:162.94 /195.00 B:60.00 /60.00 @:127 B@:127 W:?
Recv:  T:164.82 /195.00 B:60.01 /60.00 @:127 B@:0 W:?
Recv:  T:166.65 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:168.44 /195.00 B:59.94 /60.00 @:127 B@:0 W:?
Recv:  T:170.47 /195.00 B:59.87 /60.00 @:127 B@:127 W:?
Recv:  T:172.30 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:174.04 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:175.77 /195.00 B:59.98 /60.00 @:127 B@:127 W:?
Recv:  T:177.54 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:179.23 /195.00 B:60.00 /60.00 @:127 B@:0 W:?
Recv:  T:180.94 /195.00 B:60.00 /60.00 @:127 B@:127 W:?
Recv:  T:182.74 /195.00 B:60.03 /60.00 @:127 B@:0 W:?
Recv:  T:184.45 /195.00 B:60.01 /60.00 @:127 B@:0 W:?
Recv:  T:186.22 /195.00 B:60.00 /60.00 @:0 B@:0 W:?
Recv:  T:187.97 /195.00 B:59.91 /60.00 @:0 B@:127 W:?
Recv:  T:189.14 /195.00 B:60.00 /60.00 @:0 B@:0 W:?
Recv:  T:189.97 /195.00 B:59.96 /60.00 @:0 B@:0 W:?
Recv:  T:190.14 /195.00 B:59.88 /60.00 @:11 B@:127 W:?
Recv:  T:190.06 /195.00 B:60.00 /60.00 @:32 B@:127 W:?
Recv:  T:189.92 /195.00 B:60.13 /60.00 @:50 B@:0 W:?
Recv:  T:189.56 /195.00 B:60.08 /60.00 @:70 B@:0 W:?
Recv:  T:188.88 /195.00 B:60.02 /60.00 @:95 B@:0 W:?
Recv:  T:188.57 /195.00 B:60.00 /60.00 @:107 B@:0 W:?
Recv:  T:188.33 /195.00 B:60.00 /60.00 @:116 B@:127 W:?
Recv:  T:188.33 /195.00 B:60.16 /60.00 @:118 B@:0 W:?
Recv:  T:188.57 /195.00 B:60.08 /60.00 @:113 B@:0 W:?
Recv:  T:189.11 /195.00 B:60.00 /60.00 @:102 B@:0 W:?
Recv:  T:189.69 /195.00 B:59.96 /60.00 @:92 B@:0 W:?
Recv:  T:190.45 /195.00 B:59.95 /60.00 @:79 B@:127 W:?
Recv:  T:191.36 /195.00 B:60.03 /60.00 @:63 B@:0 W:?
Recv:  T:192.24 /195.00 B:60.01 /60.00 @:50 B@:0 W:?
Recv:  T:193.07 /195.00 B:60.00 /60.00 @:39 B@:0 W:?
Recv:  T:193.61 /195.00 B:59.99 /60.00 @:35 B@:127 W:?
Recv:  T:194.09 /195.00 B:60.09 /60.00 @:35 B@:0 W:4
Recv:  T:194.15 /195.00 B:60.05 /60.00 @:43 B@:0 W:3
Recv:  T:194.32 /195.00 B:60.00 /60.00 @:46 B@:0 W:2
Recv:  T:194.20 /195.00 B:60.03 /60.00 @:55 B@:127 W:1
Recv:  T:194.09 /195.00 B:60.00 /60.00 @:62 B@:0 W:0
Recv: echo:busy: processing
Recv: X:220.00 Y:220.00 Z:0.00 E:0.79 Count X:17600 Y:17600 Z:0
Recv: X:220.00 Y:220.00 Z:0.00 E:0.00 Count X:17600 Y:17600 Z:0
Recv: SD printing byte 1111/14677209
Changing monitoring state from "Operational" to "Starting print from SD"
Changing monitoring state from "Starting print from SD" to "Printing from SD"
Recv: ok
Recv: X:10.40 Y:20.00 Z:0.28 E:0.00 Count X:17600 Y:17600 Z:1
Recv: X:10.40 Y:20.00 Z:2.00 E:0.00 Count X:17600 Y:17600 Z:3
Recv: X:10.40 Y:20.00 Z:2.00 E:0.00 Count X:17600 Y:17600 Z:15
Send: M27
Changing monitoring state from "Printing from SD" to "Cancelling"
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: SD printing byte 2109/14677209
Recv: ok
Send: M108
Recv: ok
Send: M25
Recv: ok
Send: M105
Recv: echo:enqueueing "M125"
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: ok T:195.45 /195.00 B:60.00 /60.00 @:57 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M26 S0
Recv: ok
Send: M84
Recv: ok
Send: M105
Recv: ok T:195.45 /195.00 B:60.01 /60.00 @:57 B@:0
Send: M104 T0 S0
Recv: ok
Send: M140 S0
Recv: ok
Send: M106 S0
Recv: ok
Changing monitoring state from "Cancelling" to "Operational"
Send: M27
Recv: Not SD printing
Recv: ok
Send: M27
Recv: Not SD printing
Recv: ok
Send: M105
Recv: ok T:195.20 /0.00 B:59.80 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
Recv: ok
Recv: echo:enqueueing "M24"
Recv: Error:Hotend too cold
Changing monitoring state from "Operational" to "Error: Hotend too cold"
Send: M112
Send: N2 M112*35
Send: N3 M104 T0 S0*34
Send: N4 M140 S0*97
Changing monitoring state from "Error: Hotend too cold" to "Offline (Error: Hotend too cold)"
Connection closed, closing down monitor. I have no printing problems before installing octoprint, so I think it is related to octoprint.

Best regards,
André

**Comment by foosel** [comment]
> Recv: echo:enqueueing "M24"
> Recv: Error:Hotend too cold
> Changing monitoring state from "Operational" to "Error: Hotend too cold"

This is your printer deciding to start the print outside of the control of OctoPrint, and also your printer realising that that won't work because the heaters are of and throwing an error.

You need to figure out what makes your printer enqueue an M24 on its own, but this is not a big in OctoPrint. 

If you need help digging into what's happening here please get in touch on the [community forum](https://community.octoprint.org).
