### ISSUE TITLE
No formatting/scripts when using Apache2 proxy server

### ISSUE THREAD

**Issue by chickenchuck040** [foosel/OctoPrint#386]
I set up Apache2 web server on another computer to be a proxy server for octoprint, but when I connect to it, there is no formatting or scripts at all. It is a bunch of left-justified text. I am using he most recent devel version of octoprint running on a Raspberry Pi. Does anyone know want is going on or how to fix it?

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
