### ISSUE TITLE
Event PrintDone not fired

### ISSUE THREAD

**Issue by frankjoke** [foosel/OctoPrint#434]
I am using Devel and have the following in my config:
<code>
events:
&nbsp;&nbsp;systemCommandTrigger:
&nbsp;&nbsp;&nbsp;&nbsp;enabled:&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;subscriptions:
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;command:&nbsp;/home/pi/sendphoto&nbsp;"Print&nbsp;of&nbsp;{file}&nbsp;finished&nbsp;in&nbsp;{time}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;event:&nbsp;PrintDone
</code>
And it sends no photo. I also have this ins system:
<code>
system:
&nbsp;&nbsp;actions:
&nbsp;&nbsp;-&nbsp;action:&nbsp;Send&nbsp;Photo&nbsp;now
&nbsp;&nbsp;&nbsp;&nbsp;command:&nbsp;/home/pi/sendphoto&nbsp;"Current&nbsp;Photo&nbsp;of&nbsp;{gcode}"
&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;SendPhoto
</code>
And it works!
Where is the problem?

p.s.: Sorry, don't know how to enter code here, it still parses text in the code and does not show spaces right! Had to convert all spaces to & n b s p;!

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
