### ISSUE TITLE
General problem with OctoPrint when GCode Viewer is enabled

### ISSUE THREAD

**Issue by szafran81** [foosel/OctoPrint#444]
Hi,

This is in regard to: Branch: master, Commit: 293611287e312a6b276db50fe364a16524052fd2

I've been using OctoPrint (on RPi) for about a month now (great job btw). Earlier I've done smaller prints (eg. only small gcode files - up to about 10MB). Everything was fine, until last weekend. On friday morning I've started a bigger print job (about 100MB gcode file, and about 30h total print time - generated using slic3r from this project: http://www.thingiverse.com/thing:255980). First problems began rather quickly after starting the print. Chrome tabs started to hang, and I had to close them, and reload OctoPrint in new one.

Then about 6h into the print after another Chrome tab (at that time it was Chrome on Android, but same thing happend on my Laptop under Win8 and on my NAS under Ubuntu and on both I've used Chrome) hanged the print stopped. It just stopped - nothing more. OctoPrint died - no errors in any log files (I've searched OctoPrints logs and system logs - nothing). Since there were no errors etc. the Sangu board kept all the settings as of last gcode sent. That means the bed and the head temp stayed as they were during print. Unfortunatelly I was away at that time. I managed to restart OctoPrint and shut down the temps before it was too late. But it was a close one.

It was like that until today morning - my steps to print something:
1) Launch OctoPrint in a browser (I've tried it even on IE and the same thing happened)
2) Start the print
3) Close the OctoPrint tab in browser
4) Don't try to open OctoPrint in a browser until the print finishes

Today I've managed to make some test - when I've switched off GCode Viewer everything started working fine again.

During the problems there were no errors (doesn't matter if the OctoPrint died or not) in the logs - the prints just stopped if the browser tab was opened too long. No communication errors also.

What I've observed today was that after a few seconds after opening OctoPrint in a browser it starts to download something (probably the gcode file - rather long spikes in bandwidth monitor). After the download completes then the CPU usage goes to 100% and it either hangs the browser in that moment or short after GCode Viewer analyzing completes (CPU usage goes down). And this happens every time I open OctoPrint in a browser (until I've switched off the GCode Viewer).

I don't know if this a bug, or samething that supposed to be happening (downloading the code each time OctoPrint is loaded in a browser - not the hangs - those are probably a bug), but if it's possible it would be better to get the data once, process it and send it back to OctoPrint, which then can save the processed data in a separate file for next time someone loads the UI in a browser. Don't really know how this is processed, but just an idea to speed up stuff.

My conclusion:
GCode Viewer on - bad things happening, prints stop, browser tabs hang etc.
GCode Viewer off - everything is fine.

I haven't used GCode Viewer that much, but sometimes it's really handy, so it would be nice to get it working.

Hope someone can understand what I've tried to explain.

P.S. Today after one of those hangs (actually between hangs) the print was ruined and I've tried to press Cancel (didn't realize that the browser hanged allready) a few times, and that made OctoPrint to launch a couple of timelapse compressions at once (I was a bit frustraded and forgot to make a screenshot, but htop was showing 5 or 6 exactly the same thread - with different thread numbers).

**Comment by foosel** [comment]
Without being able to reproduce this (still...) maybe the fix for #1065 might also help here.

**Comment by foosel** [comment]
@szafran81 have you been able to see if the above mentioned fix attempt for #1065 changed anything in the behaviour for you?

**Comment by foosel** [comment]
@szafran81 Any update on this?

**Comment by foosel** [comment]
No reply from OP, closing.
