### ISSUE TITLE
Que of optional commands to be executed after a print

### ISSUE THREAD

**Issue by korpx** [foosel/OctoPrint#457]
It would be handy with a que of optional GCODE-commands to be executed after a print. A list of commands that can be rearranged, or maybe even as simple as a text field to enter them into. Fully editable during the print. Executed from top down after all the GCODE from the uploaded file is sent to the controller and the print is done.

You could tell the machine to shut down the heat bed, turn on cooling fans, power down at the end of the print even if it is not in the uploaded GCODE

I can think of a number of reasons one would like different things to happen after a print that was not planned for during slicing.

For example when prototyping and printing a series of prints I don't shut down the heat bed between individual prints. If the time estimations are off for a print so it will have to be left unattended for longer than planned or the print has to be slowed down for any reason it would be very useful to be able to tell OctoPrint mid-print to shutdown the heat bed afterwards.

**Comment by foosel** [comment]
Implemented in `devel` (Settings > GCODE Scripts)
