### ISSUE TITLE
Constantly Plagued with SerialException errors.

### ISSUE THREAD

**Issue by NathanSB** [foosel/OctoPrint#460]
Hi there, 

For as long as I have been using OctoPrint I have been getting SerialException errors. Sometimes it doesn't happen for hours (or days) and then other times it causes several prints one after another (moments after cleaning the print bed and starting them again).

I get this in the terminal:

Unexpected error while writing serial port: SerialException: 'write failed: [Errno 19] No such device' @ comm.py:_doSendWithoutChecksum:942
Changing monitoring state from 'Operational' to 'Error: SerialException: 'wr...'
Connection closed, closing down monitor

I am using the following Branch and Commit:

Branch: master, Commit: deb38f84555db9acb148b94de5ba2f307ff1869b

I updating OctoPrint yesterday after learning the correct way to update OctoPrint on my Raspberry Pi and not just the Raspian OS.

It might be worth mentioning that I did not get these errors while printing with either Repetier Host or Pronterface when printing from USB on my laptop.

I hope that is enough information.

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
