### ISSUE TITLE
Asking for example of Application with the API and PHP 

### ISSUE THREAD

**Issue by mpenya** [foosel/OctoPrint#462]
Hello,

I ´m trying to develop an application using the REST API of OctoPrint. I would like to programm a web application with all the operations the API has. 

For the moment, i have no problem with GET operations.

But with POST operations i don´t get good results. After a lot of hours, I cannot upload a file to the server. I´m using Php. I´ve tried Curl and "php Requests"·.

¿Are there any example of a web application that uses the API in php?

Thanks.

**Comment by foosel** [comment]
Sounds like this has been answered, closing.
