### ISSUE TITLE
Feature Request: Custom Commands through Settings page

### ISSUE THREAD

**Issue by Salandora** [foosel/OctoPrint#463]
Hello,

this is a feature request and a work in progress issue, because I'm already implementing it.

What I'm trying to implement is creating custom controls through the settings page.
For 2 purposes:
1. making implementation easier (i always struggle with this nasty yaml) atleast having a gui with all the options is much nicer i guess :-)
2. creating new custom controls without the need of restarting octoprint.

Actually I'm only able to show the existing commands, now it's time for editing and creating :-)

WIP Images:
![customcontrols1](https://cloud.githubusercontent.com/assets/2113125/2874291/dd844ac4-d3df-11e3-8557-818eb9b5e1e3.jpg)
![customcontrols2](https://cloud.githubusercontent.com/assets/2113125/2874292/dd86e50e-d3df-11e3-8c95-2799c9c85273.jpg)

**Comment by jorgempy** [comment]
I want this badly too, please @foosel , can you merge the pull request? pleeease =)

**Comment by foosel** [comment]
I can't because it's broken

**Comment by Salandora** [comment]
Hello @foosel,
I now found some time to update this, after a quick review of the actual code I noticed you made heavy changed to the Control tab which looks like an layout system.

Do you want me to change my code to this layout system?

**Comment by foosel** [comment]
It would probably make sense. Do you have all the information you need? If not, don't hesitate to ask. Also I'm still very much tempted to turn this into a plugin (hence the milestone), that should be possible already and decouple it from the rest of the system (making it easier to maintain)

**Comment by Salandora** [comment]
Making a plug in put of it was also my goal.
The layout system makes it a bit more complicated to get it running again but shouldn't be possible.

Is there anyway to contact you directly?
Because of the Plugin system there are a lot of questions.
e.g. how to include HTML code into the existing code without making hardcore changes.
second: how to replace/override existing Javascript code to make the necessary changes to the process controls function and so on.

**Comment by foosel** [comment]
Just ping me on <my first name> at foosel.net

**Comment by foosel** [comment]
Or join `#octoprint` on irc.freenode.net ;)

**Comment by Salandora** [comment]
Alright when I'm at home I gonna visit you at irc

**Comment by Salandora** [comment]
For everyone interested this is now available as a plug in for the devel branch. You can find it at git hub.com/Salandora/octoprint-customControl it's still in development but you already can use it.

**Comment by jorgempy** [comment]
Wohoo!! Awesome salandora! I'll begin testing tomorrow! Thanks for keeping this feature alive!

**Comment by foosel** [comment]
@Salandora I think we can closer this now?

**Comment by Salandora** [comment]
Yeah I think so too
