### ISSUE TITLE
Timelapse render bar/status

### ISSUE THREAD

**Issue by SelfDestructor** [foosel/OctoPrint#485]
Is it possible to add a progress bar or status box next to recorded timelapses?
A simple "Rendering" and "Finished" message would really help as right now I'm downloading the movie to see if it's finished rendering to the end.

**Comment by foosel** [comment]
Progress bar would necessitate ffmpeg output parsing, haven't yet looked if that's feasible. Status indicators on the timelapse list might be possible, but aren't implemented yet.

But the "Timelapse rendering" notification is now persistent, even across reloads/client switches. That should make it easier to see that a rendering job is currently in progress. 

Available on the `maintenance` and `devel` branches and going to be included in the 1.2.9 release.

**Comment by foosel** [comment]
This has been implemented by the above PR on `maintenance` and `devel` and will be part of 1.3.9

**Comment by foosel** [comment]
1.4.0 has been released.
