### ISSUE TITLE
BeagleBone - init-functions not found after setup.py

### ISSUE THREAD

**Issue by ChrisWeiss** [foosel/OctoPrint#488]
This is probably a docs issue more than anything else - I'm trying to deploy OctoPrint to a BBB using the Angstrom-Cloud9-IDE-GNOME-eglibc-ipk-v2012.12-beaglebone-2013.09.05 image and a git clone from 5/30/14.

I had it set up and working from /home/octo/OctoPrint/run, but wanted to see if I could get it set up using the init scripts. I ran 
```setup.py install```
which seemed to copy things about correctly, and chmod a+x's /etc/init.d/octoprint. When attempting to run /etc/init.d/octoprint, I get the following error:
```/etc/init.d/octoprint: line 37: /lib/lsb/init-functions: No such file or directory```

I'm not too familiar with Angstrom, but apparently it doesn't include init-functions by default, nor does opkg find to install.

Any ideas what to do next?

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
