### ISSUE TITLE
errors in installing webcam for OctoPrint

### ISSUE THREAD

**Issue by molnarjoe** [foosel/OctoPrint#499]
Hi, I'm on the step of the instructions where:
./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so"
I get:
MJPG Streamer Version: svn rev: Unversioned directory
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
ERROR opening V4L interface: No such file or directory
 Init v4L2 failed !! exit fatal 
 i: init_VideoIn failed

Help, I don't know what to do next. I'm just following the instructions verbatim.
Also now the commands raspistill and raspivid no longer work. They worked before I started the install. I get this when I try:

mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

But the camera IS installed correctly!

Also strange things happen when running OctoPrint. When I run ./run, I can get see the OctoPrint web page. But when I try to start it as as a daemon with ./run --daemon start, it seems to take the command, but I get no web page. When I stop the daemon with /.run --daemon stop, I get: pidfile /tmp/octoprint.pid does not exist. Daemon not running?
Then I can't do anything until I restart the pi. Something is very screwey here. I need help telling me what it is.

I don't want to spend my time poking into the depths of Linux, I'd rather spend my all-to-rare free time doing actual 3d printing.

Thanks for any help
Joe

**Comment by foosel** [comment]
No reply from OP, closing

**Comment by 626Pilot** [comment]
For anyone who finds this thread after googling "ERROR opening V4L interface", try this:

sudo modprobe bcm2835-v4l2

You can also put bcm2835-v4l2 into /etc/modules, which will automatically load it on boot.

**Comment by abreumateus** [comment]
Same here, i did this tutorial:

Webcam

If you also want webcam and timelapse support, you'll need to download and compile MJPG-Streamer:

cd ~
sudo apt-get install subversion libjpeg8-dev imagemagick libav-tools libv4l-dev cmake
git clone https://github.com/jacksonliam/mjpg-streamer.git
cd mjpg-streamer/mjpg-streamer-experimental
export LD_LIBRARY_PATH=.
make

This should hopefully run through without any compilation errors. You should then be able to start the webcam server using:

./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so"

Everything works untill the last comment.

Result for command "lsusb":

Bus 001 Device 005: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 004: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter
Bus 001 Device 003: ID 2341:0042 Arduino SA Mega 2560 R3 (CDC ACM)
Bus 001 Device 002: ID 05e3:0606 Genesys Logic, Inc. USB 2.0 Hub / D-Link DUB-H4 USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Result for command "./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so":

pi@octopi:~/mjpg-streamer/mjpg-streamer-experimental $ ./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
UVCIOC_CTRL_ADD - Error at Pan (relative): Inappropriate ioctl for device (25)
UVCIOC_CTRL_ADD - Error at Tilt (relative): Inappropriate ioctl for device (25)
UVCIOC_CTRL_ADD - Error at Pan Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_ADD - Error at Tilt Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_ADD - Error at Pan/tilt Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_ADD - Error at Focus (absolute): Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Pan (relative): Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Tilt (relative): Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Pan Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Tilt Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Pan/tilt Reset: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Focus (absolute): Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at LED1 Mode: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at LED1 Frequency: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Disable video processing: Inappropriate ioctl for device (25)
UVCIOC_CTRL_MAP - Error at Raw bits per pixel: Inappropriate ioctl for device (25)
 o: www-folder-path......: disabled
 o: HTTP TCP port........: 8080
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
libv4l2: error turning on stream: Operation not permitted
Unable to start capture: Operation not permitted
 i: Error grabbing frames

Please help me! :(
