### ISSUE TITLE
Da Vinci 3D printer help.

### ISSUE THREAD

**Issue by rainbowdash** [foosel/OctoPrint#510]
I have a Da Vinci 3D printer that I need help interfacing with. Here is the problem. The printer uses a proprietary system and needs some fiddling about in the octoprint code to make it work with the printer.

While most open source 3D printers use a serial port and gcode to print online or offline, this printer uses some custom commands for basic things and then uses gcode for actual printing. From the thread http://www.soliforum.com/topic/6279/xyzprinting-da-vinci-10-hacking/

>Great work sir.
>The following information may or may not be of use to you. This was all sent to me by >oliver, the creator of the cart hack.
>This is what I found digging through the MAC version. It’s the serial commands its using:
>I tried a few and it works. Just send this for example: XYZ_@3D:8
>I guess this is what you are after:
>"uploadGCodeText"        = "XYZ_@3D:4";
>"latestBlockSent"        = "XYZ_@3D:90”;
>Just need to find out how big each block is.
>Ollie.
>
>
>"prefix"              = "XYZ_@3D:";
>//"disconnect"           = "XYZ_@3D_S10_X";
>//"connect"              = "XYZ_@3D_S10_0";
>//"start print"          = "XYZ_@3D_S10_1";
>//"test case"            = "XYZ_@3D_S10_2";
>//"uploadFirmwareBinary" = "XYZ_@3D_S10_3";
>//"uploadGCodeText"      = "XYZ_@3D_S10_4";
>//"extruder Temperature" = "XYZ_@3D_S10_101";
>//"get standard info"    = "XYZ_@3D_S10_102";
>//"get advanced info"    = "XYZ_@3D_S10_103";

>"disconnect"             = "XYZ_@3D:-1";
>"connect"                = "XYZ_@3D:0";
>"startOnlinePrint"       = "XYZ_@3D:1";
>"test print"             = "XYZ_@3D:2";
>"injectManualCommand"    = "XYZ_@3D:2";
>"uploadFirmwareBinary"   = "XYZ_@3D:3";
>"uploadGCodeText"        = "XYZ_@3D:4";
>"latestBlockSent"        = "XYZ_@3D:90";
>"uploadBinaryDidFinish"  = "XYZ_@3D:91";
>"uploadGCodeDidFinish"   = "XYZ_@3D:92";
>"machineLife"            = "XYZ_@3D:5";
>"read eeprom A"          = "XYZ_@3D:6";
>"read eeprom B"          = "XYZ_@3D:7";
>"machine status"         = "XYZ_@3D:8";
>"printer status"         = "XYZ_@3D:8"; // same as machine status
>"get standard info"      = "XYZ_@3D:201";
>"get advanced info"      = "XYZ_@3D:202";
>//example "XYZ_@3D:101,1"
>//example "XYZ_@3D:101,2"
>//example "XYZ_@3D:103,2"
>"extruder on"           = "XYZ_@3D:101";
>"extruder off"          = "XYZ_@3D:102";
>"extruder Temperature"  = "XYZ_@3D:103";

In order to get info such as bed and extruder temp or waking the system, and sending a file for offline or online print, you would need to use these commands.

Now in order to send offline prints, which someone has written a python script to do so, you would need to calculate some checksum, which is in the process of being reversed engineered. An online print appears to be possible with these codes "XYZ_@3D:0",  "XYZ_@3D:1", "XYZ_@3D:2".

My problem is that I have no clue where to begin modifying the code. Any ideas?

https://github.com/jasongao/DaVinci1.0
http://www.soliforum.com/topic/6279/xyzprinting-da-vinci-10-hacking/

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
