### ISSUE TITLE
Require apikey even when access control is disabled

### ISSUE THREAD

**Issue by mouring** [foosel/OctoPrint#516]
Doing the following results in a HTTP/1.1 200 and the log file:
$ curl -D - 'http://10.0.0.9/downloads/logs/octoprint.log'

Where other API calls without the ?apikey= result in a HTTP/1.1 401
$ curl -D - 'http://10.0.0.9/api/logs/octoprint.log'

I assume this isn't intended behavior, as it isn't expected nor documented behavior.

**Comment by foosel** [comment]
This has actually been fixed since 254145d but I only just noticed when I wanted to tackle this issue here. Took the opportunity to also slightly refactor things. But should be solved in current `devel` builds for some time now.
