### ISSUE TITLE
Feature Request: Pre-heat button + progress bar

### ISSUE THREAD

**Issue by Booli** [foosel/OctoPrint#525]
I'm trying to adapt OctoPrint so I have a useful interface on my 7" screen attached to my printer. I think I'm not the only one on here trying/doing this. 

My feature request(or rather, give me a push in the direction and I will gladly figure it out myself) is to have a simple pre-heat button with a progress bar or even status dot.

Press pre-heat button. Issues M104 command with standard heat(for me around 200C). Run a progress bar that gets info from the 105 or just set a status dot from red to green if target temperature is met. 

I'm slowly but surely getting to understand Knockout and the view model system but I need a little help / code snippet to make this work. 

Thanks!
Booli

**Comment by foosel** [comment]
Closing as discussed on IRC, not relevant any more.
