### ISSUE TITLE
Feature Request: Filament Detection - M300 error virtual machine

### ISSUE THREAD

**Issue by Booli** [foosel/OctoPrint#526]
Hi all,

I'm trying to build in a filament detection mechanism in my printer. The hardware is already done and so is the firmware(it will send a serial msg after a period of time if there is no signal from the hardware rotary check)

The problem is that I can't seem to be able to hook a command to a special serial string I send. I looked into the code and it seems that I can use an event called "Alert" triggered by a M300 code which then will issue a command? Can I issue commands after I read something with 'feedback' ?

I tried issuing the M300 code in the virtual printer but I get the following error:

```2014-07-30 15:45:11,890 - SERIAL - DEBUG - Send: N10 M300*17 2014-07-30 15:45:11,896 - SERIAL - DEBUG - Unexpected error while writing serial port: IndexError: 'list index out of range' @ comm.py:_doSendWithoutChecksum:1124 2014-07-30 15:45:11,896 - SERIAL - DEBUG - Changing monitoring state from 'Operational' to 'Error: IndexError: 'list in...' 2014-07-30 15:45:11,968 - SERIAL - DEBUG - Connection closed, closing down monitor```

Same with the other issue I opened, I will gladly help and try and do it myself I just need a little push in the right direction.

**Comment by foosel** [comment]
Closing this as discussed on IRC. Can be achieved through GCODE command hooks on `devel` (documentation forthcoming)
