### ISSUE TITLE
[Feature Request] Add the abillity for OP to parse g-code markers

### ISSUE THREAD

**Issue by szafran81** [foosel/OctoPrint#536]
Hi,

It would be very nice for OP to be able to parse optional g-code markers. First I thought thet it would be great to move start and end g-codes to OP, but there would be more uses for this (eg. start/stop timelapse etc.).

One could put in slicers start g-code a comment like this:
```
; [OctoPrint-START-GCODE]
```
which then would be replaced on the fly by OP to the start g-code supplied in settings.
Same with end g-code.
This way i someone would like to change something in the start or end g-codes then they wouldn't have to recreate a whole bunch of g-code files, but only change one or a few lines in settings.

It also would be nice to use something like:
```
; [OctoPrint-TIMELAPSE]
```
to start/stop timelapse creation, that way the timelapse videos wouldn't contain the time it takes for the bed to heat-up etc.

**Comment by foosel** [comment]
This is already possible via plugins (specifically gcode hooks) as available in the `devel` branch, documentation is still missing but forthcoming.
