### ISSUE TITLE
[Request] Begin print after slicing

### ISSUE THREAD

**Issue by thantik** [foosel/OctoPrint#540]
So, CuraEngine integration is amazing, but given that the Pi and other boards take a while to actually get the slicing finished, I'm sure some people just want to load up the file and leave while it's slicing/printing.  Right now, you've gotta wait for the slicing to get done before starting the print, potentially wasting a bit of time.

Just a suggestion to add some sort of "Print after slicing" option.

**Comment by foosel** [comment]
Related: #272

**Comment by foosel** [comment]
Oh... actually fixed in `devel`, new slicing dialog includes an option to either select for or directly start printing the file after slicing finishes :)
