### ISSUE TITLE
Timelapse doesn't render video from stills

### ISSUE THREAD

**Issue by gojibogyo** [foosel/OctoPrint#547]
Getting this error on the main branch of octoprint running on a raspberry pi with raspbian, not octopi.
After I activated timelapse and do a print, the stills are correctly created in the .octoprint/timelapse/tmp folder, but it seems, the video creation never starts. There are also no videos appearing in the octoprint interface and a cat octoprint.log shows this:
Traceback (most recent call last):
  File "/home/pi/OctoPrint/src/octoprint/events.py", line 50, in _work
    listener(event, payload)
  File "/home/pi/OctoPrint/src/octoprint/timelapse.py", line 288, in _onZChange
    self.captureImage()
  File "/home/pi/OctoPrint/src/octoprint/timelapse.py", line 192, in captureImage
    filename = os.path.join(self._captureDir, "tmp_%05d.jpg" % (self._imageNumber))
TypeError: %d format: a number is required, not NoneType

Branch is master, commit is 36d1522f01f0b0f96049ce2cb21555ed709e2adb
update: branch: master, commit: 48dc27e1060393b0b4e98f25358711d73bf2b7f5 , same problem

Maybe this is just an avconf error, I don't know, but in any case I also don't know how to fix it. Right now I just can download the images after each print and create a timelapse video manually.
Link to the octoprint.log: http://pastebin.com/a6qucpqT
Link to the terminal output in octoprint: http://pastebin.com/t7VV5Rj3
I love cookies

**Comment by foosel** [comment]
No response from OP, closing.
