### ISSUE TITLE
User access control does not work well when different computers/browsers are used

### ISSUE THREAD

**Issue by AmedeeBulle** [foosel/OctoPrint#556]
It took me some time to understand what was happening...

Here is the scenario:
- On one computer, login in Octoprint with 'Remember me', then close your session (that is, close the browser, but don't logout)
- On another computer (or a different browser on the same computer), login again and close your session.
- Go back to the first computer/browser: your are still logged in (as expected), but you have lost privileges -- e.g. you cannot run system actions, they will return 'Error, The command "..." could not be executed'. More shows 'Forbidden'.
- Try to logout: it is like in Hotel California, you can never leave ;) The only way to logout is to delete your cookies (and btw, I love cookies).

Environement:
OS: raspbian on rasberry pi (no OctoPi)
Octoprint:: Version: 1.2.0-dev-118-gfbd9440

Logs:
Attempt to logout generates a stack trace: https://gist.github.com/AmedeeBulle/f2a02d86aee4f8c8dea0
No other error.

It is a 'fresh' install form a couple of days ago, so all libraries should be current. As it seems related to Flask, i have:
```
Flask==0.9
Flask-Login==0.2.2
Flask-Principal==0.3.5
```
My python skill are somewhat limited, can't drill down much more on this...

**Comment by foosel** [comment]
Considering this solved due to not getting any reply from OP and my tests so far looked good.

**Comment by AmedeeBulle** [comment]
Apologies for no answer...
I am running this version for about a month, and I have not been able to reproduce since then, so indeed this should be closed.
