### ISSUE TITLE
[Support] Still getting pauses on commRefactoring branch

### ISSUE THREAD

**Issue by BJClark** [foosel/OctoPrint#568]
1. What were you doing?
Printing.

2. What did you expect to happen?
Smooth continuos printing.

3. What happened instead?
Lots of pausing mid print

4. Branch & Commit or Version:
HEAD on commRefactoring

5. Printer model & used firmware incl. version
Raspberry Pi to a Printrbot (Plus v2 with a rev D board) original 2013 firmware

6. Link to octoprint.log on gist.github.com or pastebin.com:

7. Link to contents of terminal tab on gist.github.com or pastebin.com:
https://gist.github.com/BJClark/47740fdaf14f6fdca775

Is this maybe another issue not fixed in the commRefactoring branch? Is there anyway to verify in the UI that I'm actually running on the commRefactoring branch? I followed the steps to change branches, but I'm not 100% sure the install worked.

Here is the output (partial, in the middle of a print) with what I'm seeing:

`Communication timeout during printing, forcing a line
Send: M105
Communication timeout during printing, forcing a line
Send: M105
Recv: ok T:199.52 B:49.98 @:92
Send: N49513 G1 X58.827 Y169.757 E11.05820*108
Communication timeout during printing, forcing a line
Send: M105
Recv: ok T:199.97 B:49.46 @:84
Send: N49514 G1 X57.929 Y170.031 E11.10783*102
Recv: Error:Line Number is not Last Line Number+1, Last Line:49511`

**Comment by foosel** [comment]
There are more than enough tickets already that are related to the communication stuff, closing this one.
