### ISSUE TITLE
[Request] Pause->Home XY->Continue Button?

### ISSUE THREAD

**Issue by SeveQ** [foosel/OctoPrint#571]
For the times that I hear one of my printer steppers losing steps I'd like to have a button that does the same as clicking pause, home X/Y, and continue sequentially. With the printer set to absolute coordinates this procedure results in eliminating the unwanted offset caused by the lost steps. Can I do this myself or does it require the OctoPrint core to be altered?

**Comment by foosel** [comment]
Duplicate of #366
