### ISSUE TITLE
[Request]: show "print time left" on the ulticontroller alike, by means of M117

### ISSUE THREAD

**Issue by MoonCactus** [foosel/OctoPrint#596]
Could Octoprint update the display in real time with the "print time left" that is seen in the web interface?
This could be done by inserting M117 messages in the gcode stream.

**Comment by VBen** [comment]
@MoonCactus 
Do you already use [this "DetailedProgress" plugin](https://github.com/dattas/OctoPrint-DetailedProgress)?

**Comment by MoonCactus** [comment]
@VBen I was way too far from 3D printing for the last months to stay on track, but thanks for the link: this plugin seems quite nice indeed! I will tell after I find the time to fix a few more of my printers again (they really like to fail when left unused for a while, and my old ultimaker 1 has been hacked almost to death).

**Comment by foosel** [comment]
Oops, I think this can be closed :)
