### ISSUE TITLE
[Support] Getting Octoprint to work with Sailfish

### ISSUE THREAD

**Issue by NathanSB** [foosel/OctoPrint#605]
Hi there,

So I have a Flash Forge Creator Pro that I am trying to get to work with OctoPi.

I have read around the web and I found this:

https://bitbucket.org/jwellman/octopi/src/158de1a1d28f?at=master

However I am unsure as what to do with it?

It says to install the .egg drivers located in the MaerBot program files (which I found) However I am unsure how to install this on the Pi and also how to remove the pyserial from my environment..

Would someone be able to provide a de-mystified version of the details needed to install this version of OctoPi to get it working with Sailfish?

These are the instructions I am referring to:

IMPORTANT...READ THIS!
This was forked off of the master OctoPrint repo on GitHub.
To get this working with S3G (MakerBot) you'll need to do the following in addition to the normal setup instructions:
1 - Install the makerbot_driver egg that comes with MakerWare. On windows this is found at: C:\Program Files\MakerBot\MakerWare\python\makerbot_driver-0.1.1-py2.7.egg
2 - Remove pyserial from your environment and install the one that comes with MakerWare: C:\Program Files\MakerBot\MakerWare\python\pyserial-2.7_mb2.1-py2.7.egg
3 - Launch OctoPrint and go to Settings>>Serial Connection. For the "Printer Protocol" select S3G. You will need to restart the OctoPrint server for this to take effect.

Kindest regards,

Nathan

**Comment by foosel** [comment]
Closing this, also see #332.

Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)

**Comment by markwal** [comment]
@NathanSB I've made a new start based on the devel branch.  https://github.com/markwal/OctoPrint-GPX
