### ISSUE TITLE
Makerbot Replicator Dual

### ISSUE THREAD

**Issue by bubbltrubl** [foosel/OctoPrint#61]
Is the Makerbot Replicator Dual (first generation) supported by OctoPrint, because we are unable to connect to the printer. When I plug in the printer via USB a see "/dev/ttyACM0" appearing in the Serial Port Select Box but whatever baud rate I choose, I can't connect.

Any ideas?

**Comment by markwal** [comment]
BTW I've got this working as plugin in foosels cool new plugin system: https://githib.com/markwal/OctoPrint-GPX. My printer is actually a clone, but it should work with MakerBot too. Give it a try and let me know if it works.

**Comment by markwal** [comment]
@foosel, I think we can close this one now.  What do you think?

**Comment by foosel** [comment]
Yup, we can.
