### ISSUE TITLE
Zooming out in Chrome and Firefox breaks gcode viewer layout

### ISSUE THREAD

**Issue by korpx** [foosel/OctoPrint#612]
1. What were you doing?
On my 1600x900 screen the interface is huge, so using the zoom in the web browser is a good way to remedy this. Since a while back zooming out anything less than 100% breaks the layout of the gcode viewer in Chrome and Firefox. Internet Explorer 11 works.

2. What did you expect to happen?
All elements should zoom gracefully and retain the layout.

3. What happened instead?
The gcode viewer is split in two elements where the top element is blank and keep the vertical slider. The lower element contain the gcode visualization and the horizontal slider.
![image](https://cloud.githubusercontent.com/assets/1850308/4619689/d5d18af0-5317-11e4-99f7-cc5249a36407.png)

4. Branch & Commit or Version:
Version: 1.1.0-7-g62a51bb (master branch)

5. Printer model & used firmware incl. version
Ord bot Hadron, Ramps 1.4 electronics. Marlin1.0.0.

I love cookies

**Comment by foosel** [comment]
Fixed in `devel` branch.
