### ISSUE TITLE
[Request] Timelapse picture taken from same XY position every time for Z-change

### ISSUE THREAD

**Issue by Nurgak** [foosel/OctoPrint#621]
I have a printer that moves its bed in X direction (Printrbot Simple Makers's kit 1405) and my camera is fixed on the printer (not moving), making any timelapse video very blurry.

One solution would be to attach the camera on the bed, but that poses some annoying cabling problems. Another solution would be to make the pictures when the bed is at the same position every time, this would effectively remove the part-moving-blur-effect, so instead of only z-change the timelapse would also need to move the head to a defined XY position before a picture.

I guess the naive way to do this would be in inject some gcode after every z-change that would move the bed to a fixed position (let's say center), take the picture, move the head back where it was and resume printing.

**Comment by foosel** [comment]
Closing this due to not being feasible.

**Comment by Eno423** [comment]
I know this is closed..but I think this is what the op is requesting 

http://www.makermusings.com/2015/09/01/making-time-lapse-video-of-3d-prints/

**Comment by foosel** [comment]
@Eno423 That ``@execute`` pseudo command could easily be done via a plugin these days (roughly 20 lines of code maybe) if someone writes it ;)

**Comment by totalitarian** [comment]
Such a plugin exists here https://github.com/kantlivelong/OctoPrint-GCodeSystemCommands
