### ISSUE TITLE
[Request] Be able to adapt to temperature higher than 310°C

### ISSUE THREAD

**Issue by imitation** [foosel/OctoPrint#632]
The temperature monitor seems to be hardcoded for a range of 0°C to 310°C. Temperatures higher than 310°C are not shown, so when printing polycarbonate (or other fancy new materials), the monitor becomes useless at times.
Suggestion: Auto-scale the monitor's range in steps of 50°C, depending on the set and actual temperatures.

**Comment by foosel** [comment]
Implemented in `devel`.
