### ISSUE TITLE
[Request] Option to require login for entire web site

### ISSUE THREAD

**Issue by Sibanamush** [foosel/OctoPrint#640]
Since Octoprint is intended to be accessible on the internet , I was quite surprised that there isn't currently an option to require a user log in to the website  before being able to view content ( especially being able to view the webcam feed )

I am requesting a feature that would add an option that would require users to sign in to the webpage at either user or administrator level before being able to view the website. This would allow people to keep their Octoprint accessible from the internet, but would provide a layer of privacy and security if they do not wish their Webcam feed, current print, machine status , and files on the system to be viewable to anyone who visits the website. This would also add more purpose to the non admin user account level.

**Comment by foulowl** [comment]
+1 from me for the following feature: the ability to hide all features until user logs in.

I could do basic auth of course but the login popup is pretty ugly.

I would imagine that simply hiding elements might not be too much work either!

**Comment by foosel** [comment]
> I would imagine that simply hiding elements might not be too much work either!

Read https://github.com/foosel/OctoPrint/issues/640#issuecomment-64048544 above again, then think about what you just said.

**Comment by foulowl** [comment]
Sorry, when I saw the thread getting heated I kind of glossed over the rest. Sounds like it will be a lot of work!

**Comment by foosel** [comment]
Closing this since it is now tracked as part of #1110.
