### ISSUE TITLE
[Support] Problems with setup on Mac

### ISSUE THREAD

**Issue by designermx2** [foosel/OctoPrint#649]
Your link not work. Only success with this:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by foosel** [comment]
Let's try to get this bug tracker back to its original purpose: Tracking bugs.

Support requests should be redirected to the Mailinglist or G+ Community, please ask there if the problem still persists, there are probably more people who might be able to help.

(Yes, I'm looking into a proper support forum)
