### ISSUE TITLE
Problem printing .gcode file with G4 (dwell) commands

### ISSUE THREAD

**Issue by vishnubob** [foosel/OctoPrint#658]
1. What were you doing?

  I am experimenting with the [G4](http://reprap.org/wiki/G-code#G4:_Dwell) command, which causes the printer to "sleep" for a specified amount of time.  The .gcode file I'm printing has 32 dwell commands, with each command pausing for 20 seconds.  I think the same issue is reported in #194, but the author only had one dwell command and was able to re-order his .gcode file in such a way that circumvented this problem.

  Here is a [copy](https://gist.github.com/vishnubob/f1048b2c7f05e2451879) of the .gcode file I'm trying to print.  You can easily recreate the problem by adding multiple "G4 S20" to any .gcode file.

2. What did you expect to happen?

  I expected the print to finish to competition.

3. What happened instead?

  The OctoPrint serial command streamer choked.  I've tried this twice, and experienced two different outcomes with the same conclusion, the command streamer/serial connection crashes.

  My first attempt was able to print past the first few dwell commands.  After the third dwell command, the printer would recover, but would "stutter", as if the stream of commands it was receiving were arriving at irregular intervals.  After the fifth or sixth dwell command, the print completely failed.  My second attempt failed immediately after the first dwell command.

  Printing from an SD card works perfectly, so it's not the .gcode.

4. Branch & Commit or Version:

  1.2.0-dev-242-g084ca95

5. Printer model & used firmware incl. version

  Ultimaker Original with Marlin v1 (110c5dc)

6. Link to octoprint.log on gist.github.com or pastebin.com:

  https://gist.github.com/vishnubob/7b7d88671275634ae999

7. Link to contents of terminal tab on gist.github.com or pastebin.com:

  https://gist.github.com/vishnubob/5820b13d5e444e53e98c

I love cookies

**Comment by foosel** [comment]
Pinging Dr @vishnubob , Dr @vishnubob to the issue ER please ;)

**Comment by foosel** [comment]
Hm... If I'm mistaken in closing this, please reopen, but for now I'll consider this fixed after my own tests of your own PR.
