### ISSUE TITLE
Line Number is not Last Line Number+1

### ISSUE THREAD

**Issue by Arengorn** [foosel/OctoPrint#660]
I finished building my Prusa i3 about 3 months ago, and I've always used Octoprint with it. It worked well for about 2 weeks untill the "Line Number is not Last Line Number+1" error started. I was too busy to fix it, so I just left the 3D printer aside for a couple of months. This week I was determined to fix it and, surprisingly, the printer worked absolutely fine.For 4 prints. Now I get the same annoying "Line Number is not Last Line Number+1" error on every print, and there is no cable replacement, change in position or prayer that fixes it. Someone suggested for me to just filter out the line numbers of the serial com, but I don't know how to do so. Is there an absolute fix for this?

##### Log (Starts after Auto Bed Leveling routine, G28 G29):
https://gist.github.com/Arengorn/d7b540798d7244d2658f

**Comment by foosel** [comment]
Don't use BAL myself, however I just realized that this ticket is actually pretty much the same problem that is described in #553 - therefore closing it as a duplicate.

**Comment by Arengorn** [comment]
True, both have the same root and are a pain to fix.
