### ISSUE TITLE
[Request] Script + buttons

### ISSUE THREAD

**Issue by MLWORKX** [foosel/OctoPrint#674]
RepetierHost has e.g. 5 slots for self written sripts which I use for load and unload extruder 1 and 2 plus switch my LEDs on on slot 5

Really nice would be to be able to have 10 slots for scripts:
- name the scripts as defined by the user
- creating a script creates a button at the buttom of the control panel

**Comment by rspeed** [comment]
Sounds like a duplicate of #463.

**Comment by MLWORKX** [comment]
ohh, haven't seen that- #463 is exacly what I need!

**Comment by foosel** [comment]
Custom controls are already a thing, just edit your ``config.yaml`` for now.
