### ISSUE TITLE
Printer profiles do not save extruder offsets (for first extruder)

### ISSUE THREAD

**Issue by imitation** [foosel/OctoPrint#677]
Printer profiles do not save extruder offsets, they always reset to 0. 
log: http://pastebin.com/S8S3vMRE
Version: 1.2.0-dev-340-g85a567b (devel branch) [newest as of post]

Do I love cookies? I don't know anymore. Christmas started too early this year.

**Comment by foosel** [comment]
@nophead on `master` there's a checkbox under "Printer Parameters" in the Settings. On `devel` it's now part of the Printer Profiles (also available through the Settings):

![image](https://cloud.githubusercontent.com/assets/83657/5705845/65091a70-9a7c-11e4-9f6b-e1f9bed2943a.png)

I'm a bit puzzled actually that the GCODE viewer doesn't show the previews centered on (0,0) for you.

**Comment by nophead** [comment]
I don't have that tickbox, must be too old a version. Version: 1.1.0 (master branch)

TBH the gcode preview hardly ever does anything. When it does show up the print is in the middle of the grid, my gcode is always centred on 0,0.

**Comment by foosel** [comment]
FYI, the "additional option to set the print bed origin" is now tracked in #682.

This one is still left open until I've either removed the offsets for single extruder printers or made the first extruder offset fields read-only (probably the former though)

**Comment by foosel** [comment]
Fixed now. Offset for first tool (which is the reference) is now not displayed anymore, offset configuration in general only shows up if more than one extruder is configured, starting with the offset of T1

**Comment by foosel** [comment]
![image](https://cloud.githubusercontent.com/assets/83657/7469268/a0170bca-f311-11e4-8c95-9c9e5c239c7e.png)
