### ISSUE TITLE
JavaScript syntax error calling WebSocket ctor when url port is blank in IE 11

### ISSUE THREAD

**Issue by foofoodog** [foosel/OctoPrint#678]
It appears that IE 11 does not like having a colon in the socks URI when there is no port.
This causes things like file deletes to not update the file list.
Fix may be to not use the colon if you have no port.
```
var SOCKJS_URI = window.location.protocol.slice(0, -1) + "://" + (window.document ? window.document.domain : window.location.hostname) + (0 === window.location.port.length ? "" : ":" + window.location.port) + "/sockjs";
```

@GitIssueBot I love cookies

**Comment by foosel** [comment]
That was fixed "accidentally" by switching over to using ``url_for`` instead of creating the URL for the SockJS endpoint manually.

**Comment by foofoodog** [comment]
>>That was fixed "accidentally"
It was fixed "incidentally" as part of a code refactor. 

Not seeing a link to a user story, work item or commit that shows all of the "url_for" work that this was swept up in.

**Comment by foosel** [comment]
23387d6e48c82efd4b40dfacb449466a54681b99
