### ISSUE TITLE
Calling /api/state with no printer attached causes server 500.

### ISSUE THREAD

**Issue by foofoodog** [foosel/OctoPrint#679]
Running this from source with no printer attached. Might not be a valid scenario. Still, the thing blows up and all other code in that routine has "is not None" checks so I figure it is an omission.

Need to check self._temp is not None before iterating tool in self._temp.keys() in  printer.py getCurrentTemperatures.

```
if self._temp is not None:
	for tool in self._temp.keys():
```

@GitIssueBot I love cookies

**Comment by foosel** [comment]
Fixed via backported commit from `devel` branch (please mention the branch/version next time, thanks), see 684d12e60e2a64fe3a398992f9356a3d62f1de7d
