### ISSUE TITLE
[Request] Allow Bed position to be set in gcode viewer

### ISSUE THREAD

**Issue by thinkl33t** [foosel/OctoPrint#682]
![screenshot from 2014-12-16 23 40 53](https://cloud.githubusercontent.com/assets/1016780/5464203/1058b1f2-857d-11e4-9fde-b57653950be6.png)

My bed center is at [0,0], not the usual [100,100], which means the grid on the gcode viewer is off to one side.  Not a major issue, but a config variable to set the bed's width, height, and 0 position would be very nice :)

**Comment by stv0g** [comment]
Having the same problem. :+1:  Especially for Delta Robots where parts are centered around the origin coordinates.

**Comment by foosel** [comment]
@stv0g for delta robots you can just set the print bed to be circular, this will automatically make the origin be in the center. While you need the `devel` branch for that, this actually IS already possible. 

This ticket is actually about an arbitrary center location for rectangular beds, which is NOT yet possible, not even in `devel`.

**Comment by stv0g** [comment]
Oh thanks @foosel So I will check out the devel branch :-)

**Comment by foosel** [comment]
THanks to work by @markwal, that's now available on `devel`. No arbitrary location on the printbed, but you can choose between "center" and "lowerleft" for rectangular beds. Circular beds are limited to "center" for now.
