### ISSUE TITLE
[Request] Swapping control tab contents

### ISSUE THREAD

**Issue by smartroad** [foosel/OctoPrint#696]
Hi,

I was wondering if it would be possible/good idea to switch the image and controls order in the 'Control' tab?

When you go to the tab it has to load the image, this means that for a few seconds the controls are at the top of the tab. Once the image loads then controls suddenly jump down to the bottom of the image.

If the image was below the controls then they would stay in the same place even after the image has loaded.

As an alternative, assuming people like the image above the controls :grin:, then could a place holder image be inserted that is the same size as the preview so the buttons then do not move?

(as a side note, why does the grin emoticon on github look like it is constipated?! LOL)

**Comment by foosel** [comment]
Swapping could be done via a plugin but since a lot of people have custom controls that span a couple of screen pages it would basically render the webcam view useless for observing manual control input.

A webcam placeholder is already tracked in #478, hence I'm closing this as a duplicate.
