### ISSUE TITLE
[Request] GCode Viewer Defaults

### ISSUE THREAD

**Issue by chadwalber** [foosel/OctoPrint#702]
Every time I open the GCode Viewer Tab, I have to set the renderer options. Is there a way to make these options the defaults for when I load the tab?

**Comment by Klikini** [comment]
Could the last-used options be set per-user in users.yaml?

**Comment by chrisbcole** [comment]
I also find this frustrating.

**Comment by eboston** [comment]
And how about adding an option to control how big a gcode file is before triggering the "it's too big"  warning.

**Comment by Klikini** [comment]
Yes, I get that for files that I have no problem with.

**Comment by asraelis** [comment]
I can not watch gcode viewer if I am using large gcodes as well. Unfortunately I can not see the gcode viewer after clicking on "OK" as well :-(. 
Anyway it's a super printing software and I am happy that I decided to use octoprint ;-)

**Comment by foosel** [comment]
Duplicate of #443
