### ISSUE TITLE
[Request] Controlling a relay board while using OctoPrint on a Raspberry Pi

### ISSUE THREAD

**Issue by mlkoch** [foosel/OctoPrint#704]
It would be a great step when this would be possible from the web-interface of OctoPrint!
See:
https://github.com/foosel/OctoPrint/wiki/Controlling-a-relay-board-from-your-RPi

Best regards!
Michael

**Comment by connerk** [comment]
M codes 80 & 81 switch power pins through the printer electronics. I'Ve got on and off switches in Octoprint this way. What electeonics you running?
