### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by F3000** [foosel/OctoPrint#706]
1. So i finally build up my rasberry pi with octopi
2. I expected, that i can read the whole error state on the left side of the Octoprint homescreen
3. Instaed i can only read half of the sentence ;(
![error](https://cloud.githubusercontent.com/assets/8161283/5628589/b8e72970-95a9-11e4-9fae-bd1556e95386.PNG)

4. Branch Version 1.1.1.1-14-g87
5. I have the RF1000 printer from conrad electronics (germany)
6. -
7. 

![error2](https://cloud.githubusercontent.com/assets/8161283/5628648/7bf6d8f2-95aa-11e4-904e-42a2721f1326.PNG)

![error3](https://cloud.githubusercontent.com/assets/8161283/5628651/814e2922-95aa-11e4-8b4b-60284a27332e.PNG)

I hope anyone can help me and yes i love cookies ;)

**Comment by foosel** [comment]
Have you tried increasing your communication timeout? => [FAQ](https://github.com/foosel/OctoPrint/wiki/FAQ#i-see-a-lot-of-communication-timeout-messages-in-the-log)

**Comment by derpicknicker1** [comment]
I think its not about the error but about reading the whole error message. But the message gets turncated.
I think it was something like 
"Changing monitor state from 'printing' to 'Error: Printer requested line %d but no sufficient history is available, can't resend %lineToResend"
