### ISSUE TITLE
[Request] UPS Blackout Support

### ISSUE THREAD

**Issue by nacho693** [foosel/OctoPrint#749]
Bare with me as I've never posted to Github and maybe this is a plugin issue but perhaps there's a sufficient base interest along the lines of the webcam feature to garner automatic save and powerdown features in the even of a brownout or blackout.  I understand there's a debian package for APC that integrates with the consumer units' USB.  Even a feature to keep the hotbed on at a reduced at a working temperature for as long as possible in case power resumes and printing can restart.

**Comment by foosel** [comment]
You could probably easily achieve that via some shell script that gets called if a brownout or blackout is detected and then uses ``curl`` to set the temperatures via the [API](http://docs.octoprint.org/en/master/api/index.html). if you want to get extra fancy (and run the ``devel`` branch), a plugin of course would also be a nice option. The functionality is too obscure though to add to the core system.
