### ISSUE TITLE
[Request] Have software version check and auto update option

### ISSUE THREAD

**Issue by foofoodog** [foosel/OctoPrint#754]
Wondering if it would be possible for the software to offer an auto update option to run the git pull, the setup.py clean/install and the service restart. Might only apply to me running Octopi on several devices and being lazy about updating them to get fixes. Bonus points if we could switch between master and devel branches. 

I love cookies and cookies love me.

**Comment by foosel** [comment]
One step ahead: https://github.com/OctoPrint/OctoPrint-SoftwareUpdate

Not properly documented yet, and depends on the plugin system present in the devel branch, but fully functional.

**Comment by foofoodog** [comment]
Very cool, and it backs up my local changes if I have any as a patch, that is a nice touch.
