### ISSUE TITLE
GCode viewer not showing the right thing

### ISSUE THREAD

**Issue by gege2b** [foosel/OctoPrint#756]
Hi all, I have read the FAQ so to be sure to not being dropped, I'll copy/paste the guidelines ;)

1. What were you doing?
Printing a plater containing 8 objects, sliced with Slic3r, and using the "Print one object at a time" feature
This feature completes one object before jumping to the next, instead of laying down the first layer of all objects

2. What did you expect to happen?
The Gcode viewer to show the real toolpath, one object at a time, to check before printing

3. What happened instead?
The Gcode viewer show all objects, at the same time (like for a normal slice)

4. Branch & Commit or Version of OctoPrint:
    Version: 1.1.1-25-gf32c977 (master branch)

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure):
Not applicable, but it's a homemade Prusa Mendel (the first iteration) with Marlin v1 on sanguinololu 

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure):
Firefox 35.0.1 on win7 x64

7. Link to octoprint.log on gist.github.com or pastebin.com: 
http://pastebin.com/0Aw110Y5 (its just the evening session, not the whole log)
there is some errors, but I don't know if they are related

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure): serial log is empty, terminal tab just show the same thing

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com (if applicable - 
   always include if unsure): Oops, forgotted

10. Screenshot(s) showing the problem (if applicable)
Screenshot is not applicable here, but here is a link to the Gcode causing this little bug
https://dl.dropboxusercontent.com/u/34934879/20150205-144629-tentacle_segment_supported_0.2-15%25.gcode.zip

Anyway, when printing, the Gcode viewer effectively shows what it is supposed to show : one object, layer by layer, and then the other, etc...
And the print goes well, so it's just a matter of aesthetics

Cheers

**Comment by foosel** [comment]
I understand the problem, however changing that behaviour would necessitate basically rewriting the internals of the gcode viewer (which currently stores the commands per physical layer, so anything that's on z0.1 is in the same part of the data model) plus a new approach to presentation in the UI to allow to properly visualize the print manually.

While I completely agree that it would improve aesthetics I don't see a sane cost-value-ratio here to be honest.

That being said, I'm currently in the progress of making OctoPrint adaptable through plugins, and I've laid the ground work for allowing plugins to replace core functionality. So it might be that once that stuff works there might be someone who adds an alternative gcode viewer that does just that.
