### ISSUE TITLE
[request] More than one camera

### ISSUE THREAD

**Issue by Lord2Vader** [foosel/OctoPrint#762]
Hi,

would it be possible to implement the feature of using more than one cam?

**Comment by MLWORKX** [comment]
+1 on this!    :+1:

**Comment by jneilliii** [comment]
+1 on this for me as well.

**Comment by Reisperbachtal** [comment]
+1 That would be a nice feature, and if possible also timelapses with picture in picture!

**Comment by foosel** [comment]
Duplicate of #401
