### ISSUE TITLE
[Request] Send arbitrary Gcode via REST API

### ISSUE THREAD

**Issue by dustMason** [foosel/OctoPrint#765]
I was just looking over the docs and don't see a way to send arbitrary gcode via the new API. Did I miss it? Or has it been omitted for a reason?

**Comment by foosel** [comment]
[Have you checked on the wrong branch?](http://docs.octoprint.org/en/devel/api/printer.html#send-an-arbitrary-command-to-the-printer)

**Comment by dustMason** [comment]
Thanks! I guess I did
