### ISSUE TITLE
Filament Odometer

### ISSUE THREAD

**Issue by jjg** [foosel/OctoPrint#8]
Not sure if this belongs in this application or not but having feedback on how much filament remains becomes important when you're not sitting there watching the reel unwind :)

My printer doesn't have any awareness of this, but it would be nice if I could tell the PrinterWebUI when I load a new reel, specify the length and have it keep track of how many mm get consumed by each job so I can have a ballpark idea as to if there's enough left before I submit a new job.

I realize that it's not going to be super accurate, but it might prevent me from submitting a big print remotely only to find out it ran out half way through.

**Comment by mogorman** [comment]
+1

**Comment by gddeen** [comment]
Did jjg take his code and run? Are there any requirements?
Something like this? Or just pull from the history log?
Or just pull the history log code?

Requirements:
- Assign reels to extruders via plugin UI panel? Or control tab?
- Support multiple reels with ID. 'RED', 'BXQ236&ggH'
- At beginning of job, tag 'reel log' with the print.
- At the end of job, tag 'reel log' with the print and filament consumed.
- In plugin, present reels and have 'tally' button to scan 'reel log' and present length.
- To fix a reel log when someone actually knows how much their is (IE weighing reel, the user edits log and puts in values for consumed during print. negative values are OK...)
- In plugin, have 'delete' button to remove log.
- In plugin, have 'create new & edit' a reel with ID, Manufacturer, Store, Store reference, Color, Link, Est Length, Weight, Min temp, Max temp, density, Spindle Dimensions, Cost????

Each 'reel log' Contains
'Create' in XML format all the fields the user cared to enter.
'Start' A mark to start a print, date/time, print file.
'Complete' A mark when finished, date/time/file/length, 
'Fail' date/time, maybe the 'N' for file last output to printer.
(I'd have to go research, but in all my prints, the E value would be somewhat dead on but I'm clueless about any other printer/slicer. I see GCodes that reset everything to 0 [XYZEEEE])

**Comment by jjg** [comment]
Did I ever write any code in the first place? :)

**Comment by Grogyan** [comment]
This feature depends entirely on the firmware used.

There is currently some active discussion on the Marlin Firmware repository #https://github.com/MarlinFirmware/Marlin/issues/3106

**Comment by gddeen** [comment]
I do not see how the marlin firmware is related... Elaboration may help. I read the other discussion.
I don't think I'd rely on any info from the firmware... It may be accurate and exact, but who knows where the goes? I do trust the slicers are very accurate.  The only issues I see are filament changes and
stuff just going away (power outage, M112, M0, etc)

**Comment by MarcusWolschon** [comment]
I'm working on such a sensor
http://marcuswolschon.blogspot.de/2016/06/ultimaker-ii-filament-sensor-and-remote.html

it weights the spool using a load cell and will integrate as a plugin into OctoPi.
I just have to find out how to access job.filament.volume from within Python or Javascript.

**Comment by malnvenshorn** [comment]
I'm currently working on a [filament manager plugin](https://github.com/malnvenshorn/OctoPrint-FilamentManager) which will include some of the features mentioned here. It is still a work in progress, but feel free to check it out and give some feedback. Currently I'm not happy with the properties of profiles/spool (e.g. different color can have a different price), so there will be some changes.

**Comment by mamoit** [comment]
I have given @malnvenshorn 's plugin a run and it seems to do a pretty good job.

**Comment by foosel** [comment]
Ah... good point. Closing since there's a plugin available.
