### ISSUE TITLE
Printer profiles - identifier should be mandatory and overwrite exisiting one throws a silent error

### ISSUE THREAD

**Issue by imrahil** [foosel/OctoPrint#809]
1. What were you doing?
Tried to add new printer profile but didn't provide identifier. Also tried to add new profile with the same name as existing one.

2. What did you expect to happen?
For missing identifier I expect validation before sending a request.  With overwrite I expected alert with error message.

3. What happened instead?
Missing identifier creates profile which is not visible in UI (it creates .profile file on disk). Overwrite throws an error but there is no handlers for that in JS.

4. Branch & Commit or Version of OctoPrint:
devel

5. Printer model & used firmware incl. version (if applicable - always include if unsure):
virtual

6. Browser and Version of Browser, Operating System running Browser (if applicable - always include if unsure):
Firefox

7. Link to octoprint.log on gist.github.com or pastebin.com:

8. Link to contents of terminal tab or serial.log on gist.github.com or pastebin.com (if applicable - always include if unsure or reporting communication issues):

9. Link to contents of Javascript console in the browser on gist.github.com or pastebin.com or alternatively a screenshot (if applicable - always include if unsure or reporting UI issues):

10. Screenshot(s) showing the problem (if applicable - always include if unsure or reporting UI issues):

I have read the FAQ.

**Comment by foosel** [comment]
Fixed in `devel`. Added some client side input validation and turned your simple alert into a proper pnotify error (shouldn't occur anymore though unless something hiccups hard in the server since the submit button is now disabled into the data is sound).
