### ISSUE TITLE
Feature Request: Arbitrary commands staged for after print

### ISSUE THREAD

**Issue by AgentZombie** [foosel/OctoPrint#813]
Low priority, purely nice to have.

It would be nifty if you could queue commands to be sent to the printer after the print has completed. Sometimes I'd like to keep the extruder hot for the next print. sometimes I'd like to let it cool since I'm going shut the printer off. Sometimes I want to raise the temperature to clean out extruder before a filament change. Extra nice would be the ability to check a box on the Control tab to have the buttons I click be queued, rather than having to type in GCode to be queued.

I know you can send post-print commands via the slicer, but to do the above in the slicer I'd have to reslice depending on the post-print behavior I want.

**Comment by foosel** [comment]
Already implemented on the devel branch, Settings > GCODE Scripts :)
