### ISSUE TITLE
[Request] Add user to printing event payload

### ISSUE THREAD

**Issue by loelkes** [foosel/OctoPrint#847]
Hi,
it would be nice if the printing events could also have the user name (or an id) in the payload so stats can be made about who prints what etc.

**Comment by foosel** [comment]
That's a larger change since at the moment jobs have absolutely no knowledge at all about who triggered them. Users stop to exist basically on the outward facing API, internally there's no tracking at all.

**Comment by loelkes** [comment]
OK. Thanks for the quick response.
