### ISSUE TITLE
[devel] Docs say "template_header", but code says "header_addon"

### ISSUE THREAD

**Issue by markwal** [foosel/OctoPrint#848]
1. What were you doing?
Adding a part to the sidebar in a plugin via get_template_configs() using the template_header key

2. What did you expect to happen?
The template_header to show up in the header div

3. What happened instead?
Nothing

4. Branch & Commit or Version of OctoPrint:
devel a34cbc5

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure):

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure):

7. Link to octoprint.log on gist.github.com or pastebin.com:
https://gist.github.com/markwal/7ff6d6ce64246f9b986c

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues):

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):

I have read the FAQ.

http://docs.octoprint.org/en/devel/plugins/mixins.html#templateplugin says the sidebar template may also contain the template_header key:
"template_header	Additional template to include in the head section of the sidebar item. For an example of this, see the additional options included in the “Files” section."

The code seems to want header_addon, but perhaps that is for internal use not plugin?
I have this patch and it seems to work for me, but perhaps the intent was to rename header_addon or change the docs?
```
diff --git a/src/octoprint/templates/index.jinja2 b/src/octoprint/templates/index.jinja2
index d7aa1aa..78c2f78 100644
--- a/src/octoprint/templates/index.jinja2
+++ b/src/octoprint/templates/index.jinja2
@@ -52,6 +52,9 @@
                                 <a class="accordion-toggle" data-toggle="collapse" data-target="#{{ data._div }}">
                                     {% if "icon" in data %}<i class="icon-{{ data.icon }}"></i> {% endif %}{{ entry }}
                                 </a>
+                                {% if "template_header" in data %}
+                                    {% include data.template_header %}
+                                {% endif %}
                                 {% if "header_addon" in data %}
                                     {% include data.header_addon ignore missing %}
                                 {% endif %}
```
I think copying and pasting the patches into git issues kinda ruins the tabs.  :-(

**Comment by foosel** [comment]
> but perhaps the intent was to rename header_addon or change the docs?

Exactly this, but apparently over all that documentation writing I forgot that actual adjustments in the code, thanks for the heads-up, fixed now!

> I think copying and pasting the patches into git issues kinda ruins the tabs. :-(

You know, you could just create a pull request ;)
