### ISSUE TITLE
random freeze in windows

### ISSUE THREAD

**Issue by ekaggrat** [foosel/OctoPrint#868]
1. running octoprint on windows

2. the printer to work normally

3. the printer froze at a random location and kept the temperature at the last gcode

4. main branch github clone

5. 3dr delta running on standard ramps 1.4 with a lcd
   (if applicable - always include if unsure):

6. chrome and windows 7 x64

7. http://pastebin.com/c62MNnSs

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues):

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):

I have read the FAQ.

**Comment by foosel** [comment]
That looks more like an issue with tornado or your system than a problem within OctoPrint. So more a support case. Going to answer in the [G+ thread](https://plus.google.com/u/0/108050635154873068103/posts/M1aujsmFZPx) you already opened on that.
