### ISSUE TITLE
Title transparency broken - Chrome/Firefox

### ISSUE THREAD

**Issue by CupricReki** [foosel/OctoPrint#877]
Title bar transparency does not seem to be working as intended (Settings -> Appearance -> Transparent Color). Blocks appear behind title bar regardless of color chosen. 

Confirmed on chrome/firefox on win7 x64

![capture](https://cloud.githubusercontent.com/assets/6509200/7376160/1dfa8b42-ed9b-11e4-9764-c66c256d367f.JPG)

**Comment by foosel** [comment]
This *is* the intended look. It's a gimmick basically, but there really is no other way to "simulate" transparency on an opaque background such as a webpage, OctoPrint can't drill a hole in your monitor.

**Comment by CupricReki** [comment]
Haha, okay then!
