### ISSUE TITLE
[Request] Feature Request: Plugin event for file upload

### ISSUE THREAD

**Issue by quillford** [foosel/OctoPrint#885]
It would be nice to have a plugin event for when a file is uploaded, so that a post processor could be run on the gcode. Some printers, like the GUS Simpson, require a post processor for standard gcode to work on the printer.

**Comment by foosel** [comment]
Unless I misunderstand you: [FileUpload event](http://docs.octoprint.org/en/devel/events/index.html#file-handling) + [EventHandlerPlugin mixin](http://docs.octoprint.org/en/devel/plugins/mixins.html#eventhandlerplugin) :)
