### ISSUE TITLE
[Request] Allow downloading uploaded files

### ISSUE THREAD

**Issue by punkkeks** [foosel/OctoPrint#897]
When you use the extension_tree hook and allow uploading files other than gcode/stl filesm you are not able to access them. It may be because of the regex in https://github.com/foosel/OctoPrint/blob/devel/src/octoprint/server/__init__.py#L768
Either you will dynamicaly let it grow, respeting all hooks or you will allow all files to be downloaded (maybe expect .metadata.yaml, but I would like to see a whitelist)

**Comment by foosel** [comment]
Solved
