### ISSUE TITLE
[REQUEST] Add raspberry pi core temperature to graph display... or at least somewhere in the GUI

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#898]
ie log the activity of /opt/vc/bin/vcgencmd measure_temp
for raspi owners ;)

Thanks!

**Comment by imrahil** [comment]
I can add this value to NavBar Temp plugin :)
is there any way to call system commands like this one for temp? subprocess.Popen or sarge.run?

**Comment by foosel** [comment]
`sarge.run`

But for the sake of cross platform compatibility make it optional ;)

**Comment by imrahil** [comment]
sure. I found nice platform detection script from Adafruit - https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/Platform.py

**Comment by bolsoncerrado** [comment]
What plugin is that? ;)

**Comment by imrahil** [comment]
http://plugins.octoprint.org/plugins/navbartemp/

**Comment by bolsoncerrado** [comment]
Wohoo! I just realized on the new changes on the RCs and the plugin system! ;) good work!

**Comment by foosel** [comment]
Provided through [the NavbarTemp plugin](https://github.com/imrahil/OctoPrint-NavbarTemp) by @imrahil  (also on the plugin repository)
