### ISSUE TITLE
Need help with Octoprint!

### ISSUE THREAD

**Issue by clxrffdman** [foosel/OctoPrint#908]
I have read the FAQ on the website, however it does not seem to answer my problem.

My printer was sold to me by a company called Honeypoint3D. They showed me Octoprint and set it up for me. However, now that I have a problem, I can not answer it. The problem is that for months, the printer has been connecting to the printer just fine(it has a wireless antenna on the back of the printer), but for a week now, the printer has not been connecting to the Octoprint website that Honeypoint3D has set up. The site says that the serial port is AUTO, and that the Baudrate is 230400. I can not change the serial port to anything else. It does not let me control the printer in anyway anymore, and it is a big problem.

**Comment by foosel** [comment]
This is a support request. From the [contribution guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md) linked from every issue form:

> If you need **support** with a problem of your installation (e.g. if you have problems getting the webcam to work) or have a general **question**, the issue tracker is not the right place. Consult the [Mailinglist](https://groups.google.com/group/octoprint) or the [Google+ Community](https://plus.google.com/communities/102771308349328485741) instead!

Also, I have no idea what "Honeypoint3D" setup exactly, so since you probably paid them for that, you should also get your support from them.
