### ISSUE TITLE
[Request] Update 'Estimated Print Time' based on previously successful print time

### ISSUE THREAD

**Issue by nhfoley** [foosel/OctoPrint#926]
(Resubmitting because I flubbed the formatting on the first try...)

Seems like this would be a relatively straightforward feature - It would be great if after a print completes successfully, the 'estimated print time' for that file was updated based on the time it actually took to print the first time.

This would make subsequent prints of the same file better informed and would make it easier to plan out print capacity when running many of the same part.

**Comment by foosel** [comment]
Already implemented in devel
