### ISSUE TITLE
[Request] Update knockout.js to version 3.3.0

### ISSUE THREAD

**Issue by punkkeks** [foosel/OctoPrint#939]
For my current application it would be nice to use knockout in version 3.3 (because of [this bug][0]). I downloaded it and renamed it to knockout.js, restarted octoprint and everything runs like before. No errors in console, no visible crap.
I admit, that this needs further investigation, but at first glance, it works fine.

> Knockout.js takes backward compatibility seriously. If you’re using a recent v2.x build, you will typically be able to drop in Knockout v3.0.0 without having to make any changes to your application code. Version 3.0.0 is intended to be fully backward-compatible except for a few carefully chosen design changes that enable major new features or fix longstanding issues.

[0]: http://knockoutjs.com/upgrade-notes/v3.0.0.html#bindings-are-now-refreshed-independently

**Comment by foosel** [comment]
I'm a bit worried about http://knockoutjs.com/upgrade-notes/v3.0.0.html#checked-binding-uses-strict-equality and would like to evaluate this a bit myself, so this is nothing I'll put into 1.2.0. However I'll put it on the TODO list for 1.2.1

**Comment by foosel** [comment]
Updated in `maintenance` and `devel` branches, will become part of 1.2.9
