### ISSUE TITLE
After installing plugin it's not possible to save settings

### ISSUE THREAD

**Issue by imrahil** [foosel/OctoPrint#942]
1. What were you doing?
Installed a plugin and tried to click save button on settings dialog

2. What did you expect to happen?
Save settings and close a dialog

3. What happened instead?
No response. In logs however I found detailed error:
https://gist.github.com/imrahil/2e8d59604ca5490e99f5

4. Branch & Commit or Version of OctoPrint:
devel or master - both are affected

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure):

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure):
Firefox

7. Link to octoprint.log on gist.github.com or pastebin.com
   (ALWAYS INCLUDE AND DO NOT TRUNCATE):
https://gist.github.com/imrahil/2e8d59604ca5490e99f5

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues AND
   DO NOT TRUNCATE):

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):

I have read the FAQ.

**Comment by MrBreadWater** [comment]
Did you ever find a solution?
