### ISSUE TITLE
Option to disable checksums

### ISSUE THREAD

**Issue by mic159** [foosel/OctoPrint#949]
Unfortunately my hardware (a Benbox Laser Engraver) does not support GCODE checksums and line numbers.
I noticed that there is an option to force checksums to be always ON, but not the other way around.

Would it be possible to add an option to disable it?

I couldn't see a way to fix it with plugins, so to make it work I can change [util/comm.py:1524](https://github.com/foosel/OctoPrint/blob/e722c2f8adef5dce085205977a0e83331aba5837/src/octoprint/util/comm.py#L1524) like this:
```python
# now comes the part where we increase line numbers and send stuff - no turning back now
#if (gcode is not None or self._sendChecksumWithUnknownCommands) and (self.isPrinting() or self._alwaysSendChecksum):
#    linenumber = self._currentLine
#    self._addToLastLines(command)
#    self._currentLine += 1
#    self._doSendWithChecksum(command, linenumber)
#else:
self._doSendWithoutChecksum(command)
```

1. What were you doing?
   Pressed print on a `.gcode` file.

2. What did you expect to happen?
   The engraver to whirl into action.

3. What happened instead?
   The engraver sends back `ok` but nothing happens.

4. Branch & Commit or Version of OctoPrint:
    `Version: 1.2.0-rc1-3-g46711ce-dirty (master branch)`

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure):
   `benbox laser 2.7(c) mul 2014.12.25`

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure):
   Ubuntu 14.04 - Chrome

7. Link to octoprint.log on gist.github.com or pastebin.com
   (ALWAYS INCLUDE AND DO NOT TRUNCATE):
   https://gist.github.com/mic159/9ea8c2a8ff66e4c7233c

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues AND
   DO NOT TRUNCATE):
   https://gist.github.com/mic159/9ea8c2a8ff66e4c7233c

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):
  N/A

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):
   N/A

I have read the FAQ.

**Comment by foosel** [comment]
Implemented in `devel` branch.
