### ISSUE TITLE
[Request] In gcode viewer center and zoom default ?

### ISSUE THREAD

**Issue by manu69x** [foosel/OctoPrint#954]
I have a delta printer
in gcodeviewer folder there is a way to preset
center and zoom default ?

**Comment by foosel** [comment]
Yes, look in the settings, printer parameters (or printer profiles on 1.2.0), bed center. Has been there for a long time. The Settings dialog is your friend.

**Comment by manu69x** [comment]
I have Octopi with Octoprint Version: 1.1.1-30-g4fede5a (master branch)
Can bee that I have old version ?

**Comment by foosel** [comment]
Indeed looks like it, although I could have sworn that was already available on 1.1.1. But 1.2.0 is about to be released. Use that then.

**Comment by imrahil** [comment]
+1 for that - there is no option to set this values to true by default...
@foosel "bed center" is for machine, not for gcodeviewer

**Comment by foosel** [comment]
@imrahil guess what the gcode viewer is evaluating to decide on where to render the origin, which the OP was also asking about...

And for allowing to store the gcode viewer settings, there already is a ticket for that, use the search, people, that's what it's there for ;)
