### ISSUE TITLE
Tornado Content-Length too long uploading plugin.

### ISSUE THREAD

**Issue by foofoodog** [foosel/OctoPrint#957]
Uploading a plugin from the desktop fails with a "tornado.general - INFO - Malformed HTTP message from 127.0.0.1: Content-Length too long" 

1.3.0-dev-7-g5f0c89c on Pi2 from Octopi image using file Octoprint-STLViewer-master.zip (116,759 bytes) from the repo.

I have read the FAQ and I love cookies as well.

**Comment by foofoodog** [comment]
Changing the non uploads maxSize in src\octoprint\settings.py fixes it.

**Comment by jneilliii** [comment]
Is that on line 106?  I've had that issue before with some of the other plugins with upload capability and I think this might fix that for me as well.  Hope you like my hacked together plugin (STL Viewer).

**Comment by foofoodog** [comment]
Yes, 106. I guess I will clone devel again so I can create diffs since I am back here hacking on it again.
And yes I like the STL viewer, any way to show an axis so I can get an idea of the orientation? ;)

**Comment by foosel** [comment]
Should be fixed by the above commit, can someone please verify?

**Comment by foofoodog** [comment]
You beat me to the patch. My way was brutal anyway. So you want I should test the a 51 MB plugin now;) Or just one more than 100k?

**Comment by foosel** [comment]
more than 100k would be great ;)

**Comment by foofoodog** [comment]
My git foo is so weak. I can not seem to get this code to come down.

**Comment by foosel** [comment]
You are on the devel branch? And trying to pull from my repo, not maybe your fork or something like this?

**Comment by foofoodog** [comment]
.git checkout devel
	Already on 'devel'
git fetch origin && git reset --hard origin/devel
	HEAD is now at 5f0c89c Fix: Ensure correct "upload date" for all added files
Doing something wrong since 5f0c89c is behind

**Comment by foosel** [comment]
`git remote -v | grep origin` ?

**Comment by foofoodog** [comment]
DOH!
http://gnet.homelinux.com/git/OctoPrint.git. 
So an OctoPi thing from back in April. grrr. That you provided a 1 line fix for 4 days ago (https://github.com/guysoft/OctoPi/issues/74).
I am surprised they even let me use this site given how bad I am at it.

Fix is confirmed for my scenario, thank you very much.

**Comment by jneilliii** [comment]
That fixes it for the plugin manager, but doesn't for other plugins.  Should they implement the settings change the same way within their plugin?

**Comment by foosel** [comment]
@jneilliii yes, that's why there is a hook for that. having the body size limited for everything but whitelisted end points is to protect the server from malicious requests (large bodies can be especially problematic on something like a pi). OctoPrint can't possibly know about endpoints provided by plugins that should be whitelisted, hence that hook for them to tell it about them.
