### ISSUE TITLE
[Request] Auto Levelling

### ISSUE THREAD

**Issue by manu69x** [foosel/OctoPrint#959]
Add a button in the Control folder for perform Auto Levelling and Store Data ?
Maybe a configurable button ?
For my delta autolevelling is G30 A and then M500

**Comment by foosel** [comment]
http://docs.octoprint.org/en/master/features/custom_controls.html

**Comment by manu69x** [comment]
you are awesome :)

2015-07-02 19:36 GMT+02:00 Gina Häußge <notifications@github.com>:
