### ISSUE TITLE
[Request] Additions to "State" Window

### ISSUE THREAD

**Issue by KC703** [foosel/OctoPrint#977]
Hello,

Can we bring back the "Layer Height" to the "State" window?  It used to be there, but seemed to disappear in the devel version of OctoPrint.  The layer height is available in the "GCode Viewer" tab, but this often times can't be loaded on a tablet browser.

Last request for the "State" window, is there any chance of displaying the fan speed?  I guess the problem here is that it there is no way to track the fan speed outside of the g-code instruction.

Thanks for the consideration.
Ken

**Comment by foosel** [comment]
I thought I'd answered that already. [Use this plugin](http://plugins.octoprint.org/plugins/displayz/).
