### ISSUE TITLE
[Request] Notification/event for "setpoint reached"

### ISSUE THREAD

**Issue by spapadim** [foosel/OctoPrint#993]
On my lower-powered heatbeds, it takes a while (dfn: >15min) to reach target temperature.  Therefore, I'd like to modify Growl or Pushbullet plugin to notify me for manually commanded temperature changes.  

Based on quick browsing of code, I see two options: (i) poll-based, which could be implemented with current functionality, and might be ok for heatbed (e.g., a 30sec repeating timer might be acceptable); (ii) event-based, which seems would require a new event in Octoprint core (current thought: in M105 response parsing code, add simple logic "if status != printing && abs(target - actual) < threshold for more than X sec then fire event").  

Would adding such a "TargetTemperatureReached" event make sense?  Or is there a better way with current functionality?

**Comment by foosel** [comment]
I believe this to be a duplicate of #565
